/*
 * Viafirma API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.3.29-r83-596fbc1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.api;

import com.fasterxml.jackson.core.type.TypeReference;

import org.openapitools.client.ApiException;
import org.openapitools.client.ApiClient;
import org.openapitools.client.Configuration;
import org.openapitools.client.model.*;
import org.openapitools.client.Pair;

import org.openapitools.client.model.ApiErrorMessage;
import org.openapitools.client.model.BiometricSignatureRequestDTO;
import org.openapitools.client.model.BiometricSignatureResponseDTO;
import org.openapitools.client.model.SignaturePromotionRequestDTO;
import org.openapitools.client.model.SignaturePromotionResponseDTO;
import org.openapitools.client.model.SignatureRequestDTO;
import org.openapitools.client.model.SignatureResponseDTO;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-03-04T11:20:43.685+01:00[Europe/Paris]")
public class ServerSignatureResourceApi {
  private ApiClient apiClient;

  public ServerSignatureResourceApi() {
    this(Configuration.getDefaultApiClient());
  }

  public ServerSignatureResourceApi(ApiClient apiClient) {
    this.apiClient = apiClient;
  }

  public ApiClient getApiClient() {
    return apiClient;
  }

  public void setApiClient(ApiClient apiClient) {
    this.apiClient = apiClient;
  }

  /**
   * Biometric Sign Service
   * 
   * @param biometricSignatureRequestDTO  (required)
   * @return BiometricSignatureResponseDTO
   * @throws ApiException if fails to make API call
   */
  public BiometricSignatureResponseDTO biometricSignDocument(BiometricSignatureRequestDTO biometricSignatureRequestDTO) throws ApiException {
    Object localVarPostBody = biometricSignatureRequestDTO;
    
    // verify the required parameter 'biometricSignatureRequestDTO' is set
    if (biometricSignatureRequestDTO == null) {
      throw new ApiException(400, "Missing the required parameter 'biometricSignatureRequestDTO' when calling biometricSignDocument");
    }
    
    // create path and map variables
    String localVarPath = "/api/sign/biometric";

    // query params
    List<Pair> localVarQueryParams = new ArrayList<Pair>();
    List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
    Map<String, String> localVarHeaderParams = new HashMap<String, String>();
    Map<String, String> localVarCookieParams = new HashMap<String, String>();
    Map<String, Object> localVarFormParams = new HashMap<String, Object>();


    
    
    
    final String[] localVarAccepts = {
      "application/json"
    };
    final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);

    final String[] localVarContentTypes = {
      "application/json"
    };
    final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);

    String[] localVarAuthNames = new String[] { "basicAuth" };

    TypeReference<BiometricSignatureResponseDTO> localVarReturnType = new TypeReference<BiometricSignatureResponseDTO>() {};
    return apiClient.invokeAPI(
        localVarPath,
        "POST",
        localVarQueryParams,
        localVarCollectionQueryParams,
        localVarPostBody,
        localVarHeaderParams,
        localVarCookieParams,
        localVarFormParams,
        localVarAccept,
        localVarContentType,
        localVarAuthNames,
        localVarReturnType
    );
  }
  /**
   * Promotion signature service
   * 
   * @param signaturePromotionRequestDTO  (required)
   * @return SignaturePromotionResponseDTO
   * @throws ApiException if fails to make API call
   */
  public SignaturePromotionResponseDTO promoteSignature(SignaturePromotionRequestDTO signaturePromotionRequestDTO) throws ApiException {
    Object localVarPostBody = signaturePromotionRequestDTO;
    
    // verify the required parameter 'signaturePromotionRequestDTO' is set
    if (signaturePromotionRequestDTO == null) {
      throw new ApiException(400, "Missing the required parameter 'signaturePromotionRequestDTO' when calling promoteSignature");
    }
    
    // create path and map variables
    String localVarPath = "/api/sign/promote";

    // query params
    List<Pair> localVarQueryParams = new ArrayList<Pair>();
    List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
    Map<String, String> localVarHeaderParams = new HashMap<String, String>();
    Map<String, String> localVarCookieParams = new HashMap<String, String>();
    Map<String, Object> localVarFormParams = new HashMap<String, Object>();


    
    
    
    final String[] localVarAccepts = {
      "application/json", "*/*"
    };
    final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);

    final String[] localVarContentTypes = {
      "application/json"
    };
    final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);

    String[] localVarAuthNames = new String[] { "basicAuth" };

    TypeReference<SignaturePromotionResponseDTO> localVarReturnType = new TypeReference<SignaturePromotionResponseDTO>() {};
    return apiClient.invokeAPI(
        localVarPath,
        "POST",
        localVarQueryParams,
        localVarCollectionQueryParams,
        localVarPostBody,
        localVarHeaderParams,
        localVarCookieParams,
        localVarFormParams,
        localVarAccept,
        localVarContentType,
        localVarAuthNames,
        localVarReturnType
    );
  }
  /**
   * Digital sign service
   * 
   * @param signatureRequestDTO  (required)
   * @return SignatureResponseDTO
   * @throws ApiException if fails to make API call
   */
  public SignatureResponseDTO signDocument(SignatureRequestDTO signatureRequestDTO) throws ApiException {
    Object localVarPostBody = signatureRequestDTO;
    
    // verify the required parameter 'signatureRequestDTO' is set
    if (signatureRequestDTO == null) {
      throw new ApiException(400, "Missing the required parameter 'signatureRequestDTO' when calling signDocument");
    }
    
    // create path and map variables
    String localVarPath = "/api/sign";

    // query params
    List<Pair> localVarQueryParams = new ArrayList<Pair>();
    List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
    Map<String, String> localVarHeaderParams = new HashMap<String, String>();
    Map<String, String> localVarCookieParams = new HashMap<String, String>();
    Map<String, Object> localVarFormParams = new HashMap<String, Object>();


    
    
    
    final String[] localVarAccepts = {
      "application/json"
    };
    final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);

    final String[] localVarContentTypes = {
      "application/json"
    };
    final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);

    String[] localVarAuthNames = new String[] { "basicAuth" };

    TypeReference<SignatureResponseDTO> localVarReturnType = new TypeReference<SignatureResponseDTO>() {};
    return apiClient.invokeAPI(
        localVarPath,
        "POST",
        localVarQueryParams,
        localVarCollectionQueryParams,
        localVarPostBody,
        localVarHeaderParams,
        localVarCookieParams,
        localVarFormParams,
        localVarAccept,
        localVarContentType,
        localVarAuthNames,
        localVarReturnType
    );
  }
}
