/*
 * Viafirma API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.3.29-r83-596fbc1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.api;

import com.fasterxml.jackson.core.type.TypeReference;

import org.openapitools.client.ApiException;
import org.openapitools.client.ApiClient;
import org.openapitools.client.Configuration;
import org.openapitools.client.model.*;
import org.openapitools.client.Pair;

import org.openapitools.client.model.ApiErrorMessage;
import org.openapitools.client.model.ValidateCertificateRequestDTO;
import org.openapitools.client.model.ValidateCertificateResponseDTO;
import org.openapitools.client.model.ValidationFileRequestDTO;
import org.openapitools.client.model.ValidationFileResponseDTO;
import org.openapitools.client.model.ValidationHashRequestDTO;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-03-04T11:20:43.685+01:00[Europe/Paris]")
public class ValidationResourceApi {
  private ApiClient apiClient;

  public ValidationResourceApi() {
    this(Configuration.getDefaultApiClient());
  }

  public ValidationResourceApi(ApiClient apiClient) {
    this.apiClient = apiClient;
  }

  public ApiClient getApiClient() {
    return apiClient;
  }

  public void setApiClient(ApiClient apiClient) {
    this.apiClient = apiClient;
  }

  /**
   * Validate certificate
   * 
   * @param validateCertificateRequestDTO  (required)
   * @return ValidateCertificateResponseDTO
   * @throws ApiException if fails to make API call
   */
  public ValidateCertificateResponseDTO validateCertificate(ValidateCertificateRequestDTO validateCertificateRequestDTO) throws ApiException {
    Object localVarPostBody = validateCertificateRequestDTO;
    
    // verify the required parameter 'validateCertificateRequestDTO' is set
    if (validateCertificateRequestDTO == null) {
      throw new ApiException(400, "Missing the required parameter 'validateCertificateRequestDTO' when calling validateCertificate");
    }
    
    // create path and map variables
    String localVarPath = "/api/validation/certificate";

    // query params
    List<Pair> localVarQueryParams = new ArrayList<Pair>();
    List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
    Map<String, String> localVarHeaderParams = new HashMap<String, String>();
    Map<String, String> localVarCookieParams = new HashMap<String, String>();
    Map<String, Object> localVarFormParams = new HashMap<String, Object>();


    
    
    
    final String[] localVarAccepts = {
      "application/json", "*/*"
    };
    final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);

    final String[] localVarContentTypes = {
      "application/json"
    };
    final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);

    String[] localVarAuthNames = new String[] { "basicAuth" };

    TypeReference<ValidateCertificateResponseDTO> localVarReturnType = new TypeReference<ValidateCertificateResponseDTO>() {};
    return apiClient.invokeAPI(
        localVarPath,
        "POST",
        localVarQueryParams,
        localVarCollectionQueryParams,
        localVarPostBody,
        localVarHeaderParams,
        localVarCookieParams,
        localVarFormParams,
        localVarAccept,
        localVarContentType,
        localVarAuthNames,
        localVarReturnType
    );
  }
  /**
   * Verify a hash signature
   * Allow validate a signed hash
   * @param validationHashRequestDTO  (required)
   * @return ValidationFileResponseDTO
   * @throws ApiException if fails to make API call
   */
  public ValidationFileResponseDTO verifyHashSignature(ValidationHashRequestDTO validationHashRequestDTO) throws ApiException {
    Object localVarPostBody = validationHashRequestDTO;
    
    // verify the required parameter 'validationHashRequestDTO' is set
    if (validationHashRequestDTO == null) {
      throw new ApiException(400, "Missing the required parameter 'validationHashRequestDTO' when calling verifyHashSignature");
    }
    
    // create path and map variables
    String localVarPath = "/api/validation/hash";

    // query params
    List<Pair> localVarQueryParams = new ArrayList<Pair>();
    List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
    Map<String, String> localVarHeaderParams = new HashMap<String, String>();
    Map<String, String> localVarCookieParams = new HashMap<String, String>();
    Map<String, Object> localVarFormParams = new HashMap<String, Object>();


    
    
    
    final String[] localVarAccepts = {
      "application/json", "*/*"
    };
    final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);

    final String[] localVarContentTypes = {
      "application/json"
    };
    final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);

    String[] localVarAuthNames = new String[] { "basicAuth" };

    TypeReference<ValidationFileResponseDTO> localVarReturnType = new TypeReference<ValidationFileResponseDTO>() {};
    return apiClient.invokeAPI(
        localVarPath,
        "POST",
        localVarQueryParams,
        localVarCollectionQueryParams,
        localVarPostBody,
        localVarHeaderParams,
        localVarCookieParams,
        localVarFormParams,
        localVarAccept,
        localVarContentType,
        localVarAuthNames,
        localVarReturnType
    );
  }
  /**
   * Verify signature
   * Allow validate a signed document
   * @param validationFileRequestDTO  (required)
   * @return ValidationFileResponseDTO
   * @throws ApiException if fails to make API call
   */
  public ValidationFileResponseDTO verifySignature(ValidationFileRequestDTO validationFileRequestDTO) throws ApiException {
    Object localVarPostBody = validationFileRequestDTO;
    
    // verify the required parameter 'validationFileRequestDTO' is set
    if (validationFileRequestDTO == null) {
      throw new ApiException(400, "Missing the required parameter 'validationFileRequestDTO' when calling verifySignature");
    }
    
    // create path and map variables
    String localVarPath = "/api/validation/";

    // query params
    List<Pair> localVarQueryParams = new ArrayList<Pair>();
    List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
    Map<String, String> localVarHeaderParams = new HashMap<String, String>();
    Map<String, String> localVarCookieParams = new HashMap<String, String>();
    Map<String, Object> localVarFormParams = new HashMap<String, Object>();


    
    
    
    final String[] localVarAccepts = {
      "application/json", "*/*"
    };
    final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);

    final String[] localVarContentTypes = {
      "application/json"
    };
    final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);

    String[] localVarAuthNames = new String[] { "basicAuth" };

    TypeReference<ValidationFileResponseDTO> localVarReturnType = new TypeReference<ValidationFileResponseDTO>() {};
    return apiClient.invokeAPI(
        localVarPath,
        "POST",
        localVarQueryParams,
        localVarCollectionQueryParams,
        localVarPostBody,
        localVarHeaderParams,
        localVarCookieParams,
        localVarFormParams,
        localVarAccept,
        localVarContentType,
        localVarAuthNames,
        localVarReturnType
    );
  }
}
