/*
 * Viafirma API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.3.29-r83-596fbc1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * BDSignaturePointDTO
 */
@JsonPropertyOrder({
  BDSignaturePointDTO.JSON_PROPERTY_X,
  BDSignaturePointDTO.JSON_PROPERTY_Y,
  BDSignaturePointDTO.JSON_PROPERTY_PRESSURE,
  BDSignaturePointDTO.JSON_PROPERTY_MILLISECONDS,
  BDSignaturePointDTO.JSON_PROPERTY_PEN_ELEVATION,
  BDSignaturePointDTO.JSON_PROPERTY_PEN_ROTATION,
  BDSignaturePointDTO.JSON_PROPERTY_PEN_AZIMUTH,
  BDSignaturePointDTO.JSON_PROPERTY_S
})
@JsonTypeName("BDSignaturePointDTO")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-03-04T11:20:43.685+01:00[Europe/Paris]")
public class BDSignaturePointDTO {
  public static final String JSON_PROPERTY_X = "x";
  private Double x;

  public static final String JSON_PROPERTY_Y = "y";
  private Double y;

  public static final String JSON_PROPERTY_PRESSURE = "pressure";
  private Double pressure;

  public static final String JSON_PROPERTY_MILLISECONDS = "milliseconds";
  private Long milliseconds;

  public static final String JSON_PROPERTY_PEN_ELEVATION = "penElevation";
  private Double penElevation;

  public static final String JSON_PROPERTY_PEN_ROTATION = "penRotation";
  private Double penRotation;

  public static final String JSON_PROPERTY_PEN_AZIMUTH = "penAzimuth";
  private Double penAzimuth;

  public static final String JSON_PROPERTY_S = "s";
  private Boolean s;

  public BDSignaturePointDTO() { 
  }

  public BDSignaturePointDTO x(Double x) {
    
    this.x = x;
    return this;
  }

   /**
   * Get x
   * @return x
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_X)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getX() {
    return x;
  }


  @JsonProperty(JSON_PROPERTY_X)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setX(Double x) {
    this.x = x;
  }


  public BDSignaturePointDTO y(Double y) {
    
    this.y = y;
    return this;
  }

   /**
   * Get y
   * @return y
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_Y)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getY() {
    return y;
  }


  @JsonProperty(JSON_PROPERTY_Y)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setY(Double y) {
    this.y = y;
  }


  public BDSignaturePointDTO pressure(Double pressure) {
    
    this.pressure = pressure;
    return this;
  }

   /**
   * Get pressure
   * @return pressure
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_PRESSURE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getPressure() {
    return pressure;
  }


  @JsonProperty(JSON_PROPERTY_PRESSURE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPressure(Double pressure) {
    this.pressure = pressure;
  }


  public BDSignaturePointDTO milliseconds(Long milliseconds) {
    
    this.milliseconds = milliseconds;
    return this;
  }

   /**
   * Get milliseconds
   * @return milliseconds
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_MILLISECONDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getMilliseconds() {
    return milliseconds;
  }


  @JsonProperty(JSON_PROPERTY_MILLISECONDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMilliseconds(Long milliseconds) {
    this.milliseconds = milliseconds;
  }


  public BDSignaturePointDTO penElevation(Double penElevation) {
    
    this.penElevation = penElevation;
    return this;
  }

   /**
   * Get penElevation
   * @return penElevation
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_PEN_ELEVATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getPenElevation() {
    return penElevation;
  }


  @JsonProperty(JSON_PROPERTY_PEN_ELEVATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPenElevation(Double penElevation) {
    this.penElevation = penElevation;
  }


  public BDSignaturePointDTO penRotation(Double penRotation) {
    
    this.penRotation = penRotation;
    return this;
  }

   /**
   * Get penRotation
   * @return penRotation
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_PEN_ROTATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getPenRotation() {
    return penRotation;
  }


  @JsonProperty(JSON_PROPERTY_PEN_ROTATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPenRotation(Double penRotation) {
    this.penRotation = penRotation;
  }


  public BDSignaturePointDTO penAzimuth(Double penAzimuth) {
    
    this.penAzimuth = penAzimuth;
    return this;
  }

   /**
   * Get penAzimuth
   * @return penAzimuth
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_PEN_AZIMUTH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getPenAzimuth() {
    return penAzimuth;
  }


  @JsonProperty(JSON_PROPERTY_PEN_AZIMUTH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPenAzimuth(Double penAzimuth) {
    this.penAzimuth = penAzimuth;
  }


  public BDSignaturePointDTO s(Boolean s) {
    
    this.s = s;
    return this;
  }

   /**
   * Get s
   * @return s
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_S)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getS() {
    return s;
  }


  @JsonProperty(JSON_PROPERTY_S)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setS(Boolean s) {
    this.s = s;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BDSignaturePointDTO bdSignaturePointDTO = (BDSignaturePointDTO) o;
    return Objects.equals(this.x, bdSignaturePointDTO.x) &&
        Objects.equals(this.y, bdSignaturePointDTO.y) &&
        Objects.equals(this.pressure, bdSignaturePointDTO.pressure) &&
        Objects.equals(this.milliseconds, bdSignaturePointDTO.milliseconds) &&
        Objects.equals(this.penElevation, bdSignaturePointDTO.penElevation) &&
        Objects.equals(this.penRotation, bdSignaturePointDTO.penRotation) &&
        Objects.equals(this.penAzimuth, bdSignaturePointDTO.penAzimuth) &&
        Objects.equals(this.s, bdSignaturePointDTO.s);
  }

  @Override
  public int hashCode() {
    return Objects.hash(x, y, pressure, milliseconds, penElevation, penRotation, penAzimuth, s);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BDSignaturePointDTO {\n");
    sb.append("    x: ").append(toIndentedString(x)).append("\n");
    sb.append("    y: ").append(toIndentedString(y)).append("\n");
    sb.append("    pressure: ").append(toIndentedString(pressure)).append("\n");
    sb.append("    milliseconds: ").append(toIndentedString(milliseconds)).append("\n");
    sb.append("    penElevation: ").append(toIndentedString(penElevation)).append("\n");
    sb.append("    penRotation: ").append(toIndentedString(penRotation)).append("\n");
    sb.append("    penAzimuth: ").append(toIndentedString(penAzimuth)).append("\n");
    sb.append("    s: ").append(toIndentedString(s)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

