/*
 * Viafirma API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.3.29-r83-596fbc1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.BDSignatureStrokeDTO;
import org.openapitools.client.model.ConfigTsaDTO;
import org.openapitools.client.model.EvidenceDeviceDTO;
import org.openapitools.client.model.GeolocationDTO;
import org.openapitools.client.model.PositionDTO;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * BiometricSignatureRequestDTO
 */
@JsonPropertyOrder({
  BiometricSignatureRequestDTO.JSON_PROPERTY_CODE,
  BiometricSignatureRequestDTO.JSON_PROPERTY_REASON,
  BiometricSignatureRequestDTO.JSON_PROPERTY_CIPHER_CERTIFICATE_ALIAS,
  BiometricSignatureRequestDTO.JSON_PROPERTY_BIOMETRIC_CERTIFICATE_ALIAS,
  BiometricSignatureRequestDTO.JSON_PROPERTY_BIOMETRIC_CERTIFICATE_PASS,
  BiometricSignatureRequestDTO.JSON_PROPERTY_FILE_BASE64,
  BiometricSignatureRequestDTO.JSON_PROPERTY_IMAGE_BASE64,
  BiometricSignatureRequestDTO.JSON_PROPERTY_STROKES,
  BiometricSignatureRequestDTO.JSON_PROPERTY_DEVICE,
  BiometricSignatureRequestDTO.JSON_PROPERTY_GEOLOCATION,
  BiometricSignatureRequestDTO.JSON_PROPERTY_SIGNATURE_TYPE,
  BiometricSignatureRequestDTO.JSON_PROPERTY_TSA,
  BiometricSignatureRequestDTO.JSON_PROPERTY_POSITIONS,
  BiometricSignatureRequestDTO.JSON_PROPERTY_ADD_DIGITAL_SIGNATURE,
  BiometricSignatureRequestDTO.JSON_PROPERTY_DIGITAL_SIGNATURE_CERTIFICATE_ALIAS,
  BiometricSignatureRequestDTO.JSON_PROPERTY_DIGITAL_SIGNATURE_CERTIFICATE_PASS
})
@JsonTypeName("BiometricSignatureRequestDTO")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-03-04T11:20:43.685+01:00[Europe/Paris]")
public class BiometricSignatureRequestDTO {
  public static final String JSON_PROPERTY_CODE = "code";
  private String code;

  public static final String JSON_PROPERTY_REASON = "reason";
  private String reason;

  public static final String JSON_PROPERTY_CIPHER_CERTIFICATE_ALIAS = "cipherCertificateAlias";
  private String cipherCertificateAlias;

  public static final String JSON_PROPERTY_BIOMETRIC_CERTIFICATE_ALIAS = "biometricCertificateAlias";
  private String biometricCertificateAlias;

  public static final String JSON_PROPERTY_BIOMETRIC_CERTIFICATE_PASS = "biometricCertificatePass";
  private String biometricCertificatePass;

  public static final String JSON_PROPERTY_FILE_BASE64 = "fileBase64";
  private String fileBase64;

  public static final String JSON_PROPERTY_IMAGE_BASE64 = "imageBase64";
  private String imageBase64;

  public static final String JSON_PROPERTY_STROKES = "strokes";
  private List<BDSignatureStrokeDTO> strokes = null;

  public static final String JSON_PROPERTY_DEVICE = "device";
  private EvidenceDeviceDTO device;

  public static final String JSON_PROPERTY_GEOLOCATION = "geolocation";
  private GeolocationDTO geolocation;

  /**
   * Gets or Sets signatureType
   */
  public enum SignatureTypeEnum {
    CADES_B("CADES_B"),
    
    CADES_T("CADES_T"),
    
    CADES_LT("CADES_LT"),
    
    CADES_LTA("CADES_LTA"),
    
    PADES_B("PADES_B"),
    
    PADES_T("PADES_T"),
    
    PADES_LT("PADES_LT"),
    
    PADES_LTA("PADES_LTA"),
    
    XADES_B("XADES_B"),
    
    XADES_T("XADES_T"),
    
    XADES_LT("XADES_LT"),
    
    XADES_LTA("XADES_LTA");

    private String value;

    SignatureTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static SignatureTypeEnum fromValue(String value) {
      for (SignatureTypeEnum b : SignatureTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_SIGNATURE_TYPE = "signatureType";
  private SignatureTypeEnum signatureType;

  public static final String JSON_PROPERTY_TSA = "tsa";
  private ConfigTsaDTO tsa;

  public static final String JSON_PROPERTY_POSITIONS = "positions";
  private List<PositionDTO> positions = null;

  public static final String JSON_PROPERTY_ADD_DIGITAL_SIGNATURE = "addDigitalSignature";
  private Boolean addDigitalSignature;

  public static final String JSON_PROPERTY_DIGITAL_SIGNATURE_CERTIFICATE_ALIAS = "digitalSignatureCertificateAlias";
  private String digitalSignatureCertificateAlias;

  public static final String JSON_PROPERTY_DIGITAL_SIGNATURE_CERTIFICATE_PASS = "digitalSignatureCertificatePass";
  private String digitalSignatureCertificatePass;

  public BiometricSignatureRequestDTO() { 
  }

  public BiometricSignatureRequestDTO code(String code) {
    
    this.code = code;
    return this;
  }

   /**
   * Get code
   * @return code
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCode() {
    return code;
  }


  @JsonProperty(JSON_PROPERTY_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCode(String code) {
    this.code = code;
  }


  public BiometricSignatureRequestDTO reason(String reason) {
    
    this.reason = reason;
    return this;
  }

   /**
   * Get reason
   * @return reason
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_REASON)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getReason() {
    return reason;
  }


  @JsonProperty(JSON_PROPERTY_REASON)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setReason(String reason) {
    this.reason = reason;
  }


  public BiometricSignatureRequestDTO cipherCertificateAlias(String cipherCertificateAlias) {
    
    this.cipherCertificateAlias = cipherCertificateAlias;
    return this;
  }

   /**
   * Get cipherCertificateAlias
   * @return cipherCertificateAlias
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CIPHER_CERTIFICATE_ALIAS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCipherCertificateAlias() {
    return cipherCertificateAlias;
  }


  @JsonProperty(JSON_PROPERTY_CIPHER_CERTIFICATE_ALIAS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCipherCertificateAlias(String cipherCertificateAlias) {
    this.cipherCertificateAlias = cipherCertificateAlias;
  }


  public BiometricSignatureRequestDTO biometricCertificateAlias(String biometricCertificateAlias) {
    
    this.biometricCertificateAlias = biometricCertificateAlias;
    return this;
  }

   /**
   * Get biometricCertificateAlias
   * @return biometricCertificateAlias
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_BIOMETRIC_CERTIFICATE_ALIAS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getBiometricCertificateAlias() {
    return biometricCertificateAlias;
  }


  @JsonProperty(JSON_PROPERTY_BIOMETRIC_CERTIFICATE_ALIAS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBiometricCertificateAlias(String biometricCertificateAlias) {
    this.biometricCertificateAlias = biometricCertificateAlias;
  }


  public BiometricSignatureRequestDTO biometricCertificatePass(String biometricCertificatePass) {
    
    this.biometricCertificatePass = biometricCertificatePass;
    return this;
  }

   /**
   * Get biometricCertificatePass
   * @return biometricCertificatePass
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_BIOMETRIC_CERTIFICATE_PASS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getBiometricCertificatePass() {
    return biometricCertificatePass;
  }


  @JsonProperty(JSON_PROPERTY_BIOMETRIC_CERTIFICATE_PASS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBiometricCertificatePass(String biometricCertificatePass) {
    this.biometricCertificatePass = biometricCertificatePass;
  }


  public BiometricSignatureRequestDTO fileBase64(String fileBase64) {
    
    this.fileBase64 = fileBase64;
    return this;
  }

   /**
   * Get fileBase64
   * @return fileBase64
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_FILE_BASE64)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFileBase64() {
    return fileBase64;
  }


  @JsonProperty(JSON_PROPERTY_FILE_BASE64)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFileBase64(String fileBase64) {
    this.fileBase64 = fileBase64;
  }


  public BiometricSignatureRequestDTO imageBase64(String imageBase64) {
    
    this.imageBase64 = imageBase64;
    return this;
  }

   /**
   * Get imageBase64
   * @return imageBase64
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_IMAGE_BASE64)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getImageBase64() {
    return imageBase64;
  }


  @JsonProperty(JSON_PROPERTY_IMAGE_BASE64)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setImageBase64(String imageBase64) {
    this.imageBase64 = imageBase64;
  }


  public BiometricSignatureRequestDTO strokes(List<BDSignatureStrokeDTO> strokes) {
    
    this.strokes = strokes;
    return this;
  }

  public BiometricSignatureRequestDTO addStrokesItem(BDSignatureStrokeDTO strokesItem) {
    if (this.strokes == null) {
      this.strokes = new ArrayList<>();
    }
    this.strokes.add(strokesItem);
    return this;
  }

   /**
   * Get strokes
   * @return strokes
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_STROKES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<BDSignatureStrokeDTO> getStrokes() {
    return strokes;
  }


  @JsonProperty(JSON_PROPERTY_STROKES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStrokes(List<BDSignatureStrokeDTO> strokes) {
    this.strokes = strokes;
  }


  public BiometricSignatureRequestDTO device(EvidenceDeviceDTO device) {
    
    this.device = device;
    return this;
  }

   /**
   * Get device
   * @return device
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_DEVICE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public EvidenceDeviceDTO getDevice() {
    return device;
  }


  @JsonProperty(JSON_PROPERTY_DEVICE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDevice(EvidenceDeviceDTO device) {
    this.device = device;
  }


  public BiometricSignatureRequestDTO geolocation(GeolocationDTO geolocation) {
    
    this.geolocation = geolocation;
    return this;
  }

   /**
   * Get geolocation
   * @return geolocation
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_GEOLOCATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public GeolocationDTO getGeolocation() {
    return geolocation;
  }


  @JsonProperty(JSON_PROPERTY_GEOLOCATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setGeolocation(GeolocationDTO geolocation) {
    this.geolocation = geolocation;
  }


  public BiometricSignatureRequestDTO signatureType(SignatureTypeEnum signatureType) {
    
    this.signatureType = signatureType;
    return this;
  }

   /**
   * Get signatureType
   * @return signatureType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SIGNATURE_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public SignatureTypeEnum getSignatureType() {
    return signatureType;
  }


  @JsonProperty(JSON_PROPERTY_SIGNATURE_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSignatureType(SignatureTypeEnum signatureType) {
    this.signatureType = signatureType;
  }


  public BiometricSignatureRequestDTO tsa(ConfigTsaDTO tsa) {
    
    this.tsa = tsa;
    return this;
  }

   /**
   * Get tsa
   * @return tsa
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TSA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ConfigTsaDTO getTsa() {
    return tsa;
  }


  @JsonProperty(JSON_PROPERTY_TSA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTsa(ConfigTsaDTO tsa) {
    this.tsa = tsa;
  }


  public BiometricSignatureRequestDTO positions(List<PositionDTO> positions) {
    
    this.positions = positions;
    return this;
  }

  public BiometricSignatureRequestDTO addPositionsItem(PositionDTO positionsItem) {
    if (this.positions == null) {
      this.positions = new ArrayList<>();
    }
    this.positions.add(positionsItem);
    return this;
  }

   /**
   * Get positions
   * @return positions
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_POSITIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<PositionDTO> getPositions() {
    return positions;
  }


  @JsonProperty(JSON_PROPERTY_POSITIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPositions(List<PositionDTO> positions) {
    this.positions = positions;
  }


  public BiometricSignatureRequestDTO addDigitalSignature(Boolean addDigitalSignature) {
    
    this.addDigitalSignature = addDigitalSignature;
    return this;
  }

   /**
   * Get addDigitalSignature
   * @return addDigitalSignature
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ADD_DIGITAL_SIGNATURE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getAddDigitalSignature() {
    return addDigitalSignature;
  }


  @JsonProperty(JSON_PROPERTY_ADD_DIGITAL_SIGNATURE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAddDigitalSignature(Boolean addDigitalSignature) {
    this.addDigitalSignature = addDigitalSignature;
  }


  public BiometricSignatureRequestDTO digitalSignatureCertificateAlias(String digitalSignatureCertificateAlias) {
    
    this.digitalSignatureCertificateAlias = digitalSignatureCertificateAlias;
    return this;
  }

   /**
   * Get digitalSignatureCertificateAlias
   * @return digitalSignatureCertificateAlias
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_DIGITAL_SIGNATURE_CERTIFICATE_ALIAS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDigitalSignatureCertificateAlias() {
    return digitalSignatureCertificateAlias;
  }


  @JsonProperty(JSON_PROPERTY_DIGITAL_SIGNATURE_CERTIFICATE_ALIAS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDigitalSignatureCertificateAlias(String digitalSignatureCertificateAlias) {
    this.digitalSignatureCertificateAlias = digitalSignatureCertificateAlias;
  }


  public BiometricSignatureRequestDTO digitalSignatureCertificatePass(String digitalSignatureCertificatePass) {
    
    this.digitalSignatureCertificatePass = digitalSignatureCertificatePass;
    return this;
  }

   /**
   * Get digitalSignatureCertificatePass
   * @return digitalSignatureCertificatePass
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_DIGITAL_SIGNATURE_CERTIFICATE_PASS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDigitalSignatureCertificatePass() {
    return digitalSignatureCertificatePass;
  }


  @JsonProperty(JSON_PROPERTY_DIGITAL_SIGNATURE_CERTIFICATE_PASS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDigitalSignatureCertificatePass(String digitalSignatureCertificatePass) {
    this.digitalSignatureCertificatePass = digitalSignatureCertificatePass;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BiometricSignatureRequestDTO biometricSignatureRequestDTO = (BiometricSignatureRequestDTO) o;
    return Objects.equals(this.code, biometricSignatureRequestDTO.code) &&
        Objects.equals(this.reason, biometricSignatureRequestDTO.reason) &&
        Objects.equals(this.cipherCertificateAlias, biometricSignatureRequestDTO.cipherCertificateAlias) &&
        Objects.equals(this.biometricCertificateAlias, biometricSignatureRequestDTO.biometricCertificateAlias) &&
        Objects.equals(this.biometricCertificatePass, biometricSignatureRequestDTO.biometricCertificatePass) &&
        Objects.equals(this.fileBase64, biometricSignatureRequestDTO.fileBase64) &&
        Objects.equals(this.imageBase64, biometricSignatureRequestDTO.imageBase64) &&
        Objects.equals(this.strokes, biometricSignatureRequestDTO.strokes) &&
        Objects.equals(this.device, biometricSignatureRequestDTO.device) &&
        Objects.equals(this.geolocation, biometricSignatureRequestDTO.geolocation) &&
        Objects.equals(this.signatureType, biometricSignatureRequestDTO.signatureType) &&
        Objects.equals(this.tsa, biometricSignatureRequestDTO.tsa) &&
        Objects.equals(this.positions, biometricSignatureRequestDTO.positions) &&
        Objects.equals(this.addDigitalSignature, biometricSignatureRequestDTO.addDigitalSignature) &&
        Objects.equals(this.digitalSignatureCertificateAlias, biometricSignatureRequestDTO.digitalSignatureCertificateAlias) &&
        Objects.equals(this.digitalSignatureCertificatePass, biometricSignatureRequestDTO.digitalSignatureCertificatePass);
  }

  @Override
  public int hashCode() {
    return Objects.hash(code, reason, cipherCertificateAlias, biometricCertificateAlias, biometricCertificatePass, fileBase64, imageBase64, strokes, device, geolocation, signatureType, tsa, positions, addDigitalSignature, digitalSignatureCertificateAlias, digitalSignatureCertificatePass);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BiometricSignatureRequestDTO {\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    reason: ").append(toIndentedString(reason)).append("\n");
    sb.append("    cipherCertificateAlias: ").append(toIndentedString(cipherCertificateAlias)).append("\n");
    sb.append("    biometricCertificateAlias: ").append(toIndentedString(biometricCertificateAlias)).append("\n");
    sb.append("    biometricCertificatePass: ").append(toIndentedString(biometricCertificatePass)).append("\n");
    sb.append("    fileBase64: ").append(toIndentedString(fileBase64)).append("\n");
    sb.append("    imageBase64: ").append(toIndentedString(imageBase64)).append("\n");
    sb.append("    strokes: ").append(toIndentedString(strokes)).append("\n");
    sb.append("    device: ").append(toIndentedString(device)).append("\n");
    sb.append("    geolocation: ").append(toIndentedString(geolocation)).append("\n");
    sb.append("    signatureType: ").append(toIndentedString(signatureType)).append("\n");
    sb.append("    tsa: ").append(toIndentedString(tsa)).append("\n");
    sb.append("    positions: ").append(toIndentedString(positions)).append("\n");
    sb.append("    addDigitalSignature: ").append(toIndentedString(addDigitalSignature)).append("\n");
    sb.append("    digitalSignatureCertificateAlias: ").append(toIndentedString(digitalSignatureCertificateAlias)).append("\n");
    sb.append("    digitalSignatureCertificatePass: ").append(toIndentedString(digitalSignatureCertificatePass)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

