/*
 * Viafirma API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.3.29-r83-596fbc1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * BiometricSignatureResponseDTO
 */
@JsonPropertyOrder({
  BiometricSignatureResponseDTO.JSON_PROPERTY_SIGNED_FILE_BASE64,
  BiometricSignatureResponseDTO.JSON_PROPERTY_SIGNATURE_TEMPLATE,
  BiometricSignatureResponseDTO.JSON_PROPERTY_SIGNATURE_CODE
})
@JsonTypeName("BiometricSignatureResponseDTO")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-03-04T11:20:43.685+01:00[Europe/Paris]")
public class BiometricSignatureResponseDTO {
  public static final String JSON_PROPERTY_SIGNED_FILE_BASE64 = "signedFileBase64";
  private String signedFileBase64;

  public static final String JSON_PROPERTY_SIGNATURE_TEMPLATE = "signatureTemplate";
  private String signatureTemplate;

  public static final String JSON_PROPERTY_SIGNATURE_CODE = "signatureCode";
  private String signatureCode;

  public BiometricSignatureResponseDTO() { 
  }

  public BiometricSignatureResponseDTO signedFileBase64(String signedFileBase64) {
    
    this.signedFileBase64 = signedFileBase64;
    return this;
  }

   /**
   * Get signedFileBase64
   * @return signedFileBase64
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SIGNED_FILE_BASE64)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSignedFileBase64() {
    return signedFileBase64;
  }


  @JsonProperty(JSON_PROPERTY_SIGNED_FILE_BASE64)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSignedFileBase64(String signedFileBase64) {
    this.signedFileBase64 = signedFileBase64;
  }


  public BiometricSignatureResponseDTO signatureTemplate(String signatureTemplate) {
    
    this.signatureTemplate = signatureTemplate;
    return this;
  }

   /**
   * Get signatureTemplate
   * @return signatureTemplate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SIGNATURE_TEMPLATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSignatureTemplate() {
    return signatureTemplate;
  }


  @JsonProperty(JSON_PROPERTY_SIGNATURE_TEMPLATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSignatureTemplate(String signatureTemplate) {
    this.signatureTemplate = signatureTemplate;
  }


  public BiometricSignatureResponseDTO signatureCode(String signatureCode) {
    
    this.signatureCode = signatureCode;
    return this;
  }

   /**
   * Get signatureCode
   * @return signatureCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SIGNATURE_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSignatureCode() {
    return signatureCode;
  }


  @JsonProperty(JSON_PROPERTY_SIGNATURE_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSignatureCode(String signatureCode) {
    this.signatureCode = signatureCode;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BiometricSignatureResponseDTO biometricSignatureResponseDTO = (BiometricSignatureResponseDTO) o;
    return Objects.equals(this.signedFileBase64, biometricSignatureResponseDTO.signedFileBase64) &&
        Objects.equals(this.signatureTemplate, biometricSignatureResponseDTO.signatureTemplate) &&
        Objects.equals(this.signatureCode, biometricSignatureResponseDTO.signatureCode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(signedFileBase64, signatureTemplate, signatureCode);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BiometricSignatureResponseDTO {\n");
    sb.append("    signedFileBase64: ").append(toIndentedString(signedFileBase64)).append("\n");
    sb.append("    signatureTemplate: ").append(toIndentedString(signatureTemplate)).append("\n");
    sb.append("    signatureCode: ").append(toIndentedString(signatureCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

