/*
 * Viafirma API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.3.29-r83-596fbc1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * CertificateRequestDTO
 */
@JsonPropertyOrder({
  CertificateRequestDTO.JSON_PROPERTY_BASE64_PEM,
  CertificateRequestDTO.JSON_PROPERTY_BASE64_SIGNATURE
})
@JsonTypeName("CertificateRequestDTO")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-03-04T11:20:43.685+01:00[Europe/Paris]")
public class CertificateRequestDTO {
  public static final String JSON_PROPERTY_BASE64_PEM = "base64Pem";
  private String base64Pem;

  public static final String JSON_PROPERTY_BASE64_SIGNATURE = "base64Signature";
  private String base64Signature;

  public CertificateRequestDTO() { 
  }

  public CertificateRequestDTO base64Pem(String base64Pem) {
    
    this.base64Pem = base64Pem;
    return this;
  }

   /**
   * Get base64Pem
   * @return base64Pem
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_BASE64_PEM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getBase64Pem() {
    return base64Pem;
  }


  @JsonProperty(JSON_PROPERTY_BASE64_PEM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBase64Pem(String base64Pem) {
    this.base64Pem = base64Pem;
  }


  public CertificateRequestDTO base64Signature(String base64Signature) {
    
    this.base64Signature = base64Signature;
    return this;
  }

   /**
   * Get base64Signature
   * @return base64Signature
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_BASE64_SIGNATURE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getBase64Signature() {
    return base64Signature;
  }


  @JsonProperty(JSON_PROPERTY_BASE64_SIGNATURE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBase64Signature(String base64Signature) {
    this.base64Signature = base64Signature;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CertificateRequestDTO certificateRequestDTO = (CertificateRequestDTO) o;
    return Objects.equals(this.base64Pem, certificateRequestDTO.base64Pem) &&
        Objects.equals(this.base64Signature, certificateRequestDTO.base64Signature);
  }

  @Override
  public int hashCode() {
    return Objects.hash(base64Pem, base64Signature);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CertificateRequestDTO {\n");
    sb.append("    base64Pem: ").append(toIndentedString(base64Pem)).append("\n");
    sb.append("    base64Signature: ").append(toIndentedString(base64Signature)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

