/*
 * Viafirma API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.3.29-r83-596fbc1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * CertificateDTOCertificatePublicKey
 */
@JsonPropertyOrder({
  CertificateDTOCertificatePublicKey.JSON_PROPERTY_ENCODED,
  CertificateDTOCertificatePublicKey.JSON_PROPERTY_FORMAT,
  CertificateDTOCertificatePublicKey.JSON_PROPERTY_ALGORITHM
})
@JsonTypeName("CertificateDTO_certificate_publicKey")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-03-04T11:20:43.685+01:00[Europe/Paris]")
public class CertificateDTOCertificatePublicKey {
  public static final String JSON_PROPERTY_ENCODED = "encoded";
  private byte[] encoded;

  public static final String JSON_PROPERTY_FORMAT = "format";
  private String format;

  public static final String JSON_PROPERTY_ALGORITHM = "algorithm";
  private String algorithm;

  public CertificateDTOCertificatePublicKey() { 
  }

  public CertificateDTOCertificatePublicKey encoded(byte[] encoded) {
    
    this.encoded = encoded;
    return this;
  }

   /**
   * Get encoded
   * @return encoded
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ENCODED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public byte[] getEncoded() {
    return encoded;
  }


  @JsonProperty(JSON_PROPERTY_ENCODED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEncoded(byte[] encoded) {
    this.encoded = encoded;
  }


  public CertificateDTOCertificatePublicKey format(String format) {
    
    this.format = format;
    return this;
  }

   /**
   * Get format
   * @return format
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_FORMAT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFormat() {
    return format;
  }


  @JsonProperty(JSON_PROPERTY_FORMAT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFormat(String format) {
    this.format = format;
  }


  public CertificateDTOCertificatePublicKey algorithm(String algorithm) {
    
    this.algorithm = algorithm;
    return this;
  }

   /**
   * Get algorithm
   * @return algorithm
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ALGORITHM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAlgorithm() {
    return algorithm;
  }


  @JsonProperty(JSON_PROPERTY_ALGORITHM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAlgorithm(String algorithm) {
    this.algorithm = algorithm;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CertificateDTOCertificatePublicKey certificateDTOCertificatePublicKey = (CertificateDTOCertificatePublicKey) o;
    return Arrays.equals(this.encoded, certificateDTOCertificatePublicKey.encoded) &&
        Objects.equals(this.format, certificateDTOCertificatePublicKey.format) &&
        Objects.equals(this.algorithm, certificateDTOCertificatePublicKey.algorithm);
  }

  @Override
  public int hashCode() {
    return Objects.hash(Arrays.hashCode(encoded), format, algorithm);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CertificateDTOCertificatePublicKey {\n");
    sb.append("    encoded: ").append(toIndentedString(encoded)).append("\n");
    sb.append("    format: ").append(toIndentedString(format)).append("\n");
    sb.append("    algorithm: ").append(toIndentedString(algorithm)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

