/*
 * Viafirma API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.3.29-r83-596fbc1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * CertificateDTOPrivateKey
 */
@JsonPropertyOrder({
  CertificateDTOPrivateKey.JSON_PROPERTY_ENCODED,
  CertificateDTOPrivateKey.JSON_PROPERTY_FORMAT,
  CertificateDTOPrivateKey.JSON_PROPERTY_ALGORITHM,
  CertificateDTOPrivateKey.JSON_PROPERTY_DESTROYED
})
@JsonTypeName("CertificateDTO_privateKey")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-03-04T11:20:43.685+01:00[Europe/Paris]")
public class CertificateDTOPrivateKey {
  public static final String JSON_PROPERTY_ENCODED = "encoded";
  private byte[] encoded;

  public static final String JSON_PROPERTY_FORMAT = "format";
  private String format;

  public static final String JSON_PROPERTY_ALGORITHM = "algorithm";
  private String algorithm;

  public static final String JSON_PROPERTY_DESTROYED = "destroyed";
  private Boolean destroyed;

  public CertificateDTOPrivateKey() { 
  }

  public CertificateDTOPrivateKey encoded(byte[] encoded) {
    
    this.encoded = encoded;
    return this;
  }

   /**
   * Get encoded
   * @return encoded
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ENCODED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public byte[] getEncoded() {
    return encoded;
  }


  @JsonProperty(JSON_PROPERTY_ENCODED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEncoded(byte[] encoded) {
    this.encoded = encoded;
  }


  public CertificateDTOPrivateKey format(String format) {
    
    this.format = format;
    return this;
  }

   /**
   * Get format
   * @return format
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_FORMAT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFormat() {
    return format;
  }


  @JsonProperty(JSON_PROPERTY_FORMAT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFormat(String format) {
    this.format = format;
  }


  public CertificateDTOPrivateKey algorithm(String algorithm) {
    
    this.algorithm = algorithm;
    return this;
  }

   /**
   * Get algorithm
   * @return algorithm
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ALGORITHM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAlgorithm() {
    return algorithm;
  }


  @JsonProperty(JSON_PROPERTY_ALGORITHM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAlgorithm(String algorithm) {
    this.algorithm = algorithm;
  }


  public CertificateDTOPrivateKey destroyed(Boolean destroyed) {
    
    this.destroyed = destroyed;
    return this;
  }

   /**
   * Get destroyed
   * @return destroyed
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_DESTROYED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getDestroyed() {
    return destroyed;
  }


  @JsonProperty(JSON_PROPERTY_DESTROYED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDestroyed(Boolean destroyed) {
    this.destroyed = destroyed;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CertificateDTOPrivateKey certificateDTOPrivateKey = (CertificateDTOPrivateKey) o;
    return Arrays.equals(this.encoded, certificateDTOPrivateKey.encoded) &&
        Objects.equals(this.format, certificateDTOPrivateKey.format) &&
        Objects.equals(this.algorithm, certificateDTOPrivateKey.algorithm) &&
        Objects.equals(this.destroyed, certificateDTOPrivateKey.destroyed);
  }

  @Override
  public int hashCode() {
    return Objects.hash(Arrays.hashCode(encoded), format, algorithm, destroyed);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CertificateDTOPrivateKey {\n");
    sb.append("    encoded: ").append(toIndentedString(encoded)).append("\n");
    sb.append("    format: ").append(toIndentedString(format)).append("\n");
    sb.append("    algorithm: ").append(toIndentedString(algorithm)).append("\n");
    sb.append("    destroyed: ").append(toIndentedString(destroyed)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

