/*
 * Viafirma API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.3.29-r83-596fbc1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * CertificateResponseDTO
 */
@JsonPropertyOrder({
  CertificateResponseDTO.JSON_PROPERTY_NUMBER_USER_ID,
  CertificateResponseDTO.JSON_PROPERTY_NAME,
  CertificateResponseDTO.JSON_PROPERTY_SURNAME1,
  CertificateResponseDTO.JSON_PROPERTY_SURNAME2,
  CertificateResponseDTO.JSON_PROPERTY_EMAIL,
  CertificateResponseDTO.JSON_PROPERTY_CA,
  CertificateResponseDTO.JSON_PROPERTY_SHORT_CA,
  CertificateResponseDTO.JSON_PROPERTY_JOB_TITLE,
  CertificateResponseDTO.JSON_PROPERTY_TYPE,
  CertificateResponseDTO.JSON_PROPERTY_CN,
  CertificateResponseDTO.JSON_PROPERTY_ORGANIZATION,
  CertificateResponseDTO.JSON_PROPERTY_CERTIFICATE_PROPERTIES,
  CertificateResponseDTO.JSON_PROPERTY_IS_VALIDATED,
  CertificateResponseDTO.JSON_PROPERTY_IS_EXPIRED,
  CertificateResponseDTO.JSON_PROPERTY_IS_REVOKED
})
@JsonTypeName("CertificateResponseDTO")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-03-04T11:20:43.685+01:00[Europe/Paris]")
public class CertificateResponseDTO {
  public static final String JSON_PROPERTY_NUMBER_USER_ID = "numberUserId";
  private String numberUserId;

  public static final String JSON_PROPERTY_NAME = "name";
  private String name;

  public static final String JSON_PROPERTY_SURNAME1 = "surname1";
  private String surname1;

  public static final String JSON_PROPERTY_SURNAME2 = "surname2";
  private String surname2;

  public static final String JSON_PROPERTY_EMAIL = "email";
  private String email;

  public static final String JSON_PROPERTY_CA = "ca";
  private String ca;

  public static final String JSON_PROPERTY_SHORT_CA = "shortCa";
  private String shortCa;

  public static final String JSON_PROPERTY_JOB_TITLE = "jobTitle";
  private String jobTitle;

  public static final String JSON_PROPERTY_TYPE = "type";
  private String type;

  public static final String JSON_PROPERTY_CN = "cn";
  private String cn;

  public static final String JSON_PROPERTY_ORGANIZATION = "organization";
  private String organization;

  public static final String JSON_PROPERTY_CERTIFICATE_PROPERTIES = "certificateProperties";
  private Map<String, String> certificateProperties = null;

  public static final String JSON_PROPERTY_IS_VALIDATED = "isValidated";
  private Boolean isValidated;

  public static final String JSON_PROPERTY_IS_EXPIRED = "isExpired";
  private Boolean isExpired;

  public static final String JSON_PROPERTY_IS_REVOKED = "isRevoked";
  private Boolean isRevoked;

  public CertificateResponseDTO() { 
  }

  public CertificateResponseDTO numberUserId(String numberUserId) {
    
    this.numberUserId = numberUserId;
    return this;
  }

   /**
   * Get numberUserId
   * @return numberUserId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_NUMBER_USER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getNumberUserId() {
    return numberUserId;
  }


  @JsonProperty(JSON_PROPERTY_NUMBER_USER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNumberUserId(String numberUserId) {
    this.numberUserId = numberUserId;
  }


  public CertificateResponseDTO name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(String name) {
    this.name = name;
  }


  public CertificateResponseDTO surname1(String surname1) {
    
    this.surname1 = surname1;
    return this;
  }

   /**
   * Get surname1
   * @return surname1
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SURNAME1)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSurname1() {
    return surname1;
  }


  @JsonProperty(JSON_PROPERTY_SURNAME1)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSurname1(String surname1) {
    this.surname1 = surname1;
  }


  public CertificateResponseDTO surname2(String surname2) {
    
    this.surname2 = surname2;
    return this;
  }

   /**
   * Get surname2
   * @return surname2
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SURNAME2)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSurname2() {
    return surname2;
  }


  @JsonProperty(JSON_PROPERTY_SURNAME2)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSurname2(String surname2) {
    this.surname2 = surname2;
  }


  public CertificateResponseDTO email(String email) {
    
    this.email = email;
    return this;
  }

   /**
   * Get email
   * @return email
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_EMAIL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getEmail() {
    return email;
  }


  @JsonProperty(JSON_PROPERTY_EMAIL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEmail(String email) {
    this.email = email;
  }


  public CertificateResponseDTO ca(String ca) {
    
    this.ca = ca;
    return this;
  }

   /**
   * Get ca
   * @return ca
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCa() {
    return ca;
  }


  @JsonProperty(JSON_PROPERTY_CA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCa(String ca) {
    this.ca = ca;
  }


  public CertificateResponseDTO shortCa(String shortCa) {
    
    this.shortCa = shortCa;
    return this;
  }

   /**
   * Get shortCa
   * @return shortCa
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SHORT_CA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getShortCa() {
    return shortCa;
  }


  @JsonProperty(JSON_PROPERTY_SHORT_CA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setShortCa(String shortCa) {
    this.shortCa = shortCa;
  }


  public CertificateResponseDTO jobTitle(String jobTitle) {
    
    this.jobTitle = jobTitle;
    return this;
  }

   /**
   * Get jobTitle
   * @return jobTitle
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_JOB_TITLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getJobTitle() {
    return jobTitle;
  }


  @JsonProperty(JSON_PROPERTY_JOB_TITLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setJobTitle(String jobTitle) {
    this.jobTitle = jobTitle;
  }


  public CertificateResponseDTO type(String type) {
    
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getType() {
    return type;
  }


  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setType(String type) {
    this.type = type;
  }


  public CertificateResponseDTO cn(String cn) {
    
    this.cn = cn;
    return this;
  }

   /**
   * Get cn
   * @return cn
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCn() {
    return cn;
  }


  @JsonProperty(JSON_PROPERTY_CN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCn(String cn) {
    this.cn = cn;
  }


  public CertificateResponseDTO organization(String organization) {
    
    this.organization = organization;
    return this;
  }

   /**
   * Get organization
   * @return organization
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ORGANIZATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getOrganization() {
    return organization;
  }


  @JsonProperty(JSON_PROPERTY_ORGANIZATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOrganization(String organization) {
    this.organization = organization;
  }


  public CertificateResponseDTO certificateProperties(Map<String, String> certificateProperties) {
    
    this.certificateProperties = certificateProperties;
    return this;
  }

  public CertificateResponseDTO putCertificatePropertiesItem(String key, String certificatePropertiesItem) {
    if (this.certificateProperties == null) {
      this.certificateProperties = new HashMap<>();
    }
    this.certificateProperties.put(key, certificatePropertiesItem);
    return this;
  }

   /**
   * Get certificateProperties
   * @return certificateProperties
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CERTIFICATE_PROPERTIES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Map<String, String> getCertificateProperties() {
    return certificateProperties;
  }


  @JsonProperty(JSON_PROPERTY_CERTIFICATE_PROPERTIES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCertificateProperties(Map<String, String> certificateProperties) {
    this.certificateProperties = certificateProperties;
  }


  public CertificateResponseDTO isValidated(Boolean isValidated) {
    
    this.isValidated = isValidated;
    return this;
  }

   /**
   * Get isValidated
   * @return isValidated
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_IS_VALIDATED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getIsValidated() {
    return isValidated;
  }


  @JsonProperty(JSON_PROPERTY_IS_VALIDATED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIsValidated(Boolean isValidated) {
    this.isValidated = isValidated;
  }


  public CertificateResponseDTO isExpired(Boolean isExpired) {
    
    this.isExpired = isExpired;
    return this;
  }

   /**
   * Get isExpired
   * @return isExpired
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_IS_EXPIRED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getIsExpired() {
    return isExpired;
  }


  @JsonProperty(JSON_PROPERTY_IS_EXPIRED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIsExpired(Boolean isExpired) {
    this.isExpired = isExpired;
  }


  public CertificateResponseDTO isRevoked(Boolean isRevoked) {
    
    this.isRevoked = isRevoked;
    return this;
  }

   /**
   * Get isRevoked
   * @return isRevoked
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_IS_REVOKED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getIsRevoked() {
    return isRevoked;
  }


  @JsonProperty(JSON_PROPERTY_IS_REVOKED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIsRevoked(Boolean isRevoked) {
    this.isRevoked = isRevoked;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CertificateResponseDTO certificateResponseDTO = (CertificateResponseDTO) o;
    return Objects.equals(this.numberUserId, certificateResponseDTO.numberUserId) &&
        Objects.equals(this.name, certificateResponseDTO.name) &&
        Objects.equals(this.surname1, certificateResponseDTO.surname1) &&
        Objects.equals(this.surname2, certificateResponseDTO.surname2) &&
        Objects.equals(this.email, certificateResponseDTO.email) &&
        Objects.equals(this.ca, certificateResponseDTO.ca) &&
        Objects.equals(this.shortCa, certificateResponseDTO.shortCa) &&
        Objects.equals(this.jobTitle, certificateResponseDTO.jobTitle) &&
        Objects.equals(this.type, certificateResponseDTO.type) &&
        Objects.equals(this.cn, certificateResponseDTO.cn) &&
        Objects.equals(this.organization, certificateResponseDTO.organization) &&
        Objects.equals(this.certificateProperties, certificateResponseDTO.certificateProperties) &&
        Objects.equals(this.isValidated, certificateResponseDTO.isValidated) &&
        Objects.equals(this.isExpired, certificateResponseDTO.isExpired) &&
        Objects.equals(this.isRevoked, certificateResponseDTO.isRevoked);
  }

  @Override
  public int hashCode() {
    return Objects.hash(numberUserId, name, surname1, surname2, email, ca, shortCa, jobTitle, type, cn, organization, certificateProperties, isValidated, isExpired, isRevoked);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CertificateResponseDTO {\n");
    sb.append("    numberUserId: ").append(toIndentedString(numberUserId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    surname1: ").append(toIndentedString(surname1)).append("\n");
    sb.append("    surname2: ").append(toIndentedString(surname2)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    ca: ").append(toIndentedString(ca)).append("\n");
    sb.append("    shortCa: ").append(toIndentedString(shortCa)).append("\n");
    sb.append("    jobTitle: ").append(toIndentedString(jobTitle)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    cn: ").append(toIndentedString(cn)).append("\n");
    sb.append("    organization: ").append(toIndentedString(organization)).append("\n");
    sb.append("    certificateProperties: ").append(toIndentedString(certificateProperties)).append("\n");
    sb.append("    isValidated: ").append(toIndentedString(isValidated)).append("\n");
    sb.append("    isExpired: ").append(toIndentedString(isExpired)).append("\n");
    sb.append("    isRevoked: ").append(toIndentedString(isRevoked)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

