/*
 * Viafirma API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.3.29-r83-596fbc1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;
import org.openapitools.client.model.CertificateDTOCertificateIssuerDN;
import org.openapitools.client.model.CertificateDTOCertificateIssuerX500Principal;
import org.openapitools.client.model.CertificateDTOCertificatePublicKey;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * CertificateDTOCertificate
 */
@JsonPropertyOrder({
  CertificateDTOCertificate.JSON_PROPERTY_SIGNATURE,
  CertificateDTOCertificate.JSON_PROPERTY_BASIC_CONSTRAINTS,
  CertificateDTOCertificate.JSON_PROPERTY_ISSUER_X500_PRINCIPAL,
  CertificateDTOCertificate.JSON_PROPERTY_SUBJECT_X500_PRINCIPAL,
  CertificateDTOCertificate.JSON_PROPERTY_VERSION,
  CertificateDTOCertificate.JSON_PROPERTY_EXTENDED_KEY_USAGE,
  CertificateDTOCertificate.JSON_PROPERTY_SUBJECT_ALTERNATIVE_NAMES,
  CertificateDTOCertificate.JSON_PROPERTY_ISSUER_ALTERNATIVE_NAMES,
  CertificateDTOCertificate.JSON_PROPERTY_SIG_ALG_NAME,
  CertificateDTOCertificate.JSON_PROPERTY_SIG_ALG_PARAMS,
  CertificateDTOCertificate.JSON_PROPERTY_TBSCERTIFICATE,
  CertificateDTOCertificate.JSON_PROPERTY_SERIAL_NUMBER,
  CertificateDTOCertificate.JSON_PROPERTY_ISSUER_D_N,
  CertificateDTOCertificate.JSON_PROPERTY_SUBJECT_D_N,
  CertificateDTOCertificate.JSON_PROPERTY_NOT_BEFORE,
  CertificateDTOCertificate.JSON_PROPERTY_NOT_AFTER,
  CertificateDTOCertificate.JSON_PROPERTY_SIG_ALG_O_I_D,
  CertificateDTOCertificate.JSON_PROPERTY_ISSUER_UNIQUE_I_D,
  CertificateDTOCertificate.JSON_PROPERTY_SUBJECT_UNIQUE_I_D,
  CertificateDTOCertificate.JSON_PROPERTY_KEY_USAGE,
  CertificateDTOCertificate.JSON_PROPERTY_CRITICAL_EXTENSION_O_I_DS,
  CertificateDTOCertificate.JSON_PROPERTY_NON_CRITICAL_EXTENSION_O_I_DS,
  CertificateDTOCertificate.JSON_PROPERTY_TYPE,
  CertificateDTOCertificate.JSON_PROPERTY_ENCODED,
  CertificateDTOCertificate.JSON_PROPERTY_PUBLIC_KEY
})
@JsonTypeName("CertificateDTO_certificate")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-03-04T11:20:43.685+01:00[Europe/Paris]")
public class CertificateDTOCertificate {
  public static final String JSON_PROPERTY_SIGNATURE = "signature";
  private byte[] signature;

  public static final String JSON_PROPERTY_BASIC_CONSTRAINTS = "basicConstraints";
  private Integer basicConstraints;

  public static final String JSON_PROPERTY_ISSUER_X500_PRINCIPAL = "issuerX500Principal";
  private CertificateDTOCertificateIssuerX500Principal issuerX500Principal;

  public static final String JSON_PROPERTY_SUBJECT_X500_PRINCIPAL = "subjectX500Principal";
  private CertificateDTOCertificateIssuerX500Principal subjectX500Principal;

  public static final String JSON_PROPERTY_VERSION = "version";
  private Integer version;

  public static final String JSON_PROPERTY_EXTENDED_KEY_USAGE = "extendedKeyUsage";
  private List<String> extendedKeyUsage = null;

  public static final String JSON_PROPERTY_SUBJECT_ALTERNATIVE_NAMES = "subjectAlternativeNames";
  private List<List<Object>> subjectAlternativeNames = null;

  public static final String JSON_PROPERTY_ISSUER_ALTERNATIVE_NAMES = "issuerAlternativeNames";
  private List<List<Object>> issuerAlternativeNames = null;

  public static final String JSON_PROPERTY_SIG_ALG_NAME = "sigAlgName";
  private String sigAlgName;

  public static final String JSON_PROPERTY_SIG_ALG_PARAMS = "sigAlgParams";
  private byte[] sigAlgParams;

  public static final String JSON_PROPERTY_TBSCERTIFICATE = "tbscertificate";
  private byte[] tbscertificate;

  public static final String JSON_PROPERTY_SERIAL_NUMBER = "serialNumber";
  private Integer serialNumber;

  public static final String JSON_PROPERTY_ISSUER_D_N = "issuerDN";
  private CertificateDTOCertificateIssuerDN issuerDN;

  public static final String JSON_PROPERTY_SUBJECT_D_N = "subjectDN";
  private CertificateDTOCertificateIssuerDN subjectDN;

  public static final String JSON_PROPERTY_NOT_BEFORE = "notBefore";
  private OffsetDateTime notBefore;

  public static final String JSON_PROPERTY_NOT_AFTER = "notAfter";
  private OffsetDateTime notAfter;

  public static final String JSON_PROPERTY_SIG_ALG_O_I_D = "sigAlgOID";
  private String sigAlgOID;

  public static final String JSON_PROPERTY_ISSUER_UNIQUE_I_D = "issuerUniqueID";
  private List<Boolean> issuerUniqueID = null;

  public static final String JSON_PROPERTY_SUBJECT_UNIQUE_I_D = "subjectUniqueID";
  private List<Boolean> subjectUniqueID = null;

  public static final String JSON_PROPERTY_KEY_USAGE = "keyUsage";
  private List<Boolean> keyUsage = null;

  public static final String JSON_PROPERTY_CRITICAL_EXTENSION_O_I_DS = "criticalExtensionOIDs";
  private Set<String> criticalExtensionOIDs = null;

  public static final String JSON_PROPERTY_NON_CRITICAL_EXTENSION_O_I_DS = "nonCriticalExtensionOIDs";
  private Set<String> nonCriticalExtensionOIDs = null;

  public static final String JSON_PROPERTY_TYPE = "type";
  private String type;

  public static final String JSON_PROPERTY_ENCODED = "encoded";
  private byte[] encoded;

  public static final String JSON_PROPERTY_PUBLIC_KEY = "publicKey";
  private CertificateDTOCertificatePublicKey publicKey;

  public CertificateDTOCertificate() { 
  }

  public CertificateDTOCertificate signature(byte[] signature) {
    
    this.signature = signature;
    return this;
  }

   /**
   * Get signature
   * @return signature
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SIGNATURE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public byte[] getSignature() {
    return signature;
  }


  @JsonProperty(JSON_PROPERTY_SIGNATURE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSignature(byte[] signature) {
    this.signature = signature;
  }


  public CertificateDTOCertificate basicConstraints(Integer basicConstraints) {
    
    this.basicConstraints = basicConstraints;
    return this;
  }

   /**
   * Get basicConstraints
   * @return basicConstraints
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_BASIC_CONSTRAINTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getBasicConstraints() {
    return basicConstraints;
  }


  @JsonProperty(JSON_PROPERTY_BASIC_CONSTRAINTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBasicConstraints(Integer basicConstraints) {
    this.basicConstraints = basicConstraints;
  }


  public CertificateDTOCertificate issuerX500Principal(CertificateDTOCertificateIssuerX500Principal issuerX500Principal) {
    
    this.issuerX500Principal = issuerX500Principal;
    return this;
  }

   /**
   * Get issuerX500Principal
   * @return issuerX500Principal
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ISSUER_X500_PRINCIPAL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public CertificateDTOCertificateIssuerX500Principal getIssuerX500Principal() {
    return issuerX500Principal;
  }


  @JsonProperty(JSON_PROPERTY_ISSUER_X500_PRINCIPAL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIssuerX500Principal(CertificateDTOCertificateIssuerX500Principal issuerX500Principal) {
    this.issuerX500Principal = issuerX500Principal;
  }


  public CertificateDTOCertificate subjectX500Principal(CertificateDTOCertificateIssuerX500Principal subjectX500Principal) {
    
    this.subjectX500Principal = subjectX500Principal;
    return this;
  }

   /**
   * Get subjectX500Principal
   * @return subjectX500Principal
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SUBJECT_X500_PRINCIPAL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public CertificateDTOCertificateIssuerX500Principal getSubjectX500Principal() {
    return subjectX500Principal;
  }


  @JsonProperty(JSON_PROPERTY_SUBJECT_X500_PRINCIPAL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSubjectX500Principal(CertificateDTOCertificateIssuerX500Principal subjectX500Principal) {
    this.subjectX500Principal = subjectX500Principal;
  }


  public CertificateDTOCertificate version(Integer version) {
    
    this.version = version;
    return this;
  }

   /**
   * Get version
   * @return version
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_VERSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getVersion() {
    return version;
  }


  @JsonProperty(JSON_PROPERTY_VERSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVersion(Integer version) {
    this.version = version;
  }


  public CertificateDTOCertificate extendedKeyUsage(List<String> extendedKeyUsage) {
    
    this.extendedKeyUsage = extendedKeyUsage;
    return this;
  }

  public CertificateDTOCertificate addExtendedKeyUsageItem(String extendedKeyUsageItem) {
    if (this.extendedKeyUsage == null) {
      this.extendedKeyUsage = new ArrayList<>();
    }
    this.extendedKeyUsage.add(extendedKeyUsageItem);
    return this;
  }

   /**
   * Get extendedKeyUsage
   * @return extendedKeyUsage
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_EXTENDED_KEY_USAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getExtendedKeyUsage() {
    return extendedKeyUsage;
  }


  @JsonProperty(JSON_PROPERTY_EXTENDED_KEY_USAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExtendedKeyUsage(List<String> extendedKeyUsage) {
    this.extendedKeyUsage = extendedKeyUsage;
  }


  public CertificateDTOCertificate subjectAlternativeNames(List<List<Object>> subjectAlternativeNames) {
    
    this.subjectAlternativeNames = subjectAlternativeNames;
    return this;
  }

  public CertificateDTOCertificate addSubjectAlternativeNamesItem(List<Object> subjectAlternativeNamesItem) {
    if (this.subjectAlternativeNames == null) {
      this.subjectAlternativeNames = new ArrayList<>();
    }
    this.subjectAlternativeNames.add(subjectAlternativeNamesItem);
    return this;
  }

   /**
   * Get subjectAlternativeNames
   * @return subjectAlternativeNames
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SUBJECT_ALTERNATIVE_NAMES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<List<Object>> getSubjectAlternativeNames() {
    return subjectAlternativeNames;
  }


  @JsonProperty(JSON_PROPERTY_SUBJECT_ALTERNATIVE_NAMES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSubjectAlternativeNames(List<List<Object>> subjectAlternativeNames) {
    this.subjectAlternativeNames = subjectAlternativeNames;
  }


  public CertificateDTOCertificate issuerAlternativeNames(List<List<Object>> issuerAlternativeNames) {
    
    this.issuerAlternativeNames = issuerAlternativeNames;
    return this;
  }

  public CertificateDTOCertificate addIssuerAlternativeNamesItem(List<Object> issuerAlternativeNamesItem) {
    if (this.issuerAlternativeNames == null) {
      this.issuerAlternativeNames = new ArrayList<>();
    }
    this.issuerAlternativeNames.add(issuerAlternativeNamesItem);
    return this;
  }

   /**
   * Get issuerAlternativeNames
   * @return issuerAlternativeNames
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ISSUER_ALTERNATIVE_NAMES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<List<Object>> getIssuerAlternativeNames() {
    return issuerAlternativeNames;
  }


  @JsonProperty(JSON_PROPERTY_ISSUER_ALTERNATIVE_NAMES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIssuerAlternativeNames(List<List<Object>> issuerAlternativeNames) {
    this.issuerAlternativeNames = issuerAlternativeNames;
  }


  public CertificateDTOCertificate sigAlgName(String sigAlgName) {
    
    this.sigAlgName = sigAlgName;
    return this;
  }

   /**
   * Get sigAlgName
   * @return sigAlgName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SIG_ALG_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSigAlgName() {
    return sigAlgName;
  }


  @JsonProperty(JSON_PROPERTY_SIG_ALG_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSigAlgName(String sigAlgName) {
    this.sigAlgName = sigAlgName;
  }


  public CertificateDTOCertificate sigAlgParams(byte[] sigAlgParams) {
    
    this.sigAlgParams = sigAlgParams;
    return this;
  }

   /**
   * Get sigAlgParams
   * @return sigAlgParams
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SIG_ALG_PARAMS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public byte[] getSigAlgParams() {
    return sigAlgParams;
  }


  @JsonProperty(JSON_PROPERTY_SIG_ALG_PARAMS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSigAlgParams(byte[] sigAlgParams) {
    this.sigAlgParams = sigAlgParams;
  }


  public CertificateDTOCertificate tbscertificate(byte[] tbscertificate) {
    
    this.tbscertificate = tbscertificate;
    return this;
  }

   /**
   * Get tbscertificate
   * @return tbscertificate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TBSCERTIFICATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public byte[] getTbscertificate() {
    return tbscertificate;
  }


  @JsonProperty(JSON_PROPERTY_TBSCERTIFICATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTbscertificate(byte[] tbscertificate) {
    this.tbscertificate = tbscertificate;
  }


  public CertificateDTOCertificate serialNumber(Integer serialNumber) {
    
    this.serialNumber = serialNumber;
    return this;
  }

   /**
   * Get serialNumber
   * @return serialNumber
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SERIAL_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getSerialNumber() {
    return serialNumber;
  }


  @JsonProperty(JSON_PROPERTY_SERIAL_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSerialNumber(Integer serialNumber) {
    this.serialNumber = serialNumber;
  }


  public CertificateDTOCertificate issuerDN(CertificateDTOCertificateIssuerDN issuerDN) {
    
    this.issuerDN = issuerDN;
    return this;
  }

   /**
   * Get issuerDN
   * @return issuerDN
   * @deprecated
  **/
  @Deprecated
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ISSUER_D_N)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public CertificateDTOCertificateIssuerDN getIssuerDN() {
    return issuerDN;
  }


  @JsonProperty(JSON_PROPERTY_ISSUER_D_N)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIssuerDN(CertificateDTOCertificateIssuerDN issuerDN) {
    this.issuerDN = issuerDN;
  }


  public CertificateDTOCertificate subjectDN(CertificateDTOCertificateIssuerDN subjectDN) {
    
    this.subjectDN = subjectDN;
    return this;
  }

   /**
   * Get subjectDN
   * @return subjectDN
   * @deprecated
  **/
  @Deprecated
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SUBJECT_D_N)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public CertificateDTOCertificateIssuerDN getSubjectDN() {
    return subjectDN;
  }


  @JsonProperty(JSON_PROPERTY_SUBJECT_D_N)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSubjectDN(CertificateDTOCertificateIssuerDN subjectDN) {
    this.subjectDN = subjectDN;
  }


  public CertificateDTOCertificate notBefore(OffsetDateTime notBefore) {
    
    this.notBefore = notBefore;
    return this;
  }

   /**
   * Get notBefore
   * @return notBefore
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_NOT_BEFORE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getNotBefore() {
    return notBefore;
  }


  @JsonProperty(JSON_PROPERTY_NOT_BEFORE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNotBefore(OffsetDateTime notBefore) {
    this.notBefore = notBefore;
  }


  public CertificateDTOCertificate notAfter(OffsetDateTime notAfter) {
    
    this.notAfter = notAfter;
    return this;
  }

   /**
   * Get notAfter
   * @return notAfter
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_NOT_AFTER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getNotAfter() {
    return notAfter;
  }


  @JsonProperty(JSON_PROPERTY_NOT_AFTER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNotAfter(OffsetDateTime notAfter) {
    this.notAfter = notAfter;
  }


  public CertificateDTOCertificate sigAlgOID(String sigAlgOID) {
    
    this.sigAlgOID = sigAlgOID;
    return this;
  }

   /**
   * Get sigAlgOID
   * @return sigAlgOID
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SIG_ALG_O_I_D)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSigAlgOID() {
    return sigAlgOID;
  }


  @JsonProperty(JSON_PROPERTY_SIG_ALG_O_I_D)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSigAlgOID(String sigAlgOID) {
    this.sigAlgOID = sigAlgOID;
  }


  public CertificateDTOCertificate issuerUniqueID(List<Boolean> issuerUniqueID) {
    
    this.issuerUniqueID = issuerUniqueID;
    return this;
  }

  public CertificateDTOCertificate addIssuerUniqueIDItem(Boolean issuerUniqueIDItem) {
    if (this.issuerUniqueID == null) {
      this.issuerUniqueID = new ArrayList<>();
    }
    this.issuerUniqueID.add(issuerUniqueIDItem);
    return this;
  }

   /**
   * Get issuerUniqueID
   * @return issuerUniqueID
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ISSUER_UNIQUE_I_D)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Boolean> getIssuerUniqueID() {
    return issuerUniqueID;
  }


  @JsonProperty(JSON_PROPERTY_ISSUER_UNIQUE_I_D)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIssuerUniqueID(List<Boolean> issuerUniqueID) {
    this.issuerUniqueID = issuerUniqueID;
  }


  public CertificateDTOCertificate subjectUniqueID(List<Boolean> subjectUniqueID) {
    
    this.subjectUniqueID = subjectUniqueID;
    return this;
  }

  public CertificateDTOCertificate addSubjectUniqueIDItem(Boolean subjectUniqueIDItem) {
    if (this.subjectUniqueID == null) {
      this.subjectUniqueID = new ArrayList<>();
    }
    this.subjectUniqueID.add(subjectUniqueIDItem);
    return this;
  }

   /**
   * Get subjectUniqueID
   * @return subjectUniqueID
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SUBJECT_UNIQUE_I_D)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Boolean> getSubjectUniqueID() {
    return subjectUniqueID;
  }


  @JsonProperty(JSON_PROPERTY_SUBJECT_UNIQUE_I_D)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSubjectUniqueID(List<Boolean> subjectUniqueID) {
    this.subjectUniqueID = subjectUniqueID;
  }


  public CertificateDTOCertificate keyUsage(List<Boolean> keyUsage) {
    
    this.keyUsage = keyUsage;
    return this;
  }

  public CertificateDTOCertificate addKeyUsageItem(Boolean keyUsageItem) {
    if (this.keyUsage == null) {
      this.keyUsage = new ArrayList<>();
    }
    this.keyUsage.add(keyUsageItem);
    return this;
  }

   /**
   * Get keyUsage
   * @return keyUsage
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_KEY_USAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Boolean> getKeyUsage() {
    return keyUsage;
  }


  @JsonProperty(JSON_PROPERTY_KEY_USAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setKeyUsage(List<Boolean> keyUsage) {
    this.keyUsage = keyUsage;
  }


  public CertificateDTOCertificate criticalExtensionOIDs(Set<String> criticalExtensionOIDs) {
    
    this.criticalExtensionOIDs = criticalExtensionOIDs;
    return this;
  }

  public CertificateDTOCertificate addCriticalExtensionOIDsItem(String criticalExtensionOIDsItem) {
    if (this.criticalExtensionOIDs == null) {
      this.criticalExtensionOIDs = new LinkedHashSet<>();
    }
    this.criticalExtensionOIDs.add(criticalExtensionOIDsItem);
    return this;
  }

   /**
   * Get criticalExtensionOIDs
   * @return criticalExtensionOIDs
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CRITICAL_EXTENSION_O_I_DS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Set<String> getCriticalExtensionOIDs() {
    return criticalExtensionOIDs;
  }


  @JsonDeserialize(as = LinkedHashSet.class)
  @JsonProperty(JSON_PROPERTY_CRITICAL_EXTENSION_O_I_DS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCriticalExtensionOIDs(Set<String> criticalExtensionOIDs) {
    this.criticalExtensionOIDs = criticalExtensionOIDs;
  }


  public CertificateDTOCertificate nonCriticalExtensionOIDs(Set<String> nonCriticalExtensionOIDs) {
    
    this.nonCriticalExtensionOIDs = nonCriticalExtensionOIDs;
    return this;
  }

  public CertificateDTOCertificate addNonCriticalExtensionOIDsItem(String nonCriticalExtensionOIDsItem) {
    if (this.nonCriticalExtensionOIDs == null) {
      this.nonCriticalExtensionOIDs = new LinkedHashSet<>();
    }
    this.nonCriticalExtensionOIDs.add(nonCriticalExtensionOIDsItem);
    return this;
  }

   /**
   * Get nonCriticalExtensionOIDs
   * @return nonCriticalExtensionOIDs
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_NON_CRITICAL_EXTENSION_O_I_DS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Set<String> getNonCriticalExtensionOIDs() {
    return nonCriticalExtensionOIDs;
  }


  @JsonDeserialize(as = LinkedHashSet.class)
  @JsonProperty(JSON_PROPERTY_NON_CRITICAL_EXTENSION_O_I_DS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNonCriticalExtensionOIDs(Set<String> nonCriticalExtensionOIDs) {
    this.nonCriticalExtensionOIDs = nonCriticalExtensionOIDs;
  }


  public CertificateDTOCertificate type(String type) {
    
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getType() {
    return type;
  }


  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setType(String type) {
    this.type = type;
  }


  public CertificateDTOCertificate encoded(byte[] encoded) {
    
    this.encoded = encoded;
    return this;
  }

   /**
   * Get encoded
   * @return encoded
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ENCODED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public byte[] getEncoded() {
    return encoded;
  }


  @JsonProperty(JSON_PROPERTY_ENCODED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEncoded(byte[] encoded) {
    this.encoded = encoded;
  }


  public CertificateDTOCertificate publicKey(CertificateDTOCertificatePublicKey publicKey) {
    
    this.publicKey = publicKey;
    return this;
  }

   /**
   * Get publicKey
   * @return publicKey
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_PUBLIC_KEY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public CertificateDTOCertificatePublicKey getPublicKey() {
    return publicKey;
  }


  @JsonProperty(JSON_PROPERTY_PUBLIC_KEY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPublicKey(CertificateDTOCertificatePublicKey publicKey) {
    this.publicKey = publicKey;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CertificateDTOCertificate certificateDTOCertificate = (CertificateDTOCertificate) o;
    return Arrays.equals(this.signature, certificateDTOCertificate.signature) &&
        Objects.equals(this.basicConstraints, certificateDTOCertificate.basicConstraints) &&
        Objects.equals(this.issuerX500Principal, certificateDTOCertificate.issuerX500Principal) &&
        Objects.equals(this.subjectX500Principal, certificateDTOCertificate.subjectX500Principal) &&
        Objects.equals(this.version, certificateDTOCertificate.version) &&
        Objects.equals(this.extendedKeyUsage, certificateDTOCertificate.extendedKeyUsage) &&
        Objects.equals(this.subjectAlternativeNames, certificateDTOCertificate.subjectAlternativeNames) &&
        Objects.equals(this.issuerAlternativeNames, certificateDTOCertificate.issuerAlternativeNames) &&
        Objects.equals(this.sigAlgName, certificateDTOCertificate.sigAlgName) &&
        Arrays.equals(this.sigAlgParams, certificateDTOCertificate.sigAlgParams) &&
        Arrays.equals(this.tbscertificate, certificateDTOCertificate.tbscertificate) &&
        Objects.equals(this.serialNumber, certificateDTOCertificate.serialNumber) &&
        Objects.equals(this.issuerDN, certificateDTOCertificate.issuerDN) &&
        Objects.equals(this.subjectDN, certificateDTOCertificate.subjectDN) &&
        Objects.equals(this.notBefore, certificateDTOCertificate.notBefore) &&
        Objects.equals(this.notAfter, certificateDTOCertificate.notAfter) &&
        Objects.equals(this.sigAlgOID, certificateDTOCertificate.sigAlgOID) &&
        Objects.equals(this.issuerUniqueID, certificateDTOCertificate.issuerUniqueID) &&
        Objects.equals(this.subjectUniqueID, certificateDTOCertificate.subjectUniqueID) &&
        Objects.equals(this.keyUsage, certificateDTOCertificate.keyUsage) &&
        Objects.equals(this.criticalExtensionOIDs, certificateDTOCertificate.criticalExtensionOIDs) &&
        Objects.equals(this.nonCriticalExtensionOIDs, certificateDTOCertificate.nonCriticalExtensionOIDs) &&
        Objects.equals(this.type, certificateDTOCertificate.type) &&
        Arrays.equals(this.encoded, certificateDTOCertificate.encoded) &&
        Objects.equals(this.publicKey, certificateDTOCertificate.publicKey);
  }

  @Override
  public int hashCode() {
    return Objects.hash(Arrays.hashCode(signature), basicConstraints, issuerX500Principal, subjectX500Principal, version, extendedKeyUsage, subjectAlternativeNames, issuerAlternativeNames, sigAlgName, Arrays.hashCode(sigAlgParams), Arrays.hashCode(tbscertificate), serialNumber, issuerDN, subjectDN, notBefore, notAfter, sigAlgOID, issuerUniqueID, subjectUniqueID, keyUsage, criticalExtensionOIDs, nonCriticalExtensionOIDs, type, Arrays.hashCode(encoded), publicKey);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CertificateDTOCertificate {\n");
    sb.append("    signature: ").append(toIndentedString(signature)).append("\n");
    sb.append("    basicConstraints: ").append(toIndentedString(basicConstraints)).append("\n");
    sb.append("    issuerX500Principal: ").append(toIndentedString(issuerX500Principal)).append("\n");
    sb.append("    subjectX500Principal: ").append(toIndentedString(subjectX500Principal)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    extendedKeyUsage: ").append(toIndentedString(extendedKeyUsage)).append("\n");
    sb.append("    subjectAlternativeNames: ").append(toIndentedString(subjectAlternativeNames)).append("\n");
    sb.append("    issuerAlternativeNames: ").append(toIndentedString(issuerAlternativeNames)).append("\n");
    sb.append("    sigAlgName: ").append(toIndentedString(sigAlgName)).append("\n");
    sb.append("    sigAlgParams: ").append(toIndentedString(sigAlgParams)).append("\n");
    sb.append("    tbscertificate: ").append(toIndentedString(tbscertificate)).append("\n");
    sb.append("    serialNumber: ").append(toIndentedString(serialNumber)).append("\n");
    sb.append("    issuerDN: ").append(toIndentedString(issuerDN)).append("\n");
    sb.append("    subjectDN: ").append(toIndentedString(subjectDN)).append("\n");
    sb.append("    notBefore: ").append(toIndentedString(notBefore)).append("\n");
    sb.append("    notAfter: ").append(toIndentedString(notAfter)).append("\n");
    sb.append("    sigAlgOID: ").append(toIndentedString(sigAlgOID)).append("\n");
    sb.append("    issuerUniqueID: ").append(toIndentedString(issuerUniqueID)).append("\n");
    sb.append("    subjectUniqueID: ").append(toIndentedString(subjectUniqueID)).append("\n");
    sb.append("    keyUsage: ").append(toIndentedString(keyUsage)).append("\n");
    sb.append("    criticalExtensionOIDs: ").append(toIndentedString(criticalExtensionOIDs)).append("\n");
    sb.append("    nonCriticalExtensionOIDs: ").append(toIndentedString(nonCriticalExtensionOIDs)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    encoded: ").append(toIndentedString(encoded)).append("\n");
    sb.append("    publicKey: ").append(toIndentedString(publicKey)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

