/*
 * Viafirma API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.3.29-r83-596fbc1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ClientAccessResponseDTO
 */
@JsonPropertyOrder({
  ClientAccessResponseDTO.JSON_PROPERTY_DESKTOP_PROTOCOL,
  ClientAccessResponseDTO.JSON_PROPERTY_LINK,
  ClientAccessResponseDTO.JSON_PROPERTY_FORTRESS_LINK
})
@JsonTypeName("ClientAccessResponseDTO")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-03-04T11:20:43.685+01:00[Europe/Paris]")
public class ClientAccessResponseDTO {
  public static final String JSON_PROPERTY_DESKTOP_PROTOCOL = "desktopProtocol";
  private String desktopProtocol;

  public static final String JSON_PROPERTY_LINK = "link";
  private String link;

  public static final String JSON_PROPERTY_FORTRESS_LINK = "fortressLink";
  private String fortressLink;

  public ClientAccessResponseDTO() { 
  }

  public ClientAccessResponseDTO desktopProtocol(String desktopProtocol) {
    
    this.desktopProtocol = desktopProtocol;
    return this;
  }

   /**
   * Get desktopProtocol
   * @return desktopProtocol
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_DESKTOP_PROTOCOL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDesktopProtocol() {
    return desktopProtocol;
  }


  @JsonProperty(JSON_PROPERTY_DESKTOP_PROTOCOL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDesktopProtocol(String desktopProtocol) {
    this.desktopProtocol = desktopProtocol;
  }


  public ClientAccessResponseDTO link(String link) {
    
    this.link = link;
    return this;
  }

   /**
   * Get link
   * @return link
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_LINK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLink() {
    return link;
  }


  @JsonProperty(JSON_PROPERTY_LINK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLink(String link) {
    this.link = link;
  }


  public ClientAccessResponseDTO fortressLink(String fortressLink) {
    
    this.fortressLink = fortressLink;
    return this;
  }

   /**
   * Get fortressLink
   * @return fortressLink
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_FORTRESS_LINK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFortressLink() {
    return fortressLink;
  }


  @JsonProperty(JSON_PROPERTY_FORTRESS_LINK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFortressLink(String fortressLink) {
    this.fortressLink = fortressLink;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ClientAccessResponseDTO clientAccessResponseDTO = (ClientAccessResponseDTO) o;
    return Objects.equals(this.desktopProtocol, clientAccessResponseDTO.desktopProtocol) &&
        Objects.equals(this.link, clientAccessResponseDTO.link) &&
        Objects.equals(this.fortressLink, clientAccessResponseDTO.fortressLink);
  }

  @Override
  public int hashCode() {
    return Objects.hash(desktopProtocol, link, fortressLink);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ClientAccessResponseDTO {\n");
    sb.append("    desktopProtocol: ").append(toIndentedString(desktopProtocol)).append("\n");
    sb.append("    link: ").append(toIndentedString(link)).append("\n");
    sb.append("    fortressLink: ").append(toIndentedString(fortressLink)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

