/*
 * Viafirma API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.3.29-r83-596fbc1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ConfigCadesDTO
 */
@JsonPropertyOrder({
  ConfigCadesDTO.JSON_PROPERTY_TO_COUNTER_SIGN_SIGNATURE_VALUE_ID
})
@JsonTypeName("ConfigCadesDTO")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-03-04T11:20:43.685+01:00[Europe/Paris]")
public class ConfigCadesDTO {
  public static final String JSON_PROPERTY_TO_COUNTER_SIGN_SIGNATURE_VALUE_ID = "toCounterSignSignatureValueId";
  private String toCounterSignSignatureValueId;

  public ConfigCadesDTO() { 
  }

  public ConfigCadesDTO toCounterSignSignatureValueId(String toCounterSignSignatureValueId) {
    
    this.toCounterSignSignatureValueId = toCounterSignSignatureValueId;
    return this;
  }

   /**
   * Get toCounterSignSignatureValueId
   * @return toCounterSignSignatureValueId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TO_COUNTER_SIGN_SIGNATURE_VALUE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getToCounterSignSignatureValueId() {
    return toCounterSignSignatureValueId;
  }


  @JsonProperty(JSON_PROPERTY_TO_COUNTER_SIGN_SIGNATURE_VALUE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setToCounterSignSignatureValueId(String toCounterSignSignatureValueId) {
    this.toCounterSignSignatureValueId = toCounterSignSignatureValueId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConfigCadesDTO configCadesDTO = (ConfigCadesDTO) o;
    return Objects.equals(this.toCounterSignSignatureValueId, configCadesDTO.toCounterSignSignatureValueId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(toCounterSignSignatureValueId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConfigCadesDTO {\n");
    sb.append("    toCounterSignSignatureValueId: ").append(toIndentedString(toCounterSignSignatureValueId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

