/*
 * Viafirma API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.3.29-r83-596fbc1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.openapitools.client.model.StamperDTO;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ConfigPadesDTO
 */
@JsonPropertyOrder({
  ConfigPadesDTO.JSON_PROPERTY_STAMPER,
  ConfigPadesDTO.JSON_PROPERTY_CERTIFICATION_LEVEL,
  ConfigPadesDTO.JSON_PROPERTY_EXTERNAL_PKCS7_SIGNATURE,
  ConfigPadesDTO.JSON_PROPERTY_PASSWORD,
  ConfigPadesDTO.JSON_PROPERTY_VALIDATE_PDF_SYNTAX
})
@JsonTypeName("ConfigPadesDTO")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-03-04T11:20:43.685+01:00[Europe/Paris]")
public class ConfigPadesDTO {
  public static final String JSON_PROPERTY_STAMPER = "stamper";
  private StamperDTO stamper;

  /**
   * Gets or Sets certificationLevel
   */
  public enum CertificationLevelEnum {
    NOT_CERTIFIED("NOT_CERTIFIED"),
    
    CERTIFIED_NO_CHANGES_ALLOWED("CERTIFIED_NO_CHANGES_ALLOWED"),
    
    CERTIFIED_FORM_FILLING("CERTIFIED_FORM_FILLING"),
    
    CERTIFIED_FORM_FILLING_AND_ANNOTATIONS("CERTIFIED_FORM_FILLING_AND_ANNOTATIONS");

    private String value;

    CertificationLevelEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static CertificationLevelEnum fromValue(String value) {
      for (CertificationLevelEnum b : CertificationLevelEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_CERTIFICATION_LEVEL = "certificationLevel";
  private CertificationLevelEnum certificationLevel;

  public static final String JSON_PROPERTY_EXTERNAL_PKCS7_SIGNATURE = "externalPkcs7Signature";
  private Boolean externalPkcs7Signature;

  public static final String JSON_PROPERTY_PASSWORD = "password";
  private String password;

  public static final String JSON_PROPERTY_VALIDATE_PDF_SYNTAX = "validatePdfSyntax";
  private Boolean validatePdfSyntax;

  public ConfigPadesDTO() { 
  }

  public ConfigPadesDTO stamper(StamperDTO stamper) {
    
    this.stamper = stamper;
    return this;
  }

   /**
   * Get stamper
   * @return stamper
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_STAMPER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public StamperDTO getStamper() {
    return stamper;
  }


  @JsonProperty(JSON_PROPERTY_STAMPER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStamper(StamperDTO stamper) {
    this.stamper = stamper;
  }


  public ConfigPadesDTO certificationLevel(CertificationLevelEnum certificationLevel) {
    
    this.certificationLevel = certificationLevel;
    return this;
  }

   /**
   * Get certificationLevel
   * @return certificationLevel
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CERTIFICATION_LEVEL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public CertificationLevelEnum getCertificationLevel() {
    return certificationLevel;
  }


  @JsonProperty(JSON_PROPERTY_CERTIFICATION_LEVEL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCertificationLevel(CertificationLevelEnum certificationLevel) {
    this.certificationLevel = certificationLevel;
  }


  public ConfigPadesDTO externalPkcs7Signature(Boolean externalPkcs7Signature) {
    
    this.externalPkcs7Signature = externalPkcs7Signature;
    return this;
  }

   /**
   * Get externalPkcs7Signature
   * @return externalPkcs7Signature
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_EXTERNAL_PKCS7_SIGNATURE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getExternalPkcs7Signature() {
    return externalPkcs7Signature;
  }


  @JsonProperty(JSON_PROPERTY_EXTERNAL_PKCS7_SIGNATURE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExternalPkcs7Signature(Boolean externalPkcs7Signature) {
    this.externalPkcs7Signature = externalPkcs7Signature;
  }


  public ConfigPadesDTO password(String password) {
    
    this.password = password;
    return this;
  }

   /**
   * Get password
   * @return password
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_PASSWORD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPassword() {
    return password;
  }


  @JsonProperty(JSON_PROPERTY_PASSWORD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPassword(String password) {
    this.password = password;
  }


  public ConfigPadesDTO validatePdfSyntax(Boolean validatePdfSyntax) {
    
    this.validatePdfSyntax = validatePdfSyntax;
    return this;
  }

   /**
   * Get validatePdfSyntax
   * @return validatePdfSyntax
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_VALIDATE_PDF_SYNTAX)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getValidatePdfSyntax() {
    return validatePdfSyntax;
  }


  @JsonProperty(JSON_PROPERTY_VALIDATE_PDF_SYNTAX)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setValidatePdfSyntax(Boolean validatePdfSyntax) {
    this.validatePdfSyntax = validatePdfSyntax;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConfigPadesDTO configPadesDTO = (ConfigPadesDTO) o;
    return Objects.equals(this.stamper, configPadesDTO.stamper) &&
        Objects.equals(this.certificationLevel, configPadesDTO.certificationLevel) &&
        Objects.equals(this.externalPkcs7Signature, configPadesDTO.externalPkcs7Signature) &&
        Objects.equals(this.password, configPadesDTO.password) &&
        Objects.equals(this.validatePdfSyntax, configPadesDTO.validatePdfSyntax);
  }

  @Override
  public int hashCode() {
    return Objects.hash(stamper, certificationLevel, externalPkcs7Signature, password, validatePdfSyntax);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConfigPadesDTO {\n");
    sb.append("    stamper: ").append(toIndentedString(stamper)).append("\n");
    sb.append("    certificationLevel: ").append(toIndentedString(certificationLevel)).append("\n");
    sb.append("    externalPkcs7Signature: ").append(toIndentedString(externalPkcs7Signature)).append("\n");
    sb.append("    password: ").append(toIndentedString(password)).append("\n");
    sb.append("    validatePdfSyntax: ").append(toIndentedString(validatePdfSyntax)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

