/*
 * Viafirma API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.3.29-r83-596fbc1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.ConfigCadesDTO;
import org.openapitools.client.model.ConfigPadesDTO;
import org.openapitools.client.model.ConfigPolicyDTO;
import org.openapitools.client.model.ConfigTsaDTO;
import org.openapitools.client.model.ConfigXadesDTO;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ConfigSignatureDTO
 */
@JsonPropertyOrder({
  ConfigSignatureDTO.JSON_PROPERTY_ID_REFERENCE,
  ConfigSignatureDTO.JSON_PROPERTY_SIGNATURE_ALGORITHM,
  ConfigSignatureDTO.JSON_PROPERTY_CUSTODY_CODE,
  ConfigSignatureDTO.JSON_PROPERTY_CUSTODY_STORAGE,
  ConfigSignatureDTO.JSON_PROPERTY_CUSTODY_ENCRYPTED,
  ConfigSignatureDTO.JSON_PROPERTY_AUDITORY_CIPHER_DISABLE,
  ConfigSignatureDTO.JSON_PROPERTY_AUDITORY_DISABLE,
  ConfigSignatureDTO.JSON_PROPERTY_TSA,
  ConfigSignatureDTO.JSON_PROPERTY_SIGNATURE_TYPE,
  ConfigSignatureDTO.JSON_PROPERTY_PACKAGING,
  ConfigSignatureDTO.JSON_PROPERTY_POLICY,
  ConfigSignatureDTO.JSON_PROPERTY_VALID_SIGNER_IDS,
  ConfigSignatureDTO.JSON_PROPERTY_SIGNATURE_REASON,
  ConfigSignatureDTO.JSON_PROPERTY_COUNTRY,
  ConfigSignatureDTO.JSON_PROPERTY_STATE_OR_PROVINCE,
  ConfigSignatureDTO.JSON_PROPERTY_POSTAL_CODE,
  ConfigSignatureDTO.JSON_PROPERTY_CITY,
  ConfigSignatureDTO.JSON_PROPERTY_CADES_CONFIG,
  ConfigSignatureDTO.JSON_PROPERTY_PADES_CONFIG,
  ConfigSignatureDTO.JSON_PROPERTY_XADES_CONFIG,
  ConfigSignatureDTO.JSON_PROPERTY_OPERATION_ID,
  ConfigSignatureDTO.JSON_PROPERTY_OPERATION_SERVER,
  ConfigSignatureDTO.JSON_PROPERTY_TIMESTAMP_ALGORITHM,
  ConfigSignatureDTO.JSON_PROPERTY_AUTO_VERIFY_DISABLED,
  ConfigSignatureDTO.JSON_PROPERTY_AUTO_VERIFY_ERROR,
  ConfigSignatureDTO.JSON_PROPERTY_REVOCATION_REQUEST_TYPE,
  ConfigSignatureDTO.JSON_PROPERTY_FILE_NAME
})
@JsonTypeName("ConfigSignatureDTO")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-03-04T11:20:43.685+01:00[Europe/Paris]")
public class ConfigSignatureDTO {
  public static final String JSON_PROPERTY_ID_REFERENCE = "idReference";
  private String idReference;

  /**
   * Gets or Sets signatureAlgorithm
   */
  public enum SignatureAlgorithmEnum {
    RSA_MD5("RSA_MD5"),
    
    RSA_SHA1("RSA_SHA1"),
    
    RSA_SHA224("RSA_SHA224"),
    
    RSA_SHA256("RSA_SHA256"),
    
    RSA_SHA384("RSA_SHA384"),
    
    RSA_SHA512("RSA_SHA512"),
    
    ECDSA_SHA1("ECDSA_SHA1"),
    
    ECDSA_SHA224("ECDSA_SHA224"),
    
    ECDSA_SHA256("ECDSA_SHA256"),
    
    ECDSA_SHA384("ECDSA_SHA384"),
    
    ECDSA_SHA512("ECDSA_SHA512");

    private String value;

    SignatureAlgorithmEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static SignatureAlgorithmEnum fromValue(String value) {
      for (SignatureAlgorithmEnum b : SignatureAlgorithmEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_SIGNATURE_ALGORITHM = "signatureAlgorithm";
  private SignatureAlgorithmEnum signatureAlgorithm;

  public static final String JSON_PROPERTY_CUSTODY_CODE = "custodyCode";
  private String custodyCode;

  public static final String JSON_PROPERTY_CUSTODY_STORAGE = "custodyStorage";
  private Boolean custodyStorage;

  public static final String JSON_PROPERTY_CUSTODY_ENCRYPTED = "custodyEncrypted";
  private Boolean custodyEncrypted;

  public static final String JSON_PROPERTY_AUDITORY_CIPHER_DISABLE = "auditoryCipherDisable";
  private Boolean auditoryCipherDisable;

  public static final String JSON_PROPERTY_AUDITORY_DISABLE = "auditoryDisable";
  private Boolean auditoryDisable;

  public static final String JSON_PROPERTY_TSA = "tsa";
  private ConfigTsaDTO tsa;

  /**
   * Gets or Sets signatureType
   */
  public enum SignatureTypeEnum {
    CADES_B("CADES_B"),
    
    CADES_T("CADES_T"),
    
    CADES_LT("CADES_LT"),
    
    CADES_LTA("CADES_LTA"),
    
    PADES_B("PADES_B"),
    
    PADES_T("PADES_T"),
    
    PADES_LT("PADES_LT"),
    
    PADES_LTA("PADES_LTA"),
    
    XADES_B("XADES_B"),
    
    XADES_T("XADES_T"),
    
    XADES_LT("XADES_LT"),
    
    XADES_LTA("XADES_LTA");

    private String value;

    SignatureTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static SignatureTypeEnum fromValue(String value) {
      for (SignatureTypeEnum b : SignatureTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_SIGNATURE_TYPE = "signatureType";
  private SignatureTypeEnum signatureType;

  /**
   * Gets or Sets packaging
   */
  public enum PackagingEnum {
    ENVELOPED("ENVELOPED"),
    
    ENVELOPING("ENVELOPING"),
    
    DETACHED("DETACHED");

    private String value;

    PackagingEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static PackagingEnum fromValue(String value) {
      for (PackagingEnum b : PackagingEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_PACKAGING = "packaging";
  private PackagingEnum packaging;

  public static final String JSON_PROPERTY_POLICY = "policy";
  private ConfigPolicyDTO policy;

  public static final String JSON_PROPERTY_VALID_SIGNER_IDS = "validSignerIds";
  private List<String> validSignerIds = null;

  public static final String JSON_PROPERTY_SIGNATURE_REASON = "signatureReason";
  private String signatureReason;

  public static final String JSON_PROPERTY_COUNTRY = "country";
  private String country;

  public static final String JSON_PROPERTY_STATE_OR_PROVINCE = "stateOrProvince";
  private String stateOrProvince;

  public static final String JSON_PROPERTY_POSTAL_CODE = "postalCode";
  private String postalCode;

  public static final String JSON_PROPERTY_CITY = "city";
  private String city;

  public static final String JSON_PROPERTY_CADES_CONFIG = "cadesConfig";
  private ConfigCadesDTO cadesConfig;

  public static final String JSON_PROPERTY_PADES_CONFIG = "padesConfig";
  private ConfigPadesDTO padesConfig;

  public static final String JSON_PROPERTY_XADES_CONFIG = "xadesConfig";
  private ConfigXadesDTO xadesConfig;

  public static final String JSON_PROPERTY_OPERATION_ID = "operationId";
  private String operationId;

  public static final String JSON_PROPERTY_OPERATION_SERVER = "operationServer";
  private String operationServer;

  /**
   * Gets or Sets timestampAlgorithm
   */
  public enum TimestampAlgorithmEnum {
    SHA1("SHA1"),
    
    SHA224("SHA224"),
    
    SHA256("SHA256"),
    
    SHA384("SHA384"),
    
    SHA512("SHA512"),
    
    RIPEMD160("RIPEMD160"),
    
    MD2("MD2"),
    
    MD5("MD5");

    private String value;

    TimestampAlgorithmEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TimestampAlgorithmEnum fromValue(String value) {
      for (TimestampAlgorithmEnum b : TimestampAlgorithmEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_TIMESTAMP_ALGORITHM = "timestampAlgorithm";
  private TimestampAlgorithmEnum timestampAlgorithm;

  public static final String JSON_PROPERTY_AUTO_VERIFY_DISABLED = "autoVerifyDisabled";
  private Boolean autoVerifyDisabled;

  public static final String JSON_PROPERTY_AUTO_VERIFY_ERROR = "autoVerifyError";
  private Boolean autoVerifyError;

  /**
   * Gets or Sets revocationRequestType
   */
  public enum RevocationRequestTypeEnum {
    ONLINE("ONLINE"),
    
    ONLINE_WITH_CACHE("ONLINE_WITH_CACHE"),
    
    CRL("CRL"),
    
    CRL_CACHE("CRL_CACHE"),
    
    OCSP("OCSP"),
    
    NONE("NONE");

    private String value;

    RevocationRequestTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static RevocationRequestTypeEnum fromValue(String value) {
      for (RevocationRequestTypeEnum b : RevocationRequestTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_REVOCATION_REQUEST_TYPE = "revocationRequestType";
  private RevocationRequestTypeEnum revocationRequestType;

  public static final String JSON_PROPERTY_FILE_NAME = "fileName";
  private String fileName;

  public ConfigSignatureDTO() { 
  }

  public ConfigSignatureDTO idReference(String idReference) {
    
    this.idReference = idReference;
    return this;
  }

   /**
   * Get idReference
   * @return idReference
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ID_REFERENCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getIdReference() {
    return idReference;
  }


  @JsonProperty(JSON_PROPERTY_ID_REFERENCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIdReference(String idReference) {
    this.idReference = idReference;
  }


  public ConfigSignatureDTO signatureAlgorithm(SignatureAlgorithmEnum signatureAlgorithm) {
    
    this.signatureAlgorithm = signatureAlgorithm;
    return this;
  }

   /**
   * Get signatureAlgorithm
   * @return signatureAlgorithm
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SIGNATURE_ALGORITHM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public SignatureAlgorithmEnum getSignatureAlgorithm() {
    return signatureAlgorithm;
  }


  @JsonProperty(JSON_PROPERTY_SIGNATURE_ALGORITHM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSignatureAlgorithm(SignatureAlgorithmEnum signatureAlgorithm) {
    this.signatureAlgorithm = signatureAlgorithm;
  }


  public ConfigSignatureDTO custodyCode(String custodyCode) {
    
    this.custodyCode = custodyCode;
    return this;
  }

   /**
   * Get custodyCode
   * @return custodyCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CUSTODY_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCustodyCode() {
    return custodyCode;
  }


  @JsonProperty(JSON_PROPERTY_CUSTODY_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCustodyCode(String custodyCode) {
    this.custodyCode = custodyCode;
  }


  public ConfigSignatureDTO custodyStorage(Boolean custodyStorage) {
    
    this.custodyStorage = custodyStorage;
    return this;
  }

   /**
   * Get custodyStorage
   * @return custodyStorage
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CUSTODY_STORAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getCustodyStorage() {
    return custodyStorage;
  }


  @JsonProperty(JSON_PROPERTY_CUSTODY_STORAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCustodyStorage(Boolean custodyStorage) {
    this.custodyStorage = custodyStorage;
  }


  public ConfigSignatureDTO custodyEncrypted(Boolean custodyEncrypted) {
    
    this.custodyEncrypted = custodyEncrypted;
    return this;
  }

   /**
   * Get custodyEncrypted
   * @return custodyEncrypted
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CUSTODY_ENCRYPTED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getCustodyEncrypted() {
    return custodyEncrypted;
  }


  @JsonProperty(JSON_PROPERTY_CUSTODY_ENCRYPTED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCustodyEncrypted(Boolean custodyEncrypted) {
    this.custodyEncrypted = custodyEncrypted;
  }


  public ConfigSignatureDTO auditoryCipherDisable(Boolean auditoryCipherDisable) {
    
    this.auditoryCipherDisable = auditoryCipherDisable;
    return this;
  }

   /**
   * Get auditoryCipherDisable
   * @return auditoryCipherDisable
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_AUDITORY_CIPHER_DISABLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getAuditoryCipherDisable() {
    return auditoryCipherDisable;
  }


  @JsonProperty(JSON_PROPERTY_AUDITORY_CIPHER_DISABLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAuditoryCipherDisable(Boolean auditoryCipherDisable) {
    this.auditoryCipherDisable = auditoryCipherDisable;
  }


  public ConfigSignatureDTO auditoryDisable(Boolean auditoryDisable) {
    
    this.auditoryDisable = auditoryDisable;
    return this;
  }

   /**
   * Get auditoryDisable
   * @return auditoryDisable
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_AUDITORY_DISABLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getAuditoryDisable() {
    return auditoryDisable;
  }


  @JsonProperty(JSON_PROPERTY_AUDITORY_DISABLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAuditoryDisable(Boolean auditoryDisable) {
    this.auditoryDisable = auditoryDisable;
  }


  public ConfigSignatureDTO tsa(ConfigTsaDTO tsa) {
    
    this.tsa = tsa;
    return this;
  }

   /**
   * Get tsa
   * @return tsa
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TSA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ConfigTsaDTO getTsa() {
    return tsa;
  }


  @JsonProperty(JSON_PROPERTY_TSA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTsa(ConfigTsaDTO tsa) {
    this.tsa = tsa;
  }


  public ConfigSignatureDTO signatureType(SignatureTypeEnum signatureType) {
    
    this.signatureType = signatureType;
    return this;
  }

   /**
   * Get signatureType
   * @return signatureType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SIGNATURE_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public SignatureTypeEnum getSignatureType() {
    return signatureType;
  }


  @JsonProperty(JSON_PROPERTY_SIGNATURE_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSignatureType(SignatureTypeEnum signatureType) {
    this.signatureType = signatureType;
  }


  public ConfigSignatureDTO packaging(PackagingEnum packaging) {
    
    this.packaging = packaging;
    return this;
  }

   /**
   * Get packaging
   * @return packaging
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_PACKAGING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public PackagingEnum getPackaging() {
    return packaging;
  }


  @JsonProperty(JSON_PROPERTY_PACKAGING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPackaging(PackagingEnum packaging) {
    this.packaging = packaging;
  }


  public ConfigSignatureDTO policy(ConfigPolicyDTO policy) {
    
    this.policy = policy;
    return this;
  }

   /**
   * Get policy
   * @return policy
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_POLICY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ConfigPolicyDTO getPolicy() {
    return policy;
  }


  @JsonProperty(JSON_PROPERTY_POLICY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPolicy(ConfigPolicyDTO policy) {
    this.policy = policy;
  }


  public ConfigSignatureDTO validSignerIds(List<String> validSignerIds) {
    
    this.validSignerIds = validSignerIds;
    return this;
  }

  public ConfigSignatureDTO addValidSignerIdsItem(String validSignerIdsItem) {
    if (this.validSignerIds == null) {
      this.validSignerIds = new ArrayList<>();
    }
    this.validSignerIds.add(validSignerIdsItem);
    return this;
  }

   /**
   * Get validSignerIds
   * @return validSignerIds
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_VALID_SIGNER_IDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getValidSignerIds() {
    return validSignerIds;
  }


  @JsonProperty(JSON_PROPERTY_VALID_SIGNER_IDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setValidSignerIds(List<String> validSignerIds) {
    this.validSignerIds = validSignerIds;
  }


  public ConfigSignatureDTO signatureReason(String signatureReason) {
    
    this.signatureReason = signatureReason;
    return this;
  }

   /**
   * Get signatureReason
   * @return signatureReason
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SIGNATURE_REASON)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSignatureReason() {
    return signatureReason;
  }


  @JsonProperty(JSON_PROPERTY_SIGNATURE_REASON)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSignatureReason(String signatureReason) {
    this.signatureReason = signatureReason;
  }


  public ConfigSignatureDTO country(String country) {
    
    this.country = country;
    return this;
  }

   /**
   * Get country
   * @return country
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_COUNTRY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCountry() {
    return country;
  }


  @JsonProperty(JSON_PROPERTY_COUNTRY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCountry(String country) {
    this.country = country;
  }


  public ConfigSignatureDTO stateOrProvince(String stateOrProvince) {
    
    this.stateOrProvince = stateOrProvince;
    return this;
  }

   /**
   * Get stateOrProvince
   * @return stateOrProvince
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_STATE_OR_PROVINCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getStateOrProvince() {
    return stateOrProvince;
  }


  @JsonProperty(JSON_PROPERTY_STATE_OR_PROVINCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStateOrProvince(String stateOrProvince) {
    this.stateOrProvince = stateOrProvince;
  }


  public ConfigSignatureDTO postalCode(String postalCode) {
    
    this.postalCode = postalCode;
    return this;
  }

   /**
   * Get postalCode
   * @return postalCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_POSTAL_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPostalCode() {
    return postalCode;
  }


  @JsonProperty(JSON_PROPERTY_POSTAL_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPostalCode(String postalCode) {
    this.postalCode = postalCode;
  }


  public ConfigSignatureDTO city(String city) {
    
    this.city = city;
    return this;
  }

   /**
   * Get city
   * @return city
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCity() {
    return city;
  }


  @JsonProperty(JSON_PROPERTY_CITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCity(String city) {
    this.city = city;
  }


  public ConfigSignatureDTO cadesConfig(ConfigCadesDTO cadesConfig) {
    
    this.cadesConfig = cadesConfig;
    return this;
  }

   /**
   * Get cadesConfig
   * @return cadesConfig
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CADES_CONFIG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ConfigCadesDTO getCadesConfig() {
    return cadesConfig;
  }


  @JsonProperty(JSON_PROPERTY_CADES_CONFIG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCadesConfig(ConfigCadesDTO cadesConfig) {
    this.cadesConfig = cadesConfig;
  }


  public ConfigSignatureDTO padesConfig(ConfigPadesDTO padesConfig) {
    
    this.padesConfig = padesConfig;
    return this;
  }

   /**
   * Get padesConfig
   * @return padesConfig
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_PADES_CONFIG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ConfigPadesDTO getPadesConfig() {
    return padesConfig;
  }


  @JsonProperty(JSON_PROPERTY_PADES_CONFIG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPadesConfig(ConfigPadesDTO padesConfig) {
    this.padesConfig = padesConfig;
  }


  public ConfigSignatureDTO xadesConfig(ConfigXadesDTO xadesConfig) {
    
    this.xadesConfig = xadesConfig;
    return this;
  }

   /**
   * Get xadesConfig
   * @return xadesConfig
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_XADES_CONFIG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ConfigXadesDTO getXadesConfig() {
    return xadesConfig;
  }


  @JsonProperty(JSON_PROPERTY_XADES_CONFIG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setXadesConfig(ConfigXadesDTO xadesConfig) {
    this.xadesConfig = xadesConfig;
  }


  public ConfigSignatureDTO operationId(String operationId) {
    
    this.operationId = operationId;
    return this;
  }

   /**
   * Get operationId
   * @return operationId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_OPERATION_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getOperationId() {
    return operationId;
  }


  @JsonProperty(JSON_PROPERTY_OPERATION_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOperationId(String operationId) {
    this.operationId = operationId;
  }


  public ConfigSignatureDTO operationServer(String operationServer) {
    
    this.operationServer = operationServer;
    return this;
  }

   /**
   * Get operationServer
   * @return operationServer
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_OPERATION_SERVER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getOperationServer() {
    return operationServer;
  }


  @JsonProperty(JSON_PROPERTY_OPERATION_SERVER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOperationServer(String operationServer) {
    this.operationServer = operationServer;
  }


  public ConfigSignatureDTO timestampAlgorithm(TimestampAlgorithmEnum timestampAlgorithm) {
    
    this.timestampAlgorithm = timestampAlgorithm;
    return this;
  }

   /**
   * Get timestampAlgorithm
   * @return timestampAlgorithm
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TIMESTAMP_ALGORITHM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public TimestampAlgorithmEnum getTimestampAlgorithm() {
    return timestampAlgorithm;
  }


  @JsonProperty(JSON_PROPERTY_TIMESTAMP_ALGORITHM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTimestampAlgorithm(TimestampAlgorithmEnum timestampAlgorithm) {
    this.timestampAlgorithm = timestampAlgorithm;
  }


  public ConfigSignatureDTO autoVerifyDisabled(Boolean autoVerifyDisabled) {
    
    this.autoVerifyDisabled = autoVerifyDisabled;
    return this;
  }

   /**
   * Get autoVerifyDisabled
   * @return autoVerifyDisabled
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_AUTO_VERIFY_DISABLED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getAutoVerifyDisabled() {
    return autoVerifyDisabled;
  }


  @JsonProperty(JSON_PROPERTY_AUTO_VERIFY_DISABLED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAutoVerifyDisabled(Boolean autoVerifyDisabled) {
    this.autoVerifyDisabled = autoVerifyDisabled;
  }


  public ConfigSignatureDTO autoVerifyError(Boolean autoVerifyError) {
    
    this.autoVerifyError = autoVerifyError;
    return this;
  }

   /**
   * Get autoVerifyError
   * @return autoVerifyError
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_AUTO_VERIFY_ERROR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getAutoVerifyError() {
    return autoVerifyError;
  }


  @JsonProperty(JSON_PROPERTY_AUTO_VERIFY_ERROR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAutoVerifyError(Boolean autoVerifyError) {
    this.autoVerifyError = autoVerifyError;
  }


  public ConfigSignatureDTO revocationRequestType(RevocationRequestTypeEnum revocationRequestType) {
    
    this.revocationRequestType = revocationRequestType;
    return this;
  }

   /**
   * Get revocationRequestType
   * @return revocationRequestType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_REVOCATION_REQUEST_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RevocationRequestTypeEnum getRevocationRequestType() {
    return revocationRequestType;
  }


  @JsonProperty(JSON_PROPERTY_REVOCATION_REQUEST_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRevocationRequestType(RevocationRequestTypeEnum revocationRequestType) {
    this.revocationRequestType = revocationRequestType;
  }


  public ConfigSignatureDTO fileName(String fileName) {
    
    this.fileName = fileName;
    return this;
  }

   /**
   * Get fileName
   * @return fileName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_FILE_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFileName() {
    return fileName;
  }


  @JsonProperty(JSON_PROPERTY_FILE_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFileName(String fileName) {
    this.fileName = fileName;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConfigSignatureDTO configSignatureDTO = (ConfigSignatureDTO) o;
    return Objects.equals(this.idReference, configSignatureDTO.idReference) &&
        Objects.equals(this.signatureAlgorithm, configSignatureDTO.signatureAlgorithm) &&
        Objects.equals(this.custodyCode, configSignatureDTO.custodyCode) &&
        Objects.equals(this.custodyStorage, configSignatureDTO.custodyStorage) &&
        Objects.equals(this.custodyEncrypted, configSignatureDTO.custodyEncrypted) &&
        Objects.equals(this.auditoryCipherDisable, configSignatureDTO.auditoryCipherDisable) &&
        Objects.equals(this.auditoryDisable, configSignatureDTO.auditoryDisable) &&
        Objects.equals(this.tsa, configSignatureDTO.tsa) &&
        Objects.equals(this.signatureType, configSignatureDTO.signatureType) &&
        Objects.equals(this.packaging, configSignatureDTO.packaging) &&
        Objects.equals(this.policy, configSignatureDTO.policy) &&
        Objects.equals(this.validSignerIds, configSignatureDTO.validSignerIds) &&
        Objects.equals(this.signatureReason, configSignatureDTO.signatureReason) &&
        Objects.equals(this.country, configSignatureDTO.country) &&
        Objects.equals(this.stateOrProvince, configSignatureDTO.stateOrProvince) &&
        Objects.equals(this.postalCode, configSignatureDTO.postalCode) &&
        Objects.equals(this.city, configSignatureDTO.city) &&
        Objects.equals(this.cadesConfig, configSignatureDTO.cadesConfig) &&
        Objects.equals(this.padesConfig, configSignatureDTO.padesConfig) &&
        Objects.equals(this.xadesConfig, configSignatureDTO.xadesConfig) &&
        Objects.equals(this.operationId, configSignatureDTO.operationId) &&
        Objects.equals(this.operationServer, configSignatureDTO.operationServer) &&
        Objects.equals(this.timestampAlgorithm, configSignatureDTO.timestampAlgorithm) &&
        Objects.equals(this.autoVerifyDisabled, configSignatureDTO.autoVerifyDisabled) &&
        Objects.equals(this.autoVerifyError, configSignatureDTO.autoVerifyError) &&
        Objects.equals(this.revocationRequestType, configSignatureDTO.revocationRequestType) &&
        Objects.equals(this.fileName, configSignatureDTO.fileName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(idReference, signatureAlgorithm, custodyCode, custodyStorage, custodyEncrypted, auditoryCipherDisable, auditoryDisable, tsa, signatureType, packaging, policy, validSignerIds, signatureReason, country, stateOrProvince, postalCode, city, cadesConfig, padesConfig, xadesConfig, operationId, operationServer, timestampAlgorithm, autoVerifyDisabled, autoVerifyError, revocationRequestType, fileName);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConfigSignatureDTO {\n");
    sb.append("    idReference: ").append(toIndentedString(idReference)).append("\n");
    sb.append("    signatureAlgorithm: ").append(toIndentedString(signatureAlgorithm)).append("\n");
    sb.append("    custodyCode: ").append(toIndentedString(custodyCode)).append("\n");
    sb.append("    custodyStorage: ").append(toIndentedString(custodyStorage)).append("\n");
    sb.append("    custodyEncrypted: ").append(toIndentedString(custodyEncrypted)).append("\n");
    sb.append("    auditoryCipherDisable: ").append(toIndentedString(auditoryCipherDisable)).append("\n");
    sb.append("    auditoryDisable: ").append(toIndentedString(auditoryDisable)).append("\n");
    sb.append("    tsa: ").append(toIndentedString(tsa)).append("\n");
    sb.append("    signatureType: ").append(toIndentedString(signatureType)).append("\n");
    sb.append("    packaging: ").append(toIndentedString(packaging)).append("\n");
    sb.append("    policy: ").append(toIndentedString(policy)).append("\n");
    sb.append("    validSignerIds: ").append(toIndentedString(validSignerIds)).append("\n");
    sb.append("    signatureReason: ").append(toIndentedString(signatureReason)).append("\n");
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("    stateOrProvince: ").append(toIndentedString(stateOrProvince)).append("\n");
    sb.append("    postalCode: ").append(toIndentedString(postalCode)).append("\n");
    sb.append("    city: ").append(toIndentedString(city)).append("\n");
    sb.append("    cadesConfig: ").append(toIndentedString(cadesConfig)).append("\n");
    sb.append("    padesConfig: ").append(toIndentedString(padesConfig)).append("\n");
    sb.append("    xadesConfig: ").append(toIndentedString(xadesConfig)).append("\n");
    sb.append("    operationId: ").append(toIndentedString(operationId)).append("\n");
    sb.append("    operationServer: ").append(toIndentedString(operationServer)).append("\n");
    sb.append("    timestampAlgorithm: ").append(toIndentedString(timestampAlgorithm)).append("\n");
    sb.append("    autoVerifyDisabled: ").append(toIndentedString(autoVerifyDisabled)).append("\n");
    sb.append("    autoVerifyError: ").append(toIndentedString(autoVerifyError)).append("\n");
    sb.append("    revocationRequestType: ").append(toIndentedString(revocationRequestType)).append("\n");
    sb.append("    fileName: ").append(toIndentedString(fileName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

