/*
 * Viafirma API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.3.29-r83-596fbc1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.openapitools.client.model.CertificateDTO;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ConfigTsaDTO
 */
@JsonPropertyOrder({
  ConfigTsaDTO.JSON_PROPERTY_TYPE,
  ConfigTsaDTO.JSON_PROPERTY_URL,
  ConfigTsaDTO.JSON_PROPERTY_USER,
  ConfigTsaDTO.JSON_PROPERTY_PASSWORD,
  ConfigTsaDTO.JSON_PROPERTY_POLICY_ID,
  ConfigTsaDTO.JSON_PROPERTY_LOCAL_CERT,
  ConfigTsaDTO.JSON_PROPERTY_TIMESTAMP_ALGORITHM,
  ConfigTsaDTO.JSON_PROPERTY_EXTENSION_OID,
  ConfigTsaDTO.JSON_PROPERTY_EXTENSION_VALUE,
  ConfigTsaDTO.JSON_PROPERTY_TSA_TYPE
})
@JsonTypeName("ConfigTsaDTO")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-03-04T11:20:43.685+01:00[Europe/Paris]")
public class ConfigTsaDTO {
  /**
   * Gets or Sets type
   */
  public enum TypeEnum {
    URL("URL"),
    
    USER("USER"),
    
    CERTIFICATE("CERTIFICATE"),
    
    CERTIFICATE_TLS("CERTIFICATE_TLS"),
    
    LOCAL("LOCAL");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_TYPE = "type";
  private TypeEnum type;

  public static final String JSON_PROPERTY_URL = "url";
  private String url;

  public static final String JSON_PROPERTY_USER = "user";
  private String user;

  public static final String JSON_PROPERTY_PASSWORD = "password";
  private String password;

  public static final String JSON_PROPERTY_POLICY_ID = "policyId";
  private String policyId;

  public static final String JSON_PROPERTY_LOCAL_CERT = "localCert";
  private CertificateDTO localCert;

  /**
   * Gets or Sets timestampAlgorithm
   */
  public enum TimestampAlgorithmEnum {
    SHA1("SHA1"),
    
    SHA224("SHA224"),
    
    SHA256("SHA256"),
    
    SHA384("SHA384"),
    
    SHA512("SHA512"),
    
    RIPEMD160("RIPEMD160"),
    
    MD2("MD2"),
    
    MD5("MD5");

    private String value;

    TimestampAlgorithmEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TimestampAlgorithmEnum fromValue(String value) {
      for (TimestampAlgorithmEnum b : TimestampAlgorithmEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_TIMESTAMP_ALGORITHM = "timestampAlgorithm";
  private TimestampAlgorithmEnum timestampAlgorithm;

  public static final String JSON_PROPERTY_EXTENSION_OID = "extensionOid";
  private String extensionOid;

  public static final String JSON_PROPERTY_EXTENSION_VALUE = "extensionValue";
  private String extensionValue;

  public static final String JSON_PROPERTY_TSA_TYPE = "tsaType";
  private Boolean tsaType;

  public ConfigTsaDTO() { 
  }

  public ConfigTsaDTO type(TypeEnum type) {
    
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public TypeEnum getType() {
    return type;
  }


  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setType(TypeEnum type) {
    this.type = type;
  }


  public ConfigTsaDTO url(String url) {
    
    this.url = url;
    return this;
  }

   /**
   * Get url
   * @return url
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUrl() {
    return url;
  }


  @JsonProperty(JSON_PROPERTY_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUrl(String url) {
    this.url = url;
  }


  public ConfigTsaDTO user(String user) {
    
    this.user = user;
    return this;
  }

   /**
   * Get user
   * @return user
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_USER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUser() {
    return user;
  }


  @JsonProperty(JSON_PROPERTY_USER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUser(String user) {
    this.user = user;
  }


  public ConfigTsaDTO password(String password) {
    
    this.password = password;
    return this;
  }

   /**
   * Get password
   * @return password
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_PASSWORD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPassword() {
    return password;
  }


  @JsonProperty(JSON_PROPERTY_PASSWORD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPassword(String password) {
    this.password = password;
  }


  public ConfigTsaDTO policyId(String policyId) {
    
    this.policyId = policyId;
    return this;
  }

   /**
   * Get policyId
   * @return policyId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_POLICY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPolicyId() {
    return policyId;
  }


  @JsonProperty(JSON_PROPERTY_POLICY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPolicyId(String policyId) {
    this.policyId = policyId;
  }


  public ConfigTsaDTO localCert(CertificateDTO localCert) {
    
    this.localCert = localCert;
    return this;
  }

   /**
   * Get localCert
   * @return localCert
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_LOCAL_CERT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public CertificateDTO getLocalCert() {
    return localCert;
  }


  @JsonProperty(JSON_PROPERTY_LOCAL_CERT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLocalCert(CertificateDTO localCert) {
    this.localCert = localCert;
  }


  public ConfigTsaDTO timestampAlgorithm(TimestampAlgorithmEnum timestampAlgorithm) {
    
    this.timestampAlgorithm = timestampAlgorithm;
    return this;
  }

   /**
   * Get timestampAlgorithm
   * @return timestampAlgorithm
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TIMESTAMP_ALGORITHM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public TimestampAlgorithmEnum getTimestampAlgorithm() {
    return timestampAlgorithm;
  }


  @JsonProperty(JSON_PROPERTY_TIMESTAMP_ALGORITHM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTimestampAlgorithm(TimestampAlgorithmEnum timestampAlgorithm) {
    this.timestampAlgorithm = timestampAlgorithm;
  }


  public ConfigTsaDTO extensionOid(String extensionOid) {
    
    this.extensionOid = extensionOid;
    return this;
  }

   /**
   * Get extensionOid
   * @return extensionOid
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_EXTENSION_OID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getExtensionOid() {
    return extensionOid;
  }


  @JsonProperty(JSON_PROPERTY_EXTENSION_OID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExtensionOid(String extensionOid) {
    this.extensionOid = extensionOid;
  }


  public ConfigTsaDTO extensionValue(String extensionValue) {
    
    this.extensionValue = extensionValue;
    return this;
  }

   /**
   * Get extensionValue
   * @return extensionValue
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_EXTENSION_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getExtensionValue() {
    return extensionValue;
  }


  @JsonProperty(JSON_PROPERTY_EXTENSION_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExtensionValue(String extensionValue) {
    this.extensionValue = extensionValue;
  }


  public ConfigTsaDTO tsaType(Boolean tsaType) {
    
    this.tsaType = tsaType;
    return this;
  }

   /**
   * Get tsaType
   * @return tsaType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TSA_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getTsaType() {
    return tsaType;
  }


  @JsonProperty(JSON_PROPERTY_TSA_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTsaType(Boolean tsaType) {
    this.tsaType = tsaType;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConfigTsaDTO configTsaDTO = (ConfigTsaDTO) o;
    return Objects.equals(this.type, configTsaDTO.type) &&
        Objects.equals(this.url, configTsaDTO.url) &&
        Objects.equals(this.user, configTsaDTO.user) &&
        Objects.equals(this.password, configTsaDTO.password) &&
        Objects.equals(this.policyId, configTsaDTO.policyId) &&
        Objects.equals(this.localCert, configTsaDTO.localCert) &&
        Objects.equals(this.timestampAlgorithm, configTsaDTO.timestampAlgorithm) &&
        Objects.equals(this.extensionOid, configTsaDTO.extensionOid) &&
        Objects.equals(this.extensionValue, configTsaDTO.extensionValue) &&
        Objects.equals(this.tsaType, configTsaDTO.tsaType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, url, user, password, policyId, localCert, timestampAlgorithm, extensionOid, extensionValue, tsaType);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConfigTsaDTO {\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    user: ").append(toIndentedString(user)).append("\n");
    sb.append("    password: ").append(toIndentedString(password)).append("\n");
    sb.append("    policyId: ").append(toIndentedString(policyId)).append("\n");
    sb.append("    localCert: ").append(toIndentedString(localCert)).append("\n");
    sb.append("    timestampAlgorithm: ").append(toIndentedString(timestampAlgorithm)).append("\n");
    sb.append("    extensionOid: ").append(toIndentedString(extensionOid)).append("\n");
    sb.append("    extensionValue: ").append(toIndentedString(extensionValue)).append("\n");
    sb.append("    tsaType: ").append(toIndentedString(tsaType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

