/*
 * Viafirma API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.3.29-r83-596fbc1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ConfigPolicyDTO
 */
@JsonPropertyOrder({
  ConfigPolicyDTO.JSON_PROPERTY_ID,
  ConfigPolicyDTO.JSON_PROPERTY_URL,
  ConfigPolicyDTO.JSON_PROPERTY_DESCRIPTION,
  ConfigPolicyDTO.JSON_PROPERTY_DIGEST_ALGORITHM,
  ConfigPolicyDTO.JSON_PROPERTY_DIGEST_VALUE,
  ConfigPolicyDTO.JSON_PROPERTY_CONTENT_HINTS_DESCRIPTION,
  ConfigPolicyDTO.JSON_PROPERTY_CONTENT_HINTS_TYPE
})
@JsonTypeName("ConfigPolicyDTO")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-03-04T11:20:43.685+01:00[Europe/Paris]")
public class ConfigPolicyDTO {
  public static final String JSON_PROPERTY_ID = "id";
  private String id;

  public static final String JSON_PROPERTY_URL = "url";
  private String url;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  private String description;

  /**
   * Gets or Sets digestAlgorithm
   */
  public enum DigestAlgorithmEnum {
    SHA1("SHA1"),
    
    SHA224("SHA224"),
    
    SHA256("SHA256"),
    
    SHA384("SHA384"),
    
    SHA512("SHA512"),
    
    RIPEMD160("RIPEMD160"),
    
    MD2("MD2"),
    
    MD5("MD5");

    private String value;

    DigestAlgorithmEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static DigestAlgorithmEnum fromValue(String value) {
      for (DigestAlgorithmEnum b : DigestAlgorithmEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_DIGEST_ALGORITHM = "digestAlgorithm";
  private DigestAlgorithmEnum digestAlgorithm;

  public static final String JSON_PROPERTY_DIGEST_VALUE = "digestValue";
  private byte[] digestValue;

  public static final String JSON_PROPERTY_CONTENT_HINTS_DESCRIPTION = "contentHintsDescription";
  private String contentHintsDescription;

  public static final String JSON_PROPERTY_CONTENT_HINTS_TYPE = "contentHintsType";
  private String contentHintsType;

  public ConfigPolicyDTO() { 
  }

  public ConfigPolicyDTO id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(String id) {
    this.id = id;
  }


  public ConfigPolicyDTO url(String url) {
    
    this.url = url;
    return this;
  }

   /**
   * Get url
   * @return url
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUrl() {
    return url;
  }


  @JsonProperty(JSON_PROPERTY_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUrl(String url) {
    this.url = url;
  }


  public ConfigPolicyDTO description(String description) {
    
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDescription() {
    return description;
  }


  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDescription(String description) {
    this.description = description;
  }


  public ConfigPolicyDTO digestAlgorithm(DigestAlgorithmEnum digestAlgorithm) {
    
    this.digestAlgorithm = digestAlgorithm;
    return this;
  }

   /**
   * Get digestAlgorithm
   * @return digestAlgorithm
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_DIGEST_ALGORITHM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public DigestAlgorithmEnum getDigestAlgorithm() {
    return digestAlgorithm;
  }


  @JsonProperty(JSON_PROPERTY_DIGEST_ALGORITHM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDigestAlgorithm(DigestAlgorithmEnum digestAlgorithm) {
    this.digestAlgorithm = digestAlgorithm;
  }


  public ConfigPolicyDTO digestValue(byte[] digestValue) {
    
    this.digestValue = digestValue;
    return this;
  }

   /**
   * Get digestValue
   * @return digestValue
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_DIGEST_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public byte[] getDigestValue() {
    return digestValue;
  }


  @JsonProperty(JSON_PROPERTY_DIGEST_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDigestValue(byte[] digestValue) {
    this.digestValue = digestValue;
  }


  public ConfigPolicyDTO contentHintsDescription(String contentHintsDescription) {
    
    this.contentHintsDescription = contentHintsDescription;
    return this;
  }

   /**
   * Get contentHintsDescription
   * @return contentHintsDescription
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CONTENT_HINTS_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getContentHintsDescription() {
    return contentHintsDescription;
  }


  @JsonProperty(JSON_PROPERTY_CONTENT_HINTS_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setContentHintsDescription(String contentHintsDescription) {
    this.contentHintsDescription = contentHintsDescription;
  }


  public ConfigPolicyDTO contentHintsType(String contentHintsType) {
    
    this.contentHintsType = contentHintsType;
    return this;
  }

   /**
   * Get contentHintsType
   * @return contentHintsType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CONTENT_HINTS_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getContentHintsType() {
    return contentHintsType;
  }


  @JsonProperty(JSON_PROPERTY_CONTENT_HINTS_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setContentHintsType(String contentHintsType) {
    this.contentHintsType = contentHintsType;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConfigPolicyDTO configPolicyDTO = (ConfigPolicyDTO) o;
    return Objects.equals(this.id, configPolicyDTO.id) &&
        Objects.equals(this.url, configPolicyDTO.url) &&
        Objects.equals(this.description, configPolicyDTO.description) &&
        Objects.equals(this.digestAlgorithm, configPolicyDTO.digestAlgorithm) &&
        Arrays.equals(this.digestValue, configPolicyDTO.digestValue) &&
        Objects.equals(this.contentHintsDescription, configPolicyDTO.contentHintsDescription) &&
        Objects.equals(this.contentHintsType, configPolicyDTO.contentHintsType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, url, description, digestAlgorithm, Arrays.hashCode(digestValue), contentHintsDescription, contentHintsType);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConfigPolicyDTO {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    digestAlgorithm: ").append(toIndentedString(digestAlgorithm)).append("\n");
    sb.append("    digestValue: ").append(toIndentedString(digestValue)).append("\n");
    sb.append("    contentHintsDescription: ").append(toIndentedString(contentHintsDescription)).append("\n");
    sb.append("    contentHintsType: ").append(toIndentedString(contentHintsType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

