/*
 * Viafirma API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.3.29-r83-596fbc1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ConfigXadesDTO
 */
@JsonPropertyOrder({
  ConfigXadesDTO.JSON_PROPERTY_SIGNED_INFO_CANONICALIZATION_METHOD,
  ConfigXadesDTO.JSON_PROPERTY_SIGNED_PROPERTIES_CANONICALIZATION_METHOD,
  ConfigXadesDTO.JSON_PROPERTY_TRUST_ANCHOR_B_P_POLICY,
  ConfigXadesDTO.JSON_PROPERTY_CLAIMED_SIGNER_ROLES,
  ConfigXadesDTO.JSON_PROPERTY_COMMITMENT_TYPE_INDICATION,
  ConfigXadesDTO.JSON_PROPERTY_TRANSFORM_ALGORITHMS,
  ConfigXadesDTO.JSON_PROPERTY_DSS_REFERENCE_URI,
  ConfigXadesDTO.JSON_PROPERTY_USE_SIGNING_CERTIFICATE_V2,
  ConfigXadesDTO.JSON_PROPERTY_MANIFEST_SIGNATURE,
  ConfigXadesDTO.JSON_PROPERTY_TO_COUNTER_SIGN_SIGNATURE_VALUE_ID,
  ConfigXadesDTO.JSON_PROPERTY_HASH_SIGNATURE,
  ConfigXadesDTO.JSON_PROPERTY_HASH_DIGEST_ALGORITHM,
  ConfigXadesDTO.JSON_PROPERTY_XPATH_LOCATION_STRING
})
@JsonTypeName("ConfigXadesDTO")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-03-04T11:20:43.685+01:00[Europe/Paris]")
public class ConfigXadesDTO {
  public static final String JSON_PROPERTY_SIGNED_INFO_CANONICALIZATION_METHOD = "signedInfoCanonicalizationMethod";
  private String signedInfoCanonicalizationMethod;

  public static final String JSON_PROPERTY_SIGNED_PROPERTIES_CANONICALIZATION_METHOD = "signedPropertiesCanonicalizationMethod";
  private String signedPropertiesCanonicalizationMethod;

  public static final String JSON_PROPERTY_TRUST_ANCHOR_B_P_POLICY = "trustAnchorBPPolicy";
  private Boolean trustAnchorBPPolicy;

  public static final String JSON_PROPERTY_CLAIMED_SIGNER_ROLES = "claimedSignerRoles";
  private List<String> claimedSignerRoles = null;

  public static final String JSON_PROPERTY_COMMITMENT_TYPE_INDICATION = "commitmentTypeIndication";
  private List<String> commitmentTypeIndication = null;

  public static final String JSON_PROPERTY_TRANSFORM_ALGORITHMS = "transformAlgorithms";
  private List<String> transformAlgorithms = null;

  public static final String JSON_PROPERTY_DSS_REFERENCE_URI = "dssReferenceUri";
  private String dssReferenceUri;

  public static final String JSON_PROPERTY_USE_SIGNING_CERTIFICATE_V2 = "useSigningCertificateV2";
  private Boolean useSigningCertificateV2;

  public static final String JSON_PROPERTY_MANIFEST_SIGNATURE = "manifestSignature";
  private Boolean manifestSignature;

  public static final String JSON_PROPERTY_TO_COUNTER_SIGN_SIGNATURE_VALUE_ID = "toCounterSignSignatureValueId";
  private String toCounterSignSignatureValueId;

  public static final String JSON_PROPERTY_HASH_SIGNATURE = "hashSignature";
  private Boolean hashSignature;

  /**
   * Gets or Sets hashDigestAlgorithm
   */
  public enum HashDigestAlgorithmEnum {
    SHA1("SHA1"),
    
    SHA224("SHA224"),
    
    SHA256("SHA256"),
    
    SHA384("SHA384"),
    
    SHA512("SHA512"),
    
    RIPEMD160("RIPEMD160"),
    
    MD2("MD2"),
    
    MD5("MD5");

    private String value;

    HashDigestAlgorithmEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static HashDigestAlgorithmEnum fromValue(String value) {
      for (HashDigestAlgorithmEnum b : HashDigestAlgorithmEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_HASH_DIGEST_ALGORITHM = "hashDigestAlgorithm";
  private HashDigestAlgorithmEnum hashDigestAlgorithm;

  public static final String JSON_PROPERTY_XPATH_LOCATION_STRING = "xpathLocationString";
  private String xpathLocationString;

  public ConfigXadesDTO() { 
  }

  public ConfigXadesDTO signedInfoCanonicalizationMethod(String signedInfoCanonicalizationMethod) {
    
    this.signedInfoCanonicalizationMethod = signedInfoCanonicalizationMethod;
    return this;
  }

   /**
   * Get signedInfoCanonicalizationMethod
   * @return signedInfoCanonicalizationMethod
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SIGNED_INFO_CANONICALIZATION_METHOD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSignedInfoCanonicalizationMethod() {
    return signedInfoCanonicalizationMethod;
  }


  @JsonProperty(JSON_PROPERTY_SIGNED_INFO_CANONICALIZATION_METHOD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSignedInfoCanonicalizationMethod(String signedInfoCanonicalizationMethod) {
    this.signedInfoCanonicalizationMethod = signedInfoCanonicalizationMethod;
  }


  public ConfigXadesDTO signedPropertiesCanonicalizationMethod(String signedPropertiesCanonicalizationMethod) {
    
    this.signedPropertiesCanonicalizationMethod = signedPropertiesCanonicalizationMethod;
    return this;
  }

   /**
   * Get signedPropertiesCanonicalizationMethod
   * @return signedPropertiesCanonicalizationMethod
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SIGNED_PROPERTIES_CANONICALIZATION_METHOD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSignedPropertiesCanonicalizationMethod() {
    return signedPropertiesCanonicalizationMethod;
  }


  @JsonProperty(JSON_PROPERTY_SIGNED_PROPERTIES_CANONICALIZATION_METHOD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSignedPropertiesCanonicalizationMethod(String signedPropertiesCanonicalizationMethod) {
    this.signedPropertiesCanonicalizationMethod = signedPropertiesCanonicalizationMethod;
  }


  public ConfigXadesDTO trustAnchorBPPolicy(Boolean trustAnchorBPPolicy) {
    
    this.trustAnchorBPPolicy = trustAnchorBPPolicy;
    return this;
  }

   /**
   * Get trustAnchorBPPolicy
   * @return trustAnchorBPPolicy
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TRUST_ANCHOR_B_P_POLICY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getTrustAnchorBPPolicy() {
    return trustAnchorBPPolicy;
  }


  @JsonProperty(JSON_PROPERTY_TRUST_ANCHOR_B_P_POLICY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTrustAnchorBPPolicy(Boolean trustAnchorBPPolicy) {
    this.trustAnchorBPPolicy = trustAnchorBPPolicy;
  }


  public ConfigXadesDTO claimedSignerRoles(List<String> claimedSignerRoles) {
    
    this.claimedSignerRoles = claimedSignerRoles;
    return this;
  }

  public ConfigXadesDTO addClaimedSignerRolesItem(String claimedSignerRolesItem) {
    if (this.claimedSignerRoles == null) {
      this.claimedSignerRoles = new ArrayList<>();
    }
    this.claimedSignerRoles.add(claimedSignerRolesItem);
    return this;
  }

   /**
   * Get claimedSignerRoles
   * @return claimedSignerRoles
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CLAIMED_SIGNER_ROLES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getClaimedSignerRoles() {
    return claimedSignerRoles;
  }


  @JsonProperty(JSON_PROPERTY_CLAIMED_SIGNER_ROLES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setClaimedSignerRoles(List<String> claimedSignerRoles) {
    this.claimedSignerRoles = claimedSignerRoles;
  }


  public ConfigXadesDTO commitmentTypeIndication(List<String> commitmentTypeIndication) {
    
    this.commitmentTypeIndication = commitmentTypeIndication;
    return this;
  }

  public ConfigXadesDTO addCommitmentTypeIndicationItem(String commitmentTypeIndicationItem) {
    if (this.commitmentTypeIndication == null) {
      this.commitmentTypeIndication = new ArrayList<>();
    }
    this.commitmentTypeIndication.add(commitmentTypeIndicationItem);
    return this;
  }

   /**
   * Get commitmentTypeIndication
   * @return commitmentTypeIndication
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_COMMITMENT_TYPE_INDICATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getCommitmentTypeIndication() {
    return commitmentTypeIndication;
  }


  @JsonProperty(JSON_PROPERTY_COMMITMENT_TYPE_INDICATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCommitmentTypeIndication(List<String> commitmentTypeIndication) {
    this.commitmentTypeIndication = commitmentTypeIndication;
  }


  public ConfigXadesDTO transformAlgorithms(List<String> transformAlgorithms) {
    
    this.transformAlgorithms = transformAlgorithms;
    return this;
  }

  public ConfigXadesDTO addTransformAlgorithmsItem(String transformAlgorithmsItem) {
    if (this.transformAlgorithms == null) {
      this.transformAlgorithms = new ArrayList<>();
    }
    this.transformAlgorithms.add(transformAlgorithmsItem);
    return this;
  }

   /**
   * Get transformAlgorithms
   * @return transformAlgorithms
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TRANSFORM_ALGORITHMS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getTransformAlgorithms() {
    return transformAlgorithms;
  }


  @JsonProperty(JSON_PROPERTY_TRANSFORM_ALGORITHMS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTransformAlgorithms(List<String> transformAlgorithms) {
    this.transformAlgorithms = transformAlgorithms;
  }


  public ConfigXadesDTO dssReferenceUri(String dssReferenceUri) {
    
    this.dssReferenceUri = dssReferenceUri;
    return this;
  }

   /**
   * Get dssReferenceUri
   * @return dssReferenceUri
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_DSS_REFERENCE_URI)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDssReferenceUri() {
    return dssReferenceUri;
  }


  @JsonProperty(JSON_PROPERTY_DSS_REFERENCE_URI)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDssReferenceUri(String dssReferenceUri) {
    this.dssReferenceUri = dssReferenceUri;
  }


  public ConfigXadesDTO useSigningCertificateV2(Boolean useSigningCertificateV2) {
    
    this.useSigningCertificateV2 = useSigningCertificateV2;
    return this;
  }

   /**
   * Get useSigningCertificateV2
   * @return useSigningCertificateV2
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_USE_SIGNING_CERTIFICATE_V2)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getUseSigningCertificateV2() {
    return useSigningCertificateV2;
  }


  @JsonProperty(JSON_PROPERTY_USE_SIGNING_CERTIFICATE_V2)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUseSigningCertificateV2(Boolean useSigningCertificateV2) {
    this.useSigningCertificateV2 = useSigningCertificateV2;
  }


  public ConfigXadesDTO manifestSignature(Boolean manifestSignature) {
    
    this.manifestSignature = manifestSignature;
    return this;
  }

   /**
   * Get manifestSignature
   * @return manifestSignature
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_MANIFEST_SIGNATURE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getManifestSignature() {
    return manifestSignature;
  }


  @JsonProperty(JSON_PROPERTY_MANIFEST_SIGNATURE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setManifestSignature(Boolean manifestSignature) {
    this.manifestSignature = manifestSignature;
  }


  public ConfigXadesDTO toCounterSignSignatureValueId(String toCounterSignSignatureValueId) {
    
    this.toCounterSignSignatureValueId = toCounterSignSignatureValueId;
    return this;
  }

   /**
   * Get toCounterSignSignatureValueId
   * @return toCounterSignSignatureValueId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TO_COUNTER_SIGN_SIGNATURE_VALUE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getToCounterSignSignatureValueId() {
    return toCounterSignSignatureValueId;
  }


  @JsonProperty(JSON_PROPERTY_TO_COUNTER_SIGN_SIGNATURE_VALUE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setToCounterSignSignatureValueId(String toCounterSignSignatureValueId) {
    this.toCounterSignSignatureValueId = toCounterSignSignatureValueId;
  }


  public ConfigXadesDTO hashSignature(Boolean hashSignature) {
    
    this.hashSignature = hashSignature;
    return this;
  }

   /**
   * Get hashSignature
   * @return hashSignature
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_HASH_SIGNATURE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getHashSignature() {
    return hashSignature;
  }


  @JsonProperty(JSON_PROPERTY_HASH_SIGNATURE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHashSignature(Boolean hashSignature) {
    this.hashSignature = hashSignature;
  }


  public ConfigXadesDTO hashDigestAlgorithm(HashDigestAlgorithmEnum hashDigestAlgorithm) {
    
    this.hashDigestAlgorithm = hashDigestAlgorithm;
    return this;
  }

   /**
   * Get hashDigestAlgorithm
   * @return hashDigestAlgorithm
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_HASH_DIGEST_ALGORITHM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public HashDigestAlgorithmEnum getHashDigestAlgorithm() {
    return hashDigestAlgorithm;
  }


  @JsonProperty(JSON_PROPERTY_HASH_DIGEST_ALGORITHM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHashDigestAlgorithm(HashDigestAlgorithmEnum hashDigestAlgorithm) {
    this.hashDigestAlgorithm = hashDigestAlgorithm;
  }


  public ConfigXadesDTO xpathLocationString(String xpathLocationString) {
    
    this.xpathLocationString = xpathLocationString;
    return this;
  }

   /**
   * Get xpathLocationString
   * @return xpathLocationString
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_XPATH_LOCATION_STRING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getXpathLocationString() {
    return xpathLocationString;
  }


  @JsonProperty(JSON_PROPERTY_XPATH_LOCATION_STRING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setXpathLocationString(String xpathLocationString) {
    this.xpathLocationString = xpathLocationString;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConfigXadesDTO configXadesDTO = (ConfigXadesDTO) o;
    return Objects.equals(this.signedInfoCanonicalizationMethod, configXadesDTO.signedInfoCanonicalizationMethod) &&
        Objects.equals(this.signedPropertiesCanonicalizationMethod, configXadesDTO.signedPropertiesCanonicalizationMethod) &&
        Objects.equals(this.trustAnchorBPPolicy, configXadesDTO.trustAnchorBPPolicy) &&
        Objects.equals(this.claimedSignerRoles, configXadesDTO.claimedSignerRoles) &&
        Objects.equals(this.commitmentTypeIndication, configXadesDTO.commitmentTypeIndication) &&
        Objects.equals(this.transformAlgorithms, configXadesDTO.transformAlgorithms) &&
        Objects.equals(this.dssReferenceUri, configXadesDTO.dssReferenceUri) &&
        Objects.equals(this.useSigningCertificateV2, configXadesDTO.useSigningCertificateV2) &&
        Objects.equals(this.manifestSignature, configXadesDTO.manifestSignature) &&
        Objects.equals(this.toCounterSignSignatureValueId, configXadesDTO.toCounterSignSignatureValueId) &&
        Objects.equals(this.hashSignature, configXadesDTO.hashSignature) &&
        Objects.equals(this.hashDigestAlgorithm, configXadesDTO.hashDigestAlgorithm) &&
        Objects.equals(this.xpathLocationString, configXadesDTO.xpathLocationString);
  }

  @Override
  public int hashCode() {
    return Objects.hash(signedInfoCanonicalizationMethod, signedPropertiesCanonicalizationMethod, trustAnchorBPPolicy, claimedSignerRoles, commitmentTypeIndication, transformAlgorithms, dssReferenceUri, useSigningCertificateV2, manifestSignature, toCounterSignSignatureValueId, hashSignature, hashDigestAlgorithm, xpathLocationString);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConfigXadesDTO {\n");
    sb.append("    signedInfoCanonicalizationMethod: ").append(toIndentedString(signedInfoCanonicalizationMethod)).append("\n");
    sb.append("    signedPropertiesCanonicalizationMethod: ").append(toIndentedString(signedPropertiesCanonicalizationMethod)).append("\n");
    sb.append("    trustAnchorBPPolicy: ").append(toIndentedString(trustAnchorBPPolicy)).append("\n");
    sb.append("    claimedSignerRoles: ").append(toIndentedString(claimedSignerRoles)).append("\n");
    sb.append("    commitmentTypeIndication: ").append(toIndentedString(commitmentTypeIndication)).append("\n");
    sb.append("    transformAlgorithms: ").append(toIndentedString(transformAlgorithms)).append("\n");
    sb.append("    dssReferenceUri: ").append(toIndentedString(dssReferenceUri)).append("\n");
    sb.append("    useSigningCertificateV2: ").append(toIndentedString(useSigningCertificateV2)).append("\n");
    sb.append("    manifestSignature: ").append(toIndentedString(manifestSignature)).append("\n");
    sb.append("    toCounterSignSignatureValueId: ").append(toIndentedString(toCounterSignSignatureValueId)).append("\n");
    sb.append("    hashSignature: ").append(toIndentedString(hashSignature)).append("\n");
    sb.append("    hashDigestAlgorithm: ").append(toIndentedString(hashDigestAlgorithm)).append("\n");
    sb.append("    xpathLocationString: ").append(toIndentedString(xpathLocationString)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

