/*
 * Viafirma API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.3.29-r83-596fbc1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.openapitools.client.model.CertificateFilterDTO;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ConfigCertificateRequestDTO
 */
@JsonPropertyOrder({
  ConfigCertificateRequestDTO.JSON_PROPERTY_AUTO_SEND,
  ConfigCertificateRequestDTO.JSON_PROPERTY_DISCARD_EXPIRED_CERTIFICATES,
  ConfigCertificateRequestDTO.JSON_PROPERTY_CERTIFICATE_BY_FILTER,
  ConfigCertificateRequestDTO.JSON_PROPERTY_GENERIC_FILTER,
  ConfigCertificateRequestDTO.JSON_PROPERTY_CERT_FILTER,
  ConfigCertificateRequestDTO.JSON_PROPERTY_CA_FILTER,
  ConfigCertificateRequestDTO.JSON_PROPERTY_NATIONAL_ID_FILTER
})
@JsonTypeName("ConfigCertificateRequestDTO")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-03-04T11:20:43.685+01:00[Europe/Paris]")
public class ConfigCertificateRequestDTO {
  public static final String JSON_PROPERTY_AUTO_SEND = "autoSend";
  private Boolean autoSend;

  public static final String JSON_PROPERTY_DISCARD_EXPIRED_CERTIFICATES = "discardExpiredCertificates";
  private Boolean discardExpiredCertificates;

  public static final String JSON_PROPERTY_CERTIFICATE_BY_FILTER = "certificateByFilter";
  private String certificateByFilter;

  public static final String JSON_PROPERTY_GENERIC_FILTER = "genericFilter";
  private String genericFilter;

  public static final String JSON_PROPERTY_CERT_FILTER = "certFilter";
  private CertificateFilterDTO certFilter;

  public static final String JSON_PROPERTY_CA_FILTER = "caFilter";
  private CertificateFilterDTO caFilter;

  public static final String JSON_PROPERTY_NATIONAL_ID_FILTER = "nationalIdFilter";
  private CertificateFilterDTO nationalIdFilter;

  public ConfigCertificateRequestDTO() { 
  }

  public ConfigCertificateRequestDTO autoSend(Boolean autoSend) {
    
    this.autoSend = autoSend;
    return this;
  }

   /**
   * Get autoSend
   * @return autoSend
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_AUTO_SEND)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getAutoSend() {
    return autoSend;
  }


  @JsonProperty(JSON_PROPERTY_AUTO_SEND)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAutoSend(Boolean autoSend) {
    this.autoSend = autoSend;
  }


  public ConfigCertificateRequestDTO discardExpiredCertificates(Boolean discardExpiredCertificates) {
    
    this.discardExpiredCertificates = discardExpiredCertificates;
    return this;
  }

   /**
   * Get discardExpiredCertificates
   * @return discardExpiredCertificates
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_DISCARD_EXPIRED_CERTIFICATES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getDiscardExpiredCertificates() {
    return discardExpiredCertificates;
  }


  @JsonProperty(JSON_PROPERTY_DISCARD_EXPIRED_CERTIFICATES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDiscardExpiredCertificates(Boolean discardExpiredCertificates) {
    this.discardExpiredCertificates = discardExpiredCertificates;
  }


  public ConfigCertificateRequestDTO certificateByFilter(String certificateByFilter) {
    
    this.certificateByFilter = certificateByFilter;
    return this;
  }

   /**
   * Get certificateByFilter
   * @return certificateByFilter
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CERTIFICATE_BY_FILTER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCertificateByFilter() {
    return certificateByFilter;
  }


  @JsonProperty(JSON_PROPERTY_CERTIFICATE_BY_FILTER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCertificateByFilter(String certificateByFilter) {
    this.certificateByFilter = certificateByFilter;
  }


  public ConfigCertificateRequestDTO genericFilter(String genericFilter) {
    
    this.genericFilter = genericFilter;
    return this;
  }

   /**
   * Get genericFilter
   * @return genericFilter
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_GENERIC_FILTER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getGenericFilter() {
    return genericFilter;
  }


  @JsonProperty(JSON_PROPERTY_GENERIC_FILTER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setGenericFilter(String genericFilter) {
    this.genericFilter = genericFilter;
  }


  public ConfigCertificateRequestDTO certFilter(CertificateFilterDTO certFilter) {
    
    this.certFilter = certFilter;
    return this;
  }

   /**
   * Get certFilter
   * @return certFilter
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CERT_FILTER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public CertificateFilterDTO getCertFilter() {
    return certFilter;
  }


  @JsonProperty(JSON_PROPERTY_CERT_FILTER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCertFilter(CertificateFilterDTO certFilter) {
    this.certFilter = certFilter;
  }


  public ConfigCertificateRequestDTO caFilter(CertificateFilterDTO caFilter) {
    
    this.caFilter = caFilter;
    return this;
  }

   /**
   * Get caFilter
   * @return caFilter
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CA_FILTER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public CertificateFilterDTO getCaFilter() {
    return caFilter;
  }


  @JsonProperty(JSON_PROPERTY_CA_FILTER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCaFilter(CertificateFilterDTO caFilter) {
    this.caFilter = caFilter;
  }


  public ConfigCertificateRequestDTO nationalIdFilter(CertificateFilterDTO nationalIdFilter) {
    
    this.nationalIdFilter = nationalIdFilter;
    return this;
  }

   /**
   * Get nationalIdFilter
   * @return nationalIdFilter
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_NATIONAL_ID_FILTER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public CertificateFilterDTO getNationalIdFilter() {
    return nationalIdFilter;
  }


  @JsonProperty(JSON_PROPERTY_NATIONAL_ID_FILTER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNationalIdFilter(CertificateFilterDTO nationalIdFilter) {
    this.nationalIdFilter = nationalIdFilter;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConfigCertificateRequestDTO configCertificateRequestDTO = (ConfigCertificateRequestDTO) o;
    return Objects.equals(this.autoSend, configCertificateRequestDTO.autoSend) &&
        Objects.equals(this.discardExpiredCertificates, configCertificateRequestDTO.discardExpiredCertificates) &&
        Objects.equals(this.certificateByFilter, configCertificateRequestDTO.certificateByFilter) &&
        Objects.equals(this.genericFilter, configCertificateRequestDTO.genericFilter) &&
        Objects.equals(this.certFilter, configCertificateRequestDTO.certFilter) &&
        Objects.equals(this.caFilter, configCertificateRequestDTO.caFilter) &&
        Objects.equals(this.nationalIdFilter, configCertificateRequestDTO.nationalIdFilter);
  }

  @Override
  public int hashCode() {
    return Objects.hash(autoSend, discardExpiredCertificates, certificateByFilter, genericFilter, certFilter, caFilter, nationalIdFilter);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConfigCertificateRequestDTO {\n");
    sb.append("    autoSend: ").append(toIndentedString(autoSend)).append("\n");
    sb.append("    discardExpiredCertificates: ").append(toIndentedString(discardExpiredCertificates)).append("\n");
    sb.append("    certificateByFilter: ").append(toIndentedString(certificateByFilter)).append("\n");
    sb.append("    genericFilter: ").append(toIndentedString(genericFilter)).append("\n");
    sb.append("    certFilter: ").append(toIndentedString(certFilter)).append("\n");
    sb.append("    caFilter: ").append(toIndentedString(caFilter)).append("\n");
    sb.append("    nationalIdFilter: ").append(toIndentedString(nationalIdFilter)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

