/*
 * Viafirma API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.3.29-r83-596fbc1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * EvidenceDeviceDTO
 */
@JsonPropertyOrder({
  EvidenceDeviceDTO.JSON_PROPERTY_MANUFACTURER,
  EvidenceDeviceDTO.JSON_PROPERTY_APP,
  EvidenceDeviceDTO.JSON_PROPERTY_MODEL,
  EvidenceDeviceDTO.JSON_PROPERTY_OS_VERSION,
  EvidenceDeviceDTO.JSON_PROPERTY_PEN_TYPE,
  EvidenceDeviceDTO.JSON_PROPERTY_AREA_HEIGHT,
  EvidenceDeviceDTO.JSON_PROPERTY_AREA_WIDTH,
  EvidenceDeviceDTO.JSON_PROPERTY_PPI,
  EvidenceDeviceDTO.JSON_PROPERTY_ROTATION_ALLOWED,
  EvidenceDeviceDTO.JSON_PROPERTY_MIN_PRESSURE,
  EvidenceDeviceDTO.JSON_PROPERTY_MAX_PRESSURE,
  EvidenceDeviceDTO.JSON_PROPERTY_SCREEN_HEIGHT,
  EvidenceDeviceDTO.JSON_PROPERTY_SCREEN_WIDTH,
  EvidenceDeviceDTO.JSON_PROPERTY_IP
})
@JsonTypeName("EvidenceDeviceDTO")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-03-04T11:20:43.685+01:00[Europe/Paris]")
public class EvidenceDeviceDTO {
  public static final String JSON_PROPERTY_MANUFACTURER = "manufacturer";
  private String manufacturer;

  public static final String JSON_PROPERTY_APP = "app";
  private String app;

  public static final String JSON_PROPERTY_MODEL = "model";
  private String model;

  public static final String JSON_PROPERTY_OS_VERSION = "osVersion";
  private String osVersion;

  public static final String JSON_PROPERTY_PEN_TYPE = "penType";
  private String penType;

  public static final String JSON_PROPERTY_AREA_HEIGHT = "areaHeight";
  private Integer areaHeight;

  public static final String JSON_PROPERTY_AREA_WIDTH = "areaWidth";
  private Integer areaWidth;

  public static final String JSON_PROPERTY_PPI = "ppi";
  private String ppi;

  public static final String JSON_PROPERTY_ROTATION_ALLOWED = "rotationAllowed";
  private Boolean rotationAllowed;

  public static final String JSON_PROPERTY_MIN_PRESSURE = "minPressure";
  private Double minPressure;

  public static final String JSON_PROPERTY_MAX_PRESSURE = "maxPressure";
  private Double maxPressure;

  public static final String JSON_PROPERTY_SCREEN_HEIGHT = "screenHeight";
  private Integer screenHeight;

  public static final String JSON_PROPERTY_SCREEN_WIDTH = "screenWidth";
  private Integer screenWidth;

  public static final String JSON_PROPERTY_IP = "ip";
  private String ip;

  public EvidenceDeviceDTO() { 
  }

  public EvidenceDeviceDTO manufacturer(String manufacturer) {
    
    this.manufacturer = manufacturer;
    return this;
  }

   /**
   * Get manufacturer
   * @return manufacturer
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_MANUFACTURER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getManufacturer() {
    return manufacturer;
  }


  @JsonProperty(JSON_PROPERTY_MANUFACTURER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setManufacturer(String manufacturer) {
    this.manufacturer = manufacturer;
  }


  public EvidenceDeviceDTO app(String app) {
    
    this.app = app;
    return this;
  }

   /**
   * Get app
   * @return app
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_APP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getApp() {
    return app;
  }


  @JsonProperty(JSON_PROPERTY_APP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setApp(String app) {
    this.app = app;
  }


  public EvidenceDeviceDTO model(String model) {
    
    this.model = model;
    return this;
  }

   /**
   * Get model
   * @return model
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_MODEL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getModel() {
    return model;
  }


  @JsonProperty(JSON_PROPERTY_MODEL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setModel(String model) {
    this.model = model;
  }


  public EvidenceDeviceDTO osVersion(String osVersion) {
    
    this.osVersion = osVersion;
    return this;
  }

   /**
   * Get osVersion
   * @return osVersion
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_OS_VERSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getOsVersion() {
    return osVersion;
  }


  @JsonProperty(JSON_PROPERTY_OS_VERSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOsVersion(String osVersion) {
    this.osVersion = osVersion;
  }


  public EvidenceDeviceDTO penType(String penType) {
    
    this.penType = penType;
    return this;
  }

   /**
   * Get penType
   * @return penType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_PEN_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPenType() {
    return penType;
  }


  @JsonProperty(JSON_PROPERTY_PEN_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPenType(String penType) {
    this.penType = penType;
  }


  public EvidenceDeviceDTO areaHeight(Integer areaHeight) {
    
    this.areaHeight = areaHeight;
    return this;
  }

   /**
   * Get areaHeight
   * @return areaHeight
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_AREA_HEIGHT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getAreaHeight() {
    return areaHeight;
  }


  @JsonProperty(JSON_PROPERTY_AREA_HEIGHT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAreaHeight(Integer areaHeight) {
    this.areaHeight = areaHeight;
  }


  public EvidenceDeviceDTO areaWidth(Integer areaWidth) {
    
    this.areaWidth = areaWidth;
    return this;
  }

   /**
   * Get areaWidth
   * @return areaWidth
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_AREA_WIDTH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getAreaWidth() {
    return areaWidth;
  }


  @JsonProperty(JSON_PROPERTY_AREA_WIDTH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAreaWidth(Integer areaWidth) {
    this.areaWidth = areaWidth;
  }


  public EvidenceDeviceDTO ppi(String ppi) {
    
    this.ppi = ppi;
    return this;
  }

   /**
   * Get ppi
   * @return ppi
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_PPI)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPpi() {
    return ppi;
  }


  @JsonProperty(JSON_PROPERTY_PPI)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPpi(String ppi) {
    this.ppi = ppi;
  }


  public EvidenceDeviceDTO rotationAllowed(Boolean rotationAllowed) {
    
    this.rotationAllowed = rotationAllowed;
    return this;
  }

   /**
   * Get rotationAllowed
   * @return rotationAllowed
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ROTATION_ALLOWED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getRotationAllowed() {
    return rotationAllowed;
  }


  @JsonProperty(JSON_PROPERTY_ROTATION_ALLOWED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRotationAllowed(Boolean rotationAllowed) {
    this.rotationAllowed = rotationAllowed;
  }


  public EvidenceDeviceDTO minPressure(Double minPressure) {
    
    this.minPressure = minPressure;
    return this;
  }

   /**
   * Get minPressure
   * @return minPressure
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_MIN_PRESSURE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getMinPressure() {
    return minPressure;
  }


  @JsonProperty(JSON_PROPERTY_MIN_PRESSURE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMinPressure(Double minPressure) {
    this.minPressure = minPressure;
  }


  public EvidenceDeviceDTO maxPressure(Double maxPressure) {
    
    this.maxPressure = maxPressure;
    return this;
  }

   /**
   * Get maxPressure
   * @return maxPressure
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_MAX_PRESSURE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getMaxPressure() {
    return maxPressure;
  }


  @JsonProperty(JSON_PROPERTY_MAX_PRESSURE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMaxPressure(Double maxPressure) {
    this.maxPressure = maxPressure;
  }


  public EvidenceDeviceDTO screenHeight(Integer screenHeight) {
    
    this.screenHeight = screenHeight;
    return this;
  }

   /**
   * Get screenHeight
   * @return screenHeight
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SCREEN_HEIGHT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getScreenHeight() {
    return screenHeight;
  }


  @JsonProperty(JSON_PROPERTY_SCREEN_HEIGHT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setScreenHeight(Integer screenHeight) {
    this.screenHeight = screenHeight;
  }


  public EvidenceDeviceDTO screenWidth(Integer screenWidth) {
    
    this.screenWidth = screenWidth;
    return this;
  }

   /**
   * Get screenWidth
   * @return screenWidth
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SCREEN_WIDTH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getScreenWidth() {
    return screenWidth;
  }


  @JsonProperty(JSON_PROPERTY_SCREEN_WIDTH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setScreenWidth(Integer screenWidth) {
    this.screenWidth = screenWidth;
  }


  public EvidenceDeviceDTO ip(String ip) {
    
    this.ip = ip;
    return this;
  }

   /**
   * Get ip
   * @return ip
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_IP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getIp() {
    return ip;
  }


  @JsonProperty(JSON_PROPERTY_IP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIp(String ip) {
    this.ip = ip;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EvidenceDeviceDTO evidenceDeviceDTO = (EvidenceDeviceDTO) o;
    return Objects.equals(this.manufacturer, evidenceDeviceDTO.manufacturer) &&
        Objects.equals(this.app, evidenceDeviceDTO.app) &&
        Objects.equals(this.model, evidenceDeviceDTO.model) &&
        Objects.equals(this.osVersion, evidenceDeviceDTO.osVersion) &&
        Objects.equals(this.penType, evidenceDeviceDTO.penType) &&
        Objects.equals(this.areaHeight, evidenceDeviceDTO.areaHeight) &&
        Objects.equals(this.areaWidth, evidenceDeviceDTO.areaWidth) &&
        Objects.equals(this.ppi, evidenceDeviceDTO.ppi) &&
        Objects.equals(this.rotationAllowed, evidenceDeviceDTO.rotationAllowed) &&
        Objects.equals(this.minPressure, evidenceDeviceDTO.minPressure) &&
        Objects.equals(this.maxPressure, evidenceDeviceDTO.maxPressure) &&
        Objects.equals(this.screenHeight, evidenceDeviceDTO.screenHeight) &&
        Objects.equals(this.screenWidth, evidenceDeviceDTO.screenWidth) &&
        Objects.equals(this.ip, evidenceDeviceDTO.ip);
  }

  @Override
  public int hashCode() {
    return Objects.hash(manufacturer, app, model, osVersion, penType, areaHeight, areaWidth, ppi, rotationAllowed, minPressure, maxPressure, screenHeight, screenWidth, ip);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EvidenceDeviceDTO {\n");
    sb.append("    manufacturer: ").append(toIndentedString(manufacturer)).append("\n");
    sb.append("    app: ").append(toIndentedString(app)).append("\n");
    sb.append("    model: ").append(toIndentedString(model)).append("\n");
    sb.append("    osVersion: ").append(toIndentedString(osVersion)).append("\n");
    sb.append("    penType: ").append(toIndentedString(penType)).append("\n");
    sb.append("    areaHeight: ").append(toIndentedString(areaHeight)).append("\n");
    sb.append("    areaWidth: ").append(toIndentedString(areaWidth)).append("\n");
    sb.append("    ppi: ").append(toIndentedString(ppi)).append("\n");
    sb.append("    rotationAllowed: ").append(toIndentedString(rotationAllowed)).append("\n");
    sb.append("    minPressure: ").append(toIndentedString(minPressure)).append("\n");
    sb.append("    maxPressure: ").append(toIndentedString(maxPressure)).append("\n");
    sb.append("    screenHeight: ").append(toIndentedString(screenHeight)).append("\n");
    sb.append("    screenWidth: ").append(toIndentedString(screenWidth)).append("\n");
    sb.append("    ip: ").append(toIndentedString(ip)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

