/*
 * Viafirma API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.3.29-r83-596fbc1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * FileReferenceResponseDTO
 */
@JsonPropertyOrder({
  FileReferenceResponseDTO.JSON_PROPERTY_REFERENCE,
  FileReferenceResponseDTO.JSON_PROPERTY_EXPIRES
})
@JsonTypeName("FileReferenceResponseDTO")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-03-04T11:20:43.685+01:00[Europe/Paris]")
public class FileReferenceResponseDTO {
  public static final String JSON_PROPERTY_REFERENCE = "reference";
  private String reference;

  public static final String JSON_PROPERTY_EXPIRES = "expires";
  private Long expires;

  public FileReferenceResponseDTO() { 
  }

  public FileReferenceResponseDTO reference(String reference) {
    
    this.reference = reference;
    return this;
  }

   /**
   * UUID that allows this file to be referenced in other services
   * @return reference
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "b2e20d7d-09e2-4ce7-b94e-b0deb2d97ce9_document.pdf", required = true, value = "UUID that allows this file to be referenced in other services")
  @JsonProperty(JSON_PROPERTY_REFERENCE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getReference() {
    return reference;
  }


  @JsonProperty(JSON_PROPERTY_REFERENCE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setReference(String reference) {
    this.reference = reference;
  }


  public FileReferenceResponseDTO expires(Long expires) {
    
    this.expires = expires;
    return this;
  }

   /**
   * From this date the document will no longer be available
   * @return expires
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "1617235200000", required = true, value = "From this date the document will no longer be available")
  @JsonProperty(JSON_PROPERTY_EXPIRES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getExpires() {
    return expires;
  }


  @JsonProperty(JSON_PROPERTY_EXPIRES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setExpires(Long expires) {
    this.expires = expires;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FileReferenceResponseDTO fileReferenceResponseDTO = (FileReferenceResponseDTO) o;
    return Objects.equals(this.reference, fileReferenceResponseDTO.reference) &&
        Objects.equals(this.expires, fileReferenceResponseDTO.expires);
  }

  @Override
  public int hashCode() {
    return Objects.hash(reference, expires);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FileReferenceResponseDTO {\n");
    sb.append("    reference: ").append(toIndentedString(reference)).append("\n");
    sb.append("    expires: ").append(toIndentedString(expires)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

