/*
 * Viafirma API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.3.29-r83-596fbc1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * FortressConfigurationDTO
 */
@JsonPropertyOrder({
  FortressConfigurationDTO.JSON_PROPERTY_SERVICE_URL,
  FortressConfigurationDTO.JSON_PROPERTY_SERVICE_REDIRECT_URI,
  FortressConfigurationDTO.JSON_PROPERTY_CLIENT_ID,
  FortressConfigurationDTO.JSON_PROPERTY_CLIENT_SECRET
})
@JsonTypeName("FortressConfigurationDTO")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-03-04T11:20:43.685+01:00[Europe/Paris]")
public class FortressConfigurationDTO {
  public static final String JSON_PROPERTY_SERVICE_URL = "serviceUrl";
  private String serviceUrl;

  public static final String JSON_PROPERTY_SERVICE_REDIRECT_URI = "serviceRedirectUri";
  private String serviceRedirectUri;

  public static final String JSON_PROPERTY_CLIENT_ID = "clientId";
  private String clientId;

  public static final String JSON_PROPERTY_CLIENT_SECRET = "clientSecret";
  private String clientSecret;

  public FortressConfigurationDTO() { 
  }

  public FortressConfigurationDTO serviceUrl(String serviceUrl) {
    
    this.serviceUrl = serviceUrl;
    return this;
  }

   /**
   * Get serviceUrl
   * @return serviceUrl
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SERVICE_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getServiceUrl() {
    return serviceUrl;
  }


  @JsonProperty(JSON_PROPERTY_SERVICE_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setServiceUrl(String serviceUrl) {
    this.serviceUrl = serviceUrl;
  }


  public FortressConfigurationDTO serviceRedirectUri(String serviceRedirectUri) {
    
    this.serviceRedirectUri = serviceRedirectUri;
    return this;
  }

   /**
   * Get serviceRedirectUri
   * @return serviceRedirectUri
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SERVICE_REDIRECT_URI)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getServiceRedirectUri() {
    return serviceRedirectUri;
  }


  @JsonProperty(JSON_PROPERTY_SERVICE_REDIRECT_URI)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setServiceRedirectUri(String serviceRedirectUri) {
    this.serviceRedirectUri = serviceRedirectUri;
  }


  public FortressConfigurationDTO clientId(String clientId) {
    
    this.clientId = clientId;
    return this;
  }

   /**
   * Get clientId
   * @return clientId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CLIENT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getClientId() {
    return clientId;
  }


  @JsonProperty(JSON_PROPERTY_CLIENT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setClientId(String clientId) {
    this.clientId = clientId;
  }


  public FortressConfigurationDTO clientSecret(String clientSecret) {
    
    this.clientSecret = clientSecret;
    return this;
  }

   /**
   * Get clientSecret
   * @return clientSecret
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CLIENT_SECRET)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getClientSecret() {
    return clientSecret;
  }


  @JsonProperty(JSON_PROPERTY_CLIENT_SECRET)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setClientSecret(String clientSecret) {
    this.clientSecret = clientSecret;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FortressConfigurationDTO fortressConfigurationDTO = (FortressConfigurationDTO) o;
    return Objects.equals(this.serviceUrl, fortressConfigurationDTO.serviceUrl) &&
        Objects.equals(this.serviceRedirectUri, fortressConfigurationDTO.serviceRedirectUri) &&
        Objects.equals(this.clientId, fortressConfigurationDTO.clientId) &&
        Objects.equals(this.clientSecret, fortressConfigurationDTO.clientSecret);
  }

  @Override
  public int hashCode() {
    return Objects.hash(serviceUrl, serviceRedirectUri, clientId, clientSecret);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FortressConfigurationDTO {\n");
    sb.append("    serviceUrl: ").append(toIndentedString(serviceUrl)).append("\n");
    sb.append("    serviceRedirectUri: ").append(toIndentedString(serviceRedirectUri)).append("\n");
    sb.append("    clientId: ").append(toIndentedString(clientId)).append("\n");
    sb.append("    clientSecret: ").append(toIndentedString(clientSecret)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

