/*
 * Viafirma API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.3.29-r83-596fbc1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * OperationStatusDTO
 */
@JsonPropertyOrder({
  OperationStatusDTO.JSON_PROPERTY_DOCUMENT_ID,
  OperationStatusDTO.JSON_PROPERTY_STATUS,
  OperationStatusDTO.JSON_PROPERTY_STATUS_REASON,
  OperationStatusDTO.JSON_PROPERTY_SOURCE_LINK,
  OperationStatusDTO.JSON_PROPERTY_SIGNED_LINK,
  OperationStatusDTO.JSON_PROPERTY_TRAIL,
  OperationStatusDTO.JSON_PROPERTY_FILE_NAME,
  OperationStatusDTO.JSON_PROPERTY_SOURCE_ID
})
@JsonTypeName("OperationStatusDTO")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-03-04T11:20:43.685+01:00[Europe/Paris]")
public class OperationStatusDTO {
  public static final String JSON_PROPERTY_DOCUMENT_ID = "documentId";
  private String documentId;

  /**
   * Gets or Sets status
   */
  public enum StatusEnum {
    PREPARED("PREPARED"),
    
    FINISHED("FINISHED"),
    
    EXPIRED("EXPIRED"),
    
    CANCELLED("CANCELLED"),
    
    REJECTED("REJECTED"),
    
    ERROR("ERROR"),
    
    DELETED("DELETED"),
    
    UNKNOWN("UNKNOWN");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static StatusEnum fromValue(String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_STATUS = "status";
  private StatusEnum status;

  public static final String JSON_PROPERTY_STATUS_REASON = "statusReason";
  private String statusReason;

  public static final String JSON_PROPERTY_SOURCE_LINK = "sourceLink";
  private String sourceLink;

  public static final String JSON_PROPERTY_SIGNED_LINK = "signedLink";
  private String signedLink;

  public static final String JSON_PROPERTY_TRAIL = "trail";
  private String trail;

  public static final String JSON_PROPERTY_FILE_NAME = "fileName";
  private String fileName;

  public static final String JSON_PROPERTY_SOURCE_ID = "sourceId";
  private String sourceId;

  public OperationStatusDTO() { 
  }

  public OperationStatusDTO documentId(String documentId) {
    
    this.documentId = documentId;
    return this;
  }

   /**
   * Get documentId
   * @return documentId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_DOCUMENT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDocumentId() {
    return documentId;
  }


  @JsonProperty(JSON_PROPERTY_DOCUMENT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDocumentId(String documentId) {
    this.documentId = documentId;
  }


  public OperationStatusDTO status(StatusEnum status) {
    
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public StatusEnum getStatus() {
    return status;
  }


  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStatus(StatusEnum status) {
    this.status = status;
  }


  public OperationStatusDTO statusReason(String statusReason) {
    
    this.statusReason = statusReason;
    return this;
  }

   /**
   * Get statusReason
   * @return statusReason
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_STATUS_REASON)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getStatusReason() {
    return statusReason;
  }


  @JsonProperty(JSON_PROPERTY_STATUS_REASON)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStatusReason(String statusReason) {
    this.statusReason = statusReason;
  }


  public OperationStatusDTO sourceLink(String sourceLink) {
    
    this.sourceLink = sourceLink;
    return this;
  }

   /**
   * Get sourceLink
   * @return sourceLink
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SOURCE_LINK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSourceLink() {
    return sourceLink;
  }


  @JsonProperty(JSON_PROPERTY_SOURCE_LINK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSourceLink(String sourceLink) {
    this.sourceLink = sourceLink;
  }


  public OperationStatusDTO signedLink(String signedLink) {
    
    this.signedLink = signedLink;
    return this;
  }

   /**
   * Get signedLink
   * @return signedLink
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SIGNED_LINK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSignedLink() {
    return signedLink;
  }


  @JsonProperty(JSON_PROPERTY_SIGNED_LINK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSignedLink(String signedLink) {
    this.signedLink = signedLink;
  }


  public OperationStatusDTO trail(String trail) {
    
    this.trail = trail;
    return this;
  }

   /**
   * Get trail
   * @return trail
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TRAIL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTrail() {
    return trail;
  }


  @JsonProperty(JSON_PROPERTY_TRAIL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTrail(String trail) {
    this.trail = trail;
  }


  public OperationStatusDTO fileName(String fileName) {
    
    this.fileName = fileName;
    return this;
  }

   /**
   * Get fileName
   * @return fileName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_FILE_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFileName() {
    return fileName;
  }


  @JsonProperty(JSON_PROPERTY_FILE_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFileName(String fileName) {
    this.fileName = fileName;
  }


  public OperationStatusDTO sourceId(String sourceId) {
    
    this.sourceId = sourceId;
    return this;
  }

   /**
   * Get sourceId
   * @return sourceId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SOURCE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSourceId() {
    return sourceId;
  }


  @JsonProperty(JSON_PROPERTY_SOURCE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSourceId(String sourceId) {
    this.sourceId = sourceId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OperationStatusDTO operationStatusDTO = (OperationStatusDTO) o;
    return Objects.equals(this.documentId, operationStatusDTO.documentId) &&
        Objects.equals(this.status, operationStatusDTO.status) &&
        Objects.equals(this.statusReason, operationStatusDTO.statusReason) &&
        Objects.equals(this.sourceLink, operationStatusDTO.sourceLink) &&
        Objects.equals(this.signedLink, operationStatusDTO.signedLink) &&
        Objects.equals(this.trail, operationStatusDTO.trail) &&
        Objects.equals(this.fileName, operationStatusDTO.fileName) &&
        Objects.equals(this.sourceId, operationStatusDTO.sourceId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(documentId, status, statusReason, sourceLink, signedLink, trail, fileName, sourceId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OperationStatusDTO {\n");
    sb.append("    documentId: ").append(toIndentedString(documentId)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    statusReason: ").append(toIndentedString(statusReason)).append("\n");
    sb.append("    sourceLink: ").append(toIndentedString(sourceLink)).append("\n");
    sb.append("    signedLink: ").append(toIndentedString(signedLink)).append("\n");
    sb.append("    trail: ").append(toIndentedString(trail)).append("\n");
    sb.append("    fileName: ").append(toIndentedString(fileName)).append("\n");
    sb.append("    sourceId: ").append(toIndentedString(sourceId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

