/*
 * Viafirma API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.3.29-r83-596fbc1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.openapitools.client.model.ConfigCertificateRequestDTO;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * PrepareAuthDTO
 */
@JsonPropertyOrder({
  PrepareAuthDTO.JSON_PROPERTY_CERTIFICATE_FILTER,
  PrepareAuthDTO.JSON_PROPERTY_CALLBACK_U_R_L,
  PrepareAuthDTO.JSON_PROPERTY_CALLBACK_AUTHORIZATION,
  PrepareAuthDTO.JSON_PROPERTY_CALLBACK_REDIRECT_U_R_L
})
@JsonTypeName("PrepareAuthDTO")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-03-04T11:20:43.685+01:00[Europe/Paris]")
public class PrepareAuthDTO {
  public static final String JSON_PROPERTY_CERTIFICATE_FILTER = "certificateFilter";
  private ConfigCertificateRequestDTO certificateFilter;

  public static final String JSON_PROPERTY_CALLBACK_U_R_L = "callbackURL";
  private String callbackURL;

  public static final String JSON_PROPERTY_CALLBACK_AUTHORIZATION = "callbackAuthorization";
  private String callbackAuthorization;

  public static final String JSON_PROPERTY_CALLBACK_REDIRECT_U_R_L = "callbackRedirectURL";
  private String callbackRedirectURL;

  public PrepareAuthDTO() { 
  }

  public PrepareAuthDTO certificateFilter(ConfigCertificateRequestDTO certificateFilter) {
    
    this.certificateFilter = certificateFilter;
    return this;
  }

   /**
   * Get certificateFilter
   * @return certificateFilter
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CERTIFICATE_FILTER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ConfigCertificateRequestDTO getCertificateFilter() {
    return certificateFilter;
  }


  @JsonProperty(JSON_PROPERTY_CERTIFICATE_FILTER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCertificateFilter(ConfigCertificateRequestDTO certificateFilter) {
    this.certificateFilter = certificateFilter;
  }


  public PrepareAuthDTO callbackURL(String callbackURL) {
    
    this.callbackURL = callbackURL;
    return this;
  }

   /**
   * Get callbackURL
   * @return callbackURL
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CALLBACK_U_R_L)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCallbackURL() {
    return callbackURL;
  }


  @JsonProperty(JSON_PROPERTY_CALLBACK_U_R_L)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCallbackURL(String callbackURL) {
    this.callbackURL = callbackURL;
  }


  public PrepareAuthDTO callbackAuthorization(String callbackAuthorization) {
    
    this.callbackAuthorization = callbackAuthorization;
    return this;
  }

   /**
   * Get callbackAuthorization
   * @return callbackAuthorization
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CALLBACK_AUTHORIZATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCallbackAuthorization() {
    return callbackAuthorization;
  }


  @JsonProperty(JSON_PROPERTY_CALLBACK_AUTHORIZATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCallbackAuthorization(String callbackAuthorization) {
    this.callbackAuthorization = callbackAuthorization;
  }


  public PrepareAuthDTO callbackRedirectURL(String callbackRedirectURL) {
    
    this.callbackRedirectURL = callbackRedirectURL;
    return this;
  }

   /**
   * Get callbackRedirectURL
   * @return callbackRedirectURL
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CALLBACK_REDIRECT_U_R_L)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCallbackRedirectURL() {
    return callbackRedirectURL;
  }


  @JsonProperty(JSON_PROPERTY_CALLBACK_REDIRECT_U_R_L)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCallbackRedirectURL(String callbackRedirectURL) {
    this.callbackRedirectURL = callbackRedirectURL;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PrepareAuthDTO prepareAuthDTO = (PrepareAuthDTO) o;
    return Objects.equals(this.certificateFilter, prepareAuthDTO.certificateFilter) &&
        Objects.equals(this.callbackURL, prepareAuthDTO.callbackURL) &&
        Objects.equals(this.callbackAuthorization, prepareAuthDTO.callbackAuthorization) &&
        Objects.equals(this.callbackRedirectURL, prepareAuthDTO.callbackRedirectURL);
  }

  @Override
  public int hashCode() {
    return Objects.hash(certificateFilter, callbackURL, callbackAuthorization, callbackRedirectURL);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PrepareAuthDTO {\n");
    sb.append("    certificateFilter: ").append(toIndentedString(certificateFilter)).append("\n");
    sb.append("    callbackURL: ").append(toIndentedString(callbackURL)).append("\n");
    sb.append("    callbackAuthorization: ").append(toIndentedString(callbackAuthorization)).append("\n");
    sb.append("    callbackRedirectURL: ").append(toIndentedString(callbackRedirectURL)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

