/*
 * Viafirma API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.3.29-r83-596fbc1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * SignaturePromotionRequestDTO
 */
@JsonPropertyOrder({
  SignaturePromotionRequestDTO.JSON_PROPERTY_FILE_BASE64,
  SignaturePromotionRequestDTO.JSON_PROPERTY_FILE,
  SignaturePromotionRequestDTO.JSON_PROPERTY_TARGET_SIGNATURE_TYPE,
  SignaturePromotionRequestDTO.JSON_PROPERTY_TSA_TEMPLATE
})
@JsonTypeName("SignaturePromotionRequestDTO")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-03-04T11:20:43.685+01:00[Europe/Paris]")
public class SignaturePromotionRequestDTO {
  public static final String JSON_PROPERTY_FILE_BASE64 = "fileBase64";
  private String fileBase64;

  public static final String JSON_PROPERTY_FILE = "file";
  private byte[] _file;

  /**
   * Gets or Sets targetSignatureType
   */
  public enum TargetSignatureTypeEnum {
    CADES_B("CADES_B"),
    
    CADES_T("CADES_T"),
    
    CADES_LT("CADES_LT"),
    
    CADES_LTA("CADES_LTA"),
    
    PADES_B("PADES_B"),
    
    PADES_T("PADES_T"),
    
    PADES_LT("PADES_LT"),
    
    PADES_LTA("PADES_LTA"),
    
    XADES_B("XADES_B"),
    
    XADES_T("XADES_T"),
    
    XADES_LT("XADES_LT"),
    
    XADES_LTA("XADES_LTA");

    private String value;

    TargetSignatureTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TargetSignatureTypeEnum fromValue(String value) {
      for (TargetSignatureTypeEnum b : TargetSignatureTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_TARGET_SIGNATURE_TYPE = "targetSignatureType";
  private TargetSignatureTypeEnum targetSignatureType;

  public static final String JSON_PROPERTY_TSA_TEMPLATE = "tsaTemplate";
  private String tsaTemplate;

  public SignaturePromotionRequestDTO() { 
  }

  public SignaturePromotionRequestDTO fileBase64(String fileBase64) {
    
    this.fileBase64 = fileBase64;
    return this;
  }

   /**
   * Get fileBase64
   * @return fileBase64
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_FILE_BASE64)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFileBase64() {
    return fileBase64;
  }


  @JsonProperty(JSON_PROPERTY_FILE_BASE64)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFileBase64(String fileBase64) {
    this.fileBase64 = fileBase64;
  }


  public SignaturePromotionRequestDTO _file(byte[] _file) {
    
    this._file = _file;
    return this;
  }

   /**
   * Get _file
   * @return _file
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_FILE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public byte[] getFile() {
    return _file;
  }


  @JsonProperty(JSON_PROPERTY_FILE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFile(byte[] _file) {
    this._file = _file;
  }


  public SignaturePromotionRequestDTO targetSignatureType(TargetSignatureTypeEnum targetSignatureType) {
    
    this.targetSignatureType = targetSignatureType;
    return this;
  }

   /**
   * Get targetSignatureType
   * @return targetSignatureType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TARGET_SIGNATURE_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public TargetSignatureTypeEnum getTargetSignatureType() {
    return targetSignatureType;
  }


  @JsonProperty(JSON_PROPERTY_TARGET_SIGNATURE_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTargetSignatureType(TargetSignatureTypeEnum targetSignatureType) {
    this.targetSignatureType = targetSignatureType;
  }


  public SignaturePromotionRequestDTO tsaTemplate(String tsaTemplate) {
    
    this.tsaTemplate = tsaTemplate;
    return this;
  }

   /**
   * Get tsaTemplate
   * @return tsaTemplate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TSA_TEMPLATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTsaTemplate() {
    return tsaTemplate;
  }


  @JsonProperty(JSON_PROPERTY_TSA_TEMPLATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTsaTemplate(String tsaTemplate) {
    this.tsaTemplate = tsaTemplate;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SignaturePromotionRequestDTO signaturePromotionRequestDTO = (SignaturePromotionRequestDTO) o;
    return Objects.equals(this.fileBase64, signaturePromotionRequestDTO.fileBase64) &&
        Arrays.equals(this._file, signaturePromotionRequestDTO._file) &&
        Objects.equals(this.targetSignatureType, signaturePromotionRequestDTO.targetSignatureType) &&
        Objects.equals(this.tsaTemplate, signaturePromotionRequestDTO.tsaTemplate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(fileBase64, Arrays.hashCode(_file), targetSignatureType, tsaTemplate);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SignaturePromotionRequestDTO {\n");
    sb.append("    fileBase64: ").append(toIndentedString(fileBase64)).append("\n");
    sb.append("    _file: ").append(toIndentedString(_file)).append("\n");
    sb.append("    targetSignatureType: ").append(toIndentedString(targetSignatureType)).append("\n");
    sb.append("    tsaTemplate: ").append(toIndentedString(tsaTemplate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

