/*
 * Viafirma API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.3.29-r83-596fbc1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * SignatureResponseDTO
 */
@JsonPropertyOrder({
  SignatureResponseDTO.JSON_PROPERTY_OPERATION_CODE,
  SignatureResponseDTO.JSON_PROPERTY_SIGNED_FILE_BASE64,
  SignatureResponseDTO.JSON_PROPERTY_SIGNED_FILE,
  SignatureResponseDTO.JSON_PROPERTY_SIGNED_LINK,
  SignatureResponseDTO.JSON_PROPERTY_SIGNATURE_TEMPLATE,
  SignatureResponseDTO.JSON_PROPERTY_SIGNATURE_CODE,
  SignatureResponseDTO.JSON_PROPERTY_TRAIL_LINK
})
@JsonTypeName("SignatureResponseDTO")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-03-04T11:20:43.685+01:00[Europe/Paris]")
public class SignatureResponseDTO {
  public static final String JSON_PROPERTY_OPERATION_CODE = "operationCode";
  private String operationCode;

  public static final String JSON_PROPERTY_SIGNED_FILE_BASE64 = "signedFileBase64";
  private String signedFileBase64;

  public static final String JSON_PROPERTY_SIGNED_FILE = "signedFile";
  private byte[] signedFile;

  public static final String JSON_PROPERTY_SIGNED_LINK = "signedLink";
  private String signedLink;

  public static final String JSON_PROPERTY_SIGNATURE_TEMPLATE = "signatureTemplate";
  private String signatureTemplate;

  public static final String JSON_PROPERTY_SIGNATURE_CODE = "signatureCode";
  private String signatureCode;

  public static final String JSON_PROPERTY_TRAIL_LINK = "trailLink";
  private String trailLink;

  public SignatureResponseDTO() { 
  }

  public SignatureResponseDTO operationCode(String operationCode) {
    
    this.operationCode = operationCode;
    return this;
  }

   /**
   * Get operationCode
   * @return operationCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_OPERATION_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getOperationCode() {
    return operationCode;
  }


  @JsonProperty(JSON_PROPERTY_OPERATION_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOperationCode(String operationCode) {
    this.operationCode = operationCode;
  }


  public SignatureResponseDTO signedFileBase64(String signedFileBase64) {
    
    this.signedFileBase64 = signedFileBase64;
    return this;
  }

   /**
   * Get signedFileBase64
   * @return signedFileBase64
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SIGNED_FILE_BASE64)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSignedFileBase64() {
    return signedFileBase64;
  }


  @JsonProperty(JSON_PROPERTY_SIGNED_FILE_BASE64)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSignedFileBase64(String signedFileBase64) {
    this.signedFileBase64 = signedFileBase64;
  }


  public SignatureResponseDTO signedFile(byte[] signedFile) {
    
    this.signedFile = signedFile;
    return this;
  }

   /**
   * Get signedFile
   * @return signedFile
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SIGNED_FILE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public byte[] getSignedFile() {
    return signedFile;
  }


  @JsonProperty(JSON_PROPERTY_SIGNED_FILE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSignedFile(byte[] signedFile) {
    this.signedFile = signedFile;
  }


  public SignatureResponseDTO signedLink(String signedLink) {
    
    this.signedLink = signedLink;
    return this;
  }

   /**
   * Get signedLink
   * @return signedLink
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SIGNED_LINK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSignedLink() {
    return signedLink;
  }


  @JsonProperty(JSON_PROPERTY_SIGNED_LINK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSignedLink(String signedLink) {
    this.signedLink = signedLink;
  }


  public SignatureResponseDTO signatureTemplate(String signatureTemplate) {
    
    this.signatureTemplate = signatureTemplate;
    return this;
  }

   /**
   * Get signatureTemplate
   * @return signatureTemplate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SIGNATURE_TEMPLATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSignatureTemplate() {
    return signatureTemplate;
  }


  @JsonProperty(JSON_PROPERTY_SIGNATURE_TEMPLATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSignatureTemplate(String signatureTemplate) {
    this.signatureTemplate = signatureTemplate;
  }


  public SignatureResponseDTO signatureCode(String signatureCode) {
    
    this.signatureCode = signatureCode;
    return this;
  }

   /**
   * Get signatureCode
   * @return signatureCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SIGNATURE_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSignatureCode() {
    return signatureCode;
  }


  @JsonProperty(JSON_PROPERTY_SIGNATURE_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSignatureCode(String signatureCode) {
    this.signatureCode = signatureCode;
  }


  public SignatureResponseDTO trailLink(String trailLink) {
    
    this.trailLink = trailLink;
    return this;
  }

   /**
   * Get trailLink
   * @return trailLink
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TRAIL_LINK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTrailLink() {
    return trailLink;
  }


  @JsonProperty(JSON_PROPERTY_TRAIL_LINK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTrailLink(String trailLink) {
    this.trailLink = trailLink;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SignatureResponseDTO signatureResponseDTO = (SignatureResponseDTO) o;
    return Objects.equals(this.operationCode, signatureResponseDTO.operationCode) &&
        Objects.equals(this.signedFileBase64, signatureResponseDTO.signedFileBase64) &&
        Arrays.equals(this.signedFile, signatureResponseDTO.signedFile) &&
        Objects.equals(this.signedLink, signatureResponseDTO.signedLink) &&
        Objects.equals(this.signatureTemplate, signatureResponseDTO.signatureTemplate) &&
        Objects.equals(this.signatureCode, signatureResponseDTO.signatureCode) &&
        Objects.equals(this.trailLink, signatureResponseDTO.trailLink);
  }

  @Override
  public int hashCode() {
    return Objects.hash(operationCode, signedFileBase64, Arrays.hashCode(signedFile), signedLink, signatureTemplate, signatureCode, trailLink);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SignatureResponseDTO {\n");
    sb.append("    operationCode: ").append(toIndentedString(operationCode)).append("\n");
    sb.append("    signedFileBase64: ").append(toIndentedString(signedFileBase64)).append("\n");
    sb.append("    signedFile: ").append(toIndentedString(signedFile)).append("\n");
    sb.append("    signedLink: ").append(toIndentedString(signedLink)).append("\n");
    sb.append("    signatureTemplate: ").append(toIndentedString(signatureTemplate)).append("\n");
    sb.append("    signatureCode: ").append(toIndentedString(signatureCode)).append("\n");
    sb.append("    trailLink: ").append(toIndentedString(trailLink)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

