/*
 * Viafirma API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.3.29-r83-596fbc1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * SignaturePromotionResponseDTO
 */
@JsonPropertyOrder({
  SignaturePromotionResponseDTO.JSON_PROPERTY_PROMOTED_FILE_BASE64
})
@JsonTypeName("SignaturePromotionResponseDTO")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-03-04T11:20:43.685+01:00[Europe/Paris]")
public class SignaturePromotionResponseDTO {
  public static final String JSON_PROPERTY_PROMOTED_FILE_BASE64 = "promotedFileBase64";
  private String promotedFileBase64;

  public SignaturePromotionResponseDTO() { 
  }

  public SignaturePromotionResponseDTO promotedFileBase64(String promotedFileBase64) {
    
    this.promotedFileBase64 = promotedFileBase64;
    return this;
  }

   /**
   * Get promotedFileBase64
   * @return promotedFileBase64
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_PROMOTED_FILE_BASE64)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPromotedFileBase64() {
    return promotedFileBase64;
  }


  @JsonProperty(JSON_PROPERTY_PROMOTED_FILE_BASE64)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPromotedFileBase64(String promotedFileBase64) {
    this.promotedFileBase64 = promotedFileBase64;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SignaturePromotionResponseDTO signaturePromotionResponseDTO = (SignaturePromotionResponseDTO) o;
    return Objects.equals(this.promotedFileBase64, signaturePromotionResponseDTO.promotedFileBase64);
  }

  @Override
  public int hashCode() {
    return Objects.hash(promotedFileBase64);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SignaturePromotionResponseDTO {\n");
    sb.append("    promotedFileBase64: ").append(toIndentedString(promotedFileBase64)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

