/*
 * Viafirma API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.3.29-r83-596fbc1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.openapitools.client.model.ConfigSignatureDTO;
import org.openapitools.client.model.FortressConfigurationDTO;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * SignatureRequestDTO
 */
@JsonPropertyOrder({
  SignatureRequestDTO.JSON_PROPERTY_FILE_BASE64,
  SignatureRequestDTO.JSON_PROPERTY_FILE,
  SignatureRequestDTO.JSON_PROPERTY_FILE_LINK,
  SignatureRequestDTO.JSON_PROPERTY_CONFIGURATION,
  SignatureRequestDTO.JSON_PROPERTY_CONFIGURATION_TEMPLATE,
  SignatureRequestDTO.JSON_PROPERTY_REASON,
  SignatureRequestDTO.JSON_PROPERTY_CERTIFICATE_ALIAS,
  SignatureRequestDTO.JSON_PROPERTY_CERTIFICATE_PASS,
  SignatureRequestDTO.JSON_PROPERTY_CERTIFICATE_ID,
  SignatureRequestDTO.JSON_PROPERTY_FORTRESS_CONFIGURATION,
  SignatureRequestDTO.JSON_PROPERTY_TRAIL_ENABLED
})
@JsonTypeName("SignatureRequestDTO")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-03-04T11:20:43.685+01:00[Europe/Paris]")
public class SignatureRequestDTO {
  public static final String JSON_PROPERTY_FILE_BASE64 = "fileBase64";
  private String fileBase64;

  public static final String JSON_PROPERTY_FILE = "file";
  private byte[] _file;

  public static final String JSON_PROPERTY_FILE_LINK = "fileLink";
  private String fileLink;

  public static final String JSON_PROPERTY_CONFIGURATION = "configuration";
  private ConfigSignatureDTO _configuration;

  public static final String JSON_PROPERTY_CONFIGURATION_TEMPLATE = "configurationTemplate";
  private String configurationTemplate;

  public static final String JSON_PROPERTY_REASON = "reason";
  private String reason;

  public static final String JSON_PROPERTY_CERTIFICATE_ALIAS = "certificateAlias";
  private String certificateAlias;

  public static final String JSON_PROPERTY_CERTIFICATE_PASS = "certificatePass";
  private String certificatePass;

  public static final String JSON_PROPERTY_CERTIFICATE_ID = "certificateId";
  private String certificateId;

  public static final String JSON_PROPERTY_FORTRESS_CONFIGURATION = "fortressConfiguration";
  private FortressConfigurationDTO fortressConfiguration;

  public static final String JSON_PROPERTY_TRAIL_ENABLED = "trailEnabled";
  private Boolean trailEnabled;

  public SignatureRequestDTO() { 
  }

  public SignatureRequestDTO fileBase64(String fileBase64) {
    
    this.fileBase64 = fileBase64;
    return this;
  }

   /**
   * Get fileBase64
   * @return fileBase64
   * @deprecated
  **/
  @Deprecated
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_FILE_BASE64)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFileBase64() {
    return fileBase64;
  }


  @JsonProperty(JSON_PROPERTY_FILE_BASE64)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFileBase64(String fileBase64) {
    this.fileBase64 = fileBase64;
  }


  public SignatureRequestDTO _file(byte[] _file) {
    
    this._file = _file;
    return this;
  }

   /**
   * Get _file
   * @return _file
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_FILE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public byte[] getFile() {
    return _file;
  }


  @JsonProperty(JSON_PROPERTY_FILE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFile(byte[] _file) {
    this._file = _file;
  }


  public SignatureRequestDTO fileLink(String fileLink) {
    
    this.fileLink = fileLink;
    return this;
  }

   /**
   * Get fileLink
   * @return fileLink
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_FILE_LINK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFileLink() {
    return fileLink;
  }


  @JsonProperty(JSON_PROPERTY_FILE_LINK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFileLink(String fileLink) {
    this.fileLink = fileLink;
  }


  public SignatureRequestDTO _configuration(ConfigSignatureDTO _configuration) {
    
    this._configuration = _configuration;
    return this;
  }

   /**
   * Get _configuration
   * @return _configuration
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CONFIGURATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ConfigSignatureDTO getConfiguration() {
    return _configuration;
  }


  @JsonProperty(JSON_PROPERTY_CONFIGURATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setConfiguration(ConfigSignatureDTO _configuration) {
    this._configuration = _configuration;
  }


  public SignatureRequestDTO configurationTemplate(String configurationTemplate) {
    
    this.configurationTemplate = configurationTemplate;
    return this;
  }

   /**
   * Get configurationTemplate
   * @return configurationTemplate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CONFIGURATION_TEMPLATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getConfigurationTemplate() {
    return configurationTemplate;
  }


  @JsonProperty(JSON_PROPERTY_CONFIGURATION_TEMPLATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setConfigurationTemplate(String configurationTemplate) {
    this.configurationTemplate = configurationTemplate;
  }


  public SignatureRequestDTO reason(String reason) {
    
    this.reason = reason;
    return this;
  }

   /**
   * Get reason
   * @return reason
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_REASON)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getReason() {
    return reason;
  }


  @JsonProperty(JSON_PROPERTY_REASON)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setReason(String reason) {
    this.reason = reason;
  }


  public SignatureRequestDTO certificateAlias(String certificateAlias) {
    
    this.certificateAlias = certificateAlias;
    return this;
  }

   /**
   * Get certificateAlias
   * @return certificateAlias
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CERTIFICATE_ALIAS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCertificateAlias() {
    return certificateAlias;
  }


  @JsonProperty(JSON_PROPERTY_CERTIFICATE_ALIAS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCertificateAlias(String certificateAlias) {
    this.certificateAlias = certificateAlias;
  }


  public SignatureRequestDTO certificatePass(String certificatePass) {
    
    this.certificatePass = certificatePass;
    return this;
  }

   /**
   * Get certificatePass
   * @return certificatePass
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CERTIFICATE_PASS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCertificatePass() {
    return certificatePass;
  }


  @JsonProperty(JSON_PROPERTY_CERTIFICATE_PASS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCertificatePass(String certificatePass) {
    this.certificatePass = certificatePass;
  }


  public SignatureRequestDTO certificateId(String certificateId) {
    
    this.certificateId = certificateId;
    return this;
  }

   /**
   * Get certificateId
   * @return certificateId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CERTIFICATE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCertificateId() {
    return certificateId;
  }


  @JsonProperty(JSON_PROPERTY_CERTIFICATE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCertificateId(String certificateId) {
    this.certificateId = certificateId;
  }


  public SignatureRequestDTO fortressConfiguration(FortressConfigurationDTO fortressConfiguration) {
    
    this.fortressConfiguration = fortressConfiguration;
    return this;
  }

   /**
   * Get fortressConfiguration
   * @return fortressConfiguration
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_FORTRESS_CONFIGURATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public FortressConfigurationDTO getFortressConfiguration() {
    return fortressConfiguration;
  }


  @JsonProperty(JSON_PROPERTY_FORTRESS_CONFIGURATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFortressConfiguration(FortressConfigurationDTO fortressConfiguration) {
    this.fortressConfiguration = fortressConfiguration;
  }


  public SignatureRequestDTO trailEnabled(Boolean trailEnabled) {
    
    this.trailEnabled = trailEnabled;
    return this;
  }

   /**
   * Get trailEnabled
   * @return trailEnabled
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TRAIL_ENABLED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getTrailEnabled() {
    return trailEnabled;
  }


  @JsonProperty(JSON_PROPERTY_TRAIL_ENABLED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTrailEnabled(Boolean trailEnabled) {
    this.trailEnabled = trailEnabled;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SignatureRequestDTO signatureRequestDTO = (SignatureRequestDTO) o;
    return Objects.equals(this.fileBase64, signatureRequestDTO.fileBase64) &&
        Arrays.equals(this._file, signatureRequestDTO._file) &&
        Objects.equals(this.fileLink, signatureRequestDTO.fileLink) &&
        Objects.equals(this._configuration, signatureRequestDTO._configuration) &&
        Objects.equals(this.configurationTemplate, signatureRequestDTO.configurationTemplate) &&
        Objects.equals(this.reason, signatureRequestDTO.reason) &&
        Objects.equals(this.certificateAlias, signatureRequestDTO.certificateAlias) &&
        Objects.equals(this.certificatePass, signatureRequestDTO.certificatePass) &&
        Objects.equals(this.certificateId, signatureRequestDTO.certificateId) &&
        Objects.equals(this.fortressConfiguration, signatureRequestDTO.fortressConfiguration) &&
        Objects.equals(this.trailEnabled, signatureRequestDTO.trailEnabled);
  }

  @Override
  public int hashCode() {
    return Objects.hash(fileBase64, Arrays.hashCode(_file), fileLink, _configuration, configurationTemplate, reason, certificateAlias, certificatePass, certificateId, fortressConfiguration, trailEnabled);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SignatureRequestDTO {\n");
    sb.append("    fileBase64: ").append(toIndentedString(fileBase64)).append("\n");
    sb.append("    _file: ").append(toIndentedString(_file)).append("\n");
    sb.append("    fileLink: ").append(toIndentedString(fileLink)).append("\n");
    sb.append("    _configuration: ").append(toIndentedString(_configuration)).append("\n");
    sb.append("    configurationTemplate: ").append(toIndentedString(configurationTemplate)).append("\n");
    sb.append("    reason: ").append(toIndentedString(reason)).append("\n");
    sb.append("    certificateAlias: ").append(toIndentedString(certificateAlias)).append("\n");
    sb.append("    certificatePass: ").append(toIndentedString(certificatePass)).append("\n");
    sb.append("    certificateId: ").append(toIndentedString(certificateId)).append("\n");
    sb.append("    fortressConfiguration: ").append(toIndentedString(fortressConfiguration)).append("\n");
    sb.append("    trailEnabled: ").append(toIndentedString(trailEnabled)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

