/*
 * Viafirma API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.3.29-r83-596fbc1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.OffsetDateTime;
import org.openapitools.client.model.StamperDTOTimeZone;
import org.openapitools.client.model.StamperLegacyDTO;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * StamperDTO
 */
@JsonPropertyOrder({
  StamperDTO.JSON_PROPERTY_TYPE,
  StamperDTO.JSON_PROPERTY_ROTATION,
  StamperDTO.JSON_PROPERTY_WIDTH,
  StamperDTO.JSON_PROPERTY_HEIGHT,
  StamperDTO.JSON_PROPERTY_X_AXIS,
  StamperDTO.JSON_PROPERTY_Y_AXIS,
  StamperDTO.JSON_PROPERTY_PAGE,
  StamperDTO.JSON_PROPERTY_CSV_PATH,
  StamperDTO.JSON_PROPERTY_CSV_ID,
  StamperDTO.JSON_PROPERTY_TEXT_LINE1,
  StamperDTO.JSON_PROPERTY_TEXT_LINE2,
  StamperDTO.JSON_PROPERTY_TEXT_LINE3,
  StamperDTO.JSON_PROPERTY_IMAGE,
  StamperDTO.JSON_PROPERTY_LOGO,
  StamperDTO.JSON_PROPERTY_SIGNING_DATE,
  StamperDTO.JSON_PROPERTY_TRANSPARENT,
  StamperDTO.JSON_PROPERTY_TIME_ZONE,
  StamperDTO.JSON_PROPERTY_ADD_CSV_LINK,
  StamperDTO.JSON_PROPERTY_LEGACY_PARAM
})
@JsonTypeName("StamperDTO")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-03-04T11:20:43.685+01:00[Europe/Paris]")
public class StamperDTO {
  /**
   * Gets or Sets type
   */
  public enum TypeEnum {
    PDF417("PDF417"),
    
    PDF417_LEGACY("PDF417_LEGACY"),
    
    QR_BARCODE128("QR_BARCODE128"),
    
    QR_BARCODE128_LEGACY("QR_BARCODE128_LEGACY"),
    
    QR("QR"),
    
    BARCODE128("BARCODE128"),
    
    IMAGE("IMAGE"),
    
    TEXT("TEXT"),
    
    MINTEXT("MINTEXT"),
    
    QR_NO_TEXT("QR_NO_TEXT"),
    
    QR_SCALED("QR_SCALED"),
    
    CUSTOM_TEXT("CUSTOM_TEXT"),
    
    QR_REDUCED("QR_REDUCED"),
    
    CSV("CSV"),
    
    CSV_QR("CSV_QR"),
    
    IMAGE_TEXT("IMAGE_TEXT"),
    
    DEFAULT("DEFAULT");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_TYPE = "type";
  private TypeEnum type;

  /**
   * Gets or Sets rotation
   */
  public enum RotationEnum {
    _90("ROTATE_90"),
    
    _270("ROTATE_270");

    private String value;

    RotationEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static RotationEnum fromValue(String value) {
      for (RotationEnum b : RotationEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_ROTATION = "rotation";
  private RotationEnum rotation;

  public static final String JSON_PROPERTY_WIDTH = "width";
  private Integer width;

  public static final String JSON_PROPERTY_HEIGHT = "height";
  private Integer height;

  public static final String JSON_PROPERTY_X_AXIS = "xAxis";
  private Integer xAxis;

  public static final String JSON_PROPERTY_Y_AXIS = "yAxis";
  private Integer yAxis;

  public static final String JSON_PROPERTY_PAGE = "page";
  private Integer page;

  public static final String JSON_PROPERTY_CSV_PATH = "csvPath";
  private String csvPath;

  public static final String JSON_PROPERTY_CSV_ID = "csvId";
  private String csvId;

  public static final String JSON_PROPERTY_TEXT_LINE1 = "textLine1";
  private String textLine1;

  public static final String JSON_PROPERTY_TEXT_LINE2 = "textLine2";
  private String textLine2;

  public static final String JSON_PROPERTY_TEXT_LINE3 = "textLine3";
  private String textLine3;

  public static final String JSON_PROPERTY_IMAGE = "image";
  private byte[] image;

  public static final String JSON_PROPERTY_LOGO = "logo";
  private byte[] logo;

  public static final String JSON_PROPERTY_SIGNING_DATE = "signingDate";
  private OffsetDateTime signingDate;

  public static final String JSON_PROPERTY_TRANSPARENT = "transparent";
  private Boolean transparent;

  public static final String JSON_PROPERTY_TIME_ZONE = "timeZone";
  private StamperDTOTimeZone timeZone;

  public static final String JSON_PROPERTY_ADD_CSV_LINK = "addCsvLink";
  private Boolean addCsvLink;

  public static final String JSON_PROPERTY_LEGACY_PARAM = "legacyParam";
  private StamperLegacyDTO legacyParam;

  public StamperDTO() { 
  }

  public StamperDTO type(TypeEnum type) {
    
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public TypeEnum getType() {
    return type;
  }


  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setType(TypeEnum type) {
    this.type = type;
  }


  public StamperDTO rotation(RotationEnum rotation) {
    
    this.rotation = rotation;
    return this;
  }

   /**
   * Get rotation
   * @return rotation
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ROTATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RotationEnum getRotation() {
    return rotation;
  }


  @JsonProperty(JSON_PROPERTY_ROTATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRotation(RotationEnum rotation) {
    this.rotation = rotation;
  }


  public StamperDTO width(Integer width) {
    
    this.width = width;
    return this;
  }

   /**
   * Get width
   * @return width
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_WIDTH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getWidth() {
    return width;
  }


  @JsonProperty(JSON_PROPERTY_WIDTH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setWidth(Integer width) {
    this.width = width;
  }


  public StamperDTO height(Integer height) {
    
    this.height = height;
    return this;
  }

   /**
   * Get height
   * @return height
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_HEIGHT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getHeight() {
    return height;
  }


  @JsonProperty(JSON_PROPERTY_HEIGHT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHeight(Integer height) {
    this.height = height;
  }


  public StamperDTO getxAxis(Integer xAxis) {
    
    this.xAxis = xAxis;
    return this;
  }

   /**
   * Get getxAxis
   * @return getxAxis
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_X_AXIS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getxAxis() {
    return xAxis;
  }


  @JsonProperty(JSON_PROPERTY_X_AXIS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setxAxis(Integer xAxis) {
    this.xAxis = xAxis;
  }


  public StamperDTO setyAxis(Integer yAxis) {
    
    this.yAxis = yAxis;
    return this;
  }

   /**
   * Get getyAxis
   * @return getyAxis
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_Y_AXIS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getyAxis() {
    return yAxis;
  }


  @JsonProperty(JSON_PROPERTY_Y_AXIS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setGetyAxis(Integer yAxis) {
    this.yAxis = yAxis;
  }


  public StamperDTO page(Integer page) {
    
    this.page = page;
    return this;
  }

   /**
   * Get page
   * @return page
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_PAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getPage() {
    return page;
  }


  @JsonProperty(JSON_PROPERTY_PAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPage(Integer page) {
    this.page = page;
  }


  public StamperDTO csvPath(String csvPath) {
    
    this.csvPath = csvPath;
    return this;
  }

   /**
   * Get csvPath
   * @return csvPath
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CSV_PATH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCsvPath() {
    return csvPath;
  }


  @JsonProperty(JSON_PROPERTY_CSV_PATH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCsvPath(String csvPath) {
    this.csvPath = csvPath;
  }


  public StamperDTO csvId(String csvId) {
    
    this.csvId = csvId;
    return this;
  }

   /**
   * Get csvId
   * @return csvId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CSV_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCsvId() {
    return csvId;
  }


  @JsonProperty(JSON_PROPERTY_CSV_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCsvId(String csvId) {
    this.csvId = csvId;
  }


  public StamperDTO textLine1(String textLine1) {
    
    this.textLine1 = textLine1;
    return this;
  }

   /**
   * Get textLine1
   * @return textLine1
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TEXT_LINE1)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTextLine1() {
    return textLine1;
  }


  @JsonProperty(JSON_PROPERTY_TEXT_LINE1)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTextLine1(String textLine1) {
    this.textLine1 = textLine1;
  }


  public StamperDTO textLine2(String textLine2) {
    
    this.textLine2 = textLine2;
    return this;
  }

   /**
   * Get textLine2
   * @return textLine2
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TEXT_LINE2)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTextLine2() {
    return textLine2;
  }


  @JsonProperty(JSON_PROPERTY_TEXT_LINE2)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTextLine2(String textLine2) {
    this.textLine2 = textLine2;
  }


  public StamperDTO textLine3(String textLine3) {
    
    this.textLine3 = textLine3;
    return this;
  }

   /**
   * Get textLine3
   * @return textLine3
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TEXT_LINE3)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTextLine3() {
    return textLine3;
  }


  @JsonProperty(JSON_PROPERTY_TEXT_LINE3)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTextLine3(String textLine3) {
    this.textLine3 = textLine3;
  }


  public StamperDTO image(byte[] image) {
    
    this.image = image;
    return this;
  }

   /**
   * Get image
   * @return image
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_IMAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public byte[] getImage() {
    return image;
  }


  @JsonProperty(JSON_PROPERTY_IMAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setImage(byte[] image) {
    this.image = image;
  }


  public StamperDTO logo(byte[] logo) {
    
    this.logo = logo;
    return this;
  }

   /**
   * Get logo
   * @return logo
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_LOGO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public byte[] getLogo() {
    return logo;
  }


  @JsonProperty(JSON_PROPERTY_LOGO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLogo(byte[] logo) {
    this.logo = logo;
  }


  public StamperDTO signingDate(OffsetDateTime signingDate) {
    
    this.signingDate = signingDate;
    return this;
  }

   /**
   * Get signingDate
   * @return signingDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SIGNING_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getSigningDate() {
    return signingDate;
  }


  @JsonProperty(JSON_PROPERTY_SIGNING_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSigningDate(OffsetDateTime signingDate) {
    this.signingDate = signingDate;
  }


  public StamperDTO transparent(Boolean transparent) {
    
    this.transparent = transparent;
    return this;
  }

   /**
   * Get transparent
   * @return transparent
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TRANSPARENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getTransparent() {
    return transparent;
  }


  @JsonProperty(JSON_PROPERTY_TRANSPARENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTransparent(Boolean transparent) {
    this.transparent = transparent;
  }


  public StamperDTO timeZone(StamperDTOTimeZone timeZone) {
    
    this.timeZone = timeZone;
    return this;
  }

   /**
   * Get timeZone
   * @return timeZone
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TIME_ZONE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public StamperDTOTimeZone getTimeZone() {
    return timeZone;
  }


  @JsonProperty(JSON_PROPERTY_TIME_ZONE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTimeZone(StamperDTOTimeZone timeZone) {
    this.timeZone = timeZone;
  }


  public StamperDTO addCsvLink(Boolean addCsvLink) {
    
    this.addCsvLink = addCsvLink;
    return this;
  }

   /**
   * Get addCsvLink
   * @return addCsvLink
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ADD_CSV_LINK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getAddCsvLink() {
    return addCsvLink;
  }


  @JsonProperty(JSON_PROPERTY_ADD_CSV_LINK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAddCsvLink(Boolean addCsvLink) {
    this.addCsvLink = addCsvLink;
  }


  public StamperDTO legacyParam(StamperLegacyDTO legacyParam) {
    
    this.legacyParam = legacyParam;
    return this;
  }

   /**
   * Get legacyParam
   * @return legacyParam
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_LEGACY_PARAM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public StamperLegacyDTO getLegacyParam() {
    return legacyParam;
  }


  @JsonProperty(JSON_PROPERTY_LEGACY_PARAM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLegacyParam(StamperLegacyDTO legacyParam) {
    this.legacyParam = legacyParam;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StamperDTO stamperDTO = (StamperDTO) o;
    return Objects.equals(this.type, stamperDTO.type) &&
        Objects.equals(this.rotation, stamperDTO.rotation) &&
        Objects.equals(this.width, stamperDTO.width) &&
        Objects.equals(this.height, stamperDTO.height) &&
        Objects.equals(this.xAxis, stamperDTO.xAxis) &&
        Objects.equals(this.yAxis, stamperDTO.yAxis) &&
        Objects.equals(this.page, stamperDTO.page) &&
        Objects.equals(this.csvPath, stamperDTO.csvPath) &&
        Objects.equals(this.csvId, stamperDTO.csvId) &&
        Objects.equals(this.textLine1, stamperDTO.textLine1) &&
        Objects.equals(this.textLine2, stamperDTO.textLine2) &&
        Objects.equals(this.textLine3, stamperDTO.textLine3) &&
        Arrays.equals(this.image, stamperDTO.image) &&
        Arrays.equals(this.logo, stamperDTO.logo) &&
        Objects.equals(this.signingDate, stamperDTO.signingDate) &&
        Objects.equals(this.transparent, stamperDTO.transparent) &&
        Objects.equals(this.timeZone, stamperDTO.timeZone) &&
        Objects.equals(this.addCsvLink, stamperDTO.addCsvLink) &&
        Objects.equals(this.legacyParam, stamperDTO.legacyParam);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, rotation, width, height, xAxis, yAxis, page, csvPath, csvId, textLine1, textLine2, textLine3, Arrays.hashCode(image), Arrays.hashCode(logo), signingDate, transparent, timeZone, addCsvLink, legacyParam);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StamperDTO {\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    rotation: ").append(toIndentedString(rotation)).append("\n");
    sb.append("    width: ").append(toIndentedString(width)).append("\n");
    sb.append("    height: ").append(toIndentedString(height)).append("\n");
    sb.append("    xAxis: ").append(toIndentedString(xAxis)).append("\n");
    sb.append("    yAxis: ").append(toIndentedString(yAxis)).append("\n");
    sb.append("    page: ").append(toIndentedString(page)).append("\n");
    sb.append("    csvPath: ").append(toIndentedString(csvPath)).append("\n");
    sb.append("    csvId: ").append(toIndentedString(csvId)).append("\n");
    sb.append("    textLine1: ").append(toIndentedString(textLine1)).append("\n");
    sb.append("    textLine2: ").append(toIndentedString(textLine2)).append("\n");
    sb.append("    textLine3: ").append(toIndentedString(textLine3)).append("\n");
    sb.append("    image: ").append(toIndentedString(image)).append("\n");
    sb.append("    logo: ").append(toIndentedString(logo)).append("\n");
    sb.append("    signingDate: ").append(toIndentedString(signingDate)).append("\n");
    sb.append("    transparent: ").append(toIndentedString(transparent)).append("\n");
    sb.append("    timeZone: ").append(toIndentedString(timeZone)).append("\n");
    sb.append("    addCsvLink: ").append(toIndentedString(addCsvLink)).append("\n");
    sb.append("    legacyParam: ").append(toIndentedString(legacyParam)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

