/*
 * Viafirma API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.3.29-r83-596fbc1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * StamperLegacyDTO
 */
@JsonPropertyOrder({
  StamperLegacyDTO.JSON_PROPERTY_INCLUDE_Q_R_CODE,
  StamperLegacyDTO.JSON_PROPERTY_INCLUDE_BAR_CODE,
  StamperLegacyDTO.JSON_PROPERTY_INCLUDE_VERIFICATION_U_R_L,
  StamperLegacyDTO.JSON_PROPERTY_INCLUDE_TEXT
})
@JsonTypeName("StamperLegacyDTO")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-03-04T11:20:43.685+01:00[Europe/Paris]")
public class StamperLegacyDTO {
  public static final String JSON_PROPERTY_INCLUDE_Q_R_CODE = "includeQRCode";
  private Boolean includeQRCode;

  public static final String JSON_PROPERTY_INCLUDE_BAR_CODE = "includeBarCode";
  private Boolean includeBarCode;

  public static final String JSON_PROPERTY_INCLUDE_VERIFICATION_U_R_L = "includeVerificationURL";
  private Boolean includeVerificationURL;

  public static final String JSON_PROPERTY_INCLUDE_TEXT = "includeText";
  private Boolean includeText;

  public StamperLegacyDTO() { 
  }

  public StamperLegacyDTO includeQRCode(Boolean includeQRCode) {
    
    this.includeQRCode = includeQRCode;
    return this;
  }

   /**
   * Get includeQRCode
   * @return includeQRCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_INCLUDE_Q_R_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getIncludeQRCode() {
    return includeQRCode;
  }


  @JsonProperty(JSON_PROPERTY_INCLUDE_Q_R_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIncludeQRCode(Boolean includeQRCode) {
    this.includeQRCode = includeQRCode;
  }


  public StamperLegacyDTO includeBarCode(Boolean includeBarCode) {
    
    this.includeBarCode = includeBarCode;
    return this;
  }

   /**
   * Get includeBarCode
   * @return includeBarCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_INCLUDE_BAR_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getIncludeBarCode() {
    return includeBarCode;
  }


  @JsonProperty(JSON_PROPERTY_INCLUDE_BAR_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIncludeBarCode(Boolean includeBarCode) {
    this.includeBarCode = includeBarCode;
  }


  public StamperLegacyDTO includeVerificationURL(Boolean includeVerificationURL) {
    
    this.includeVerificationURL = includeVerificationURL;
    return this;
  }

   /**
   * Get includeVerificationURL
   * @return includeVerificationURL
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_INCLUDE_VERIFICATION_U_R_L)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getIncludeVerificationURL() {
    return includeVerificationURL;
  }


  @JsonProperty(JSON_PROPERTY_INCLUDE_VERIFICATION_U_R_L)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIncludeVerificationURL(Boolean includeVerificationURL) {
    this.includeVerificationURL = includeVerificationURL;
  }


  public StamperLegacyDTO includeText(Boolean includeText) {
    
    this.includeText = includeText;
    return this;
  }

   /**
   * Get includeText
   * @return includeText
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_INCLUDE_TEXT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getIncludeText() {
    return includeText;
  }


  @JsonProperty(JSON_PROPERTY_INCLUDE_TEXT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIncludeText(Boolean includeText) {
    this.includeText = includeText;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StamperLegacyDTO stamperLegacyDTO = (StamperLegacyDTO) o;
    return Objects.equals(this.includeQRCode, stamperLegacyDTO.includeQRCode) &&
        Objects.equals(this.includeBarCode, stamperLegacyDTO.includeBarCode) &&
        Objects.equals(this.includeVerificationURL, stamperLegacyDTO.includeVerificationURL) &&
        Objects.equals(this.includeText, stamperLegacyDTO.includeText);
  }

  @Override
  public int hashCode() {
    return Objects.hash(includeQRCode, includeBarCode, includeVerificationURL, includeText);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StamperLegacyDTO {\n");
    sb.append("    includeQRCode: ").append(toIndentedString(includeQRCode)).append("\n");
    sb.append("    includeBarCode: ").append(toIndentedString(includeBarCode)).append("\n");
    sb.append("    includeVerificationURL: ").append(toIndentedString(includeVerificationURL)).append("\n");
    sb.append("    includeText: ").append(toIndentedString(includeText)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

