/*
 * Viafirma API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.3.29-r83-596fbc1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * StamperDTOTimeZone
 */
@JsonPropertyOrder({
  StamperDTOTimeZone.JSON_PROPERTY_DISPLAY_NAME,
  StamperDTOTimeZone.JSON_PROPERTY_ID,
  StamperDTOTimeZone.JSON_PROPERTY_DSTSAVINGS,
  StamperDTOTimeZone.JSON_PROPERTY_RAW_OFFSET
})
@JsonTypeName("StamperDTO_timeZone")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-03-04T11:20:43.685+01:00[Europe/Paris]")
public class StamperDTOTimeZone {
  public static final String JSON_PROPERTY_DISPLAY_NAME = "displayName";
  private String displayName;

  public static final String JSON_PROPERTY_ID = "id";
  private String id;

  public static final String JSON_PROPERTY_DSTSAVINGS = "dstsavings";
  private Integer dstsavings;

  public static final String JSON_PROPERTY_RAW_OFFSET = "rawOffset";
  private Integer rawOffset;

  public StamperDTOTimeZone() { 
  }

  public StamperDTOTimeZone displayName(String displayName) {
    
    this.displayName = displayName;
    return this;
  }

   /**
   * Get displayName
   * @return displayName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_DISPLAY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDisplayName() {
    return displayName;
  }


  @JsonProperty(JSON_PROPERTY_DISPLAY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDisplayName(String displayName) {
    this.displayName = displayName;
  }


  public StamperDTOTimeZone id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(String id) {
    this.id = id;
  }


  public StamperDTOTimeZone dstsavings(Integer dstsavings) {
    
    this.dstsavings = dstsavings;
    return this;
  }

   /**
   * Get dstsavings
   * @return dstsavings
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_DSTSAVINGS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getDstsavings() {
    return dstsavings;
  }


  @JsonProperty(JSON_PROPERTY_DSTSAVINGS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDstsavings(Integer dstsavings) {
    this.dstsavings = dstsavings;
  }


  public StamperDTOTimeZone rawOffset(Integer rawOffset) {
    
    this.rawOffset = rawOffset;
    return this;
  }

   /**
   * Get rawOffset
   * @return rawOffset
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_RAW_OFFSET)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getRawOffset() {
    return rawOffset;
  }


  @JsonProperty(JSON_PROPERTY_RAW_OFFSET)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRawOffset(Integer rawOffset) {
    this.rawOffset = rawOffset;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StamperDTOTimeZone stamperDTOTimeZone = (StamperDTOTimeZone) o;
    return Objects.equals(this.displayName, stamperDTOTimeZone.displayName) &&
        Objects.equals(this.id, stamperDTOTimeZone.id) &&
        Objects.equals(this.dstsavings, stamperDTOTimeZone.dstsavings) &&
        Objects.equals(this.rawOffset, stamperDTOTimeZone.rawOffset);
  }

  @Override
  public int hashCode() {
    return Objects.hash(displayName, id, dstsavings, rawOffset);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StamperDTOTimeZone {\n");
    sb.append("    displayName: ").append(toIndentedString(displayName)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    dstsavings: ").append(toIndentedString(dstsavings)).append("\n");
    sb.append("    rawOffset: ").append(toIndentedString(rawOffset)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

