/*
 * Viafirma API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.3.29-r83-596fbc1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.VerifierSignatureDTO;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ValidationFileResponseDTO
 */
@JsonPropertyOrder({
  ValidationFileResponseDTO.JSON_PROPERTY_OPERATION_CODE,
  ValidationFileResponseDTO.JSON_PROPERTY_INTERNAL_OPERATION_CODE,
  ValidationFileResponseDTO.JSON_PROPERTY_FILENAME,
  ValidationFileResponseDTO.JSON_PROPERTY_SIGNATURE_VALID,
  ValidationFileResponseDTO.JSON_PROPERTY_VALIDATION_TIME,
  ValidationFileResponseDTO.JSON_PROPERTY_SIGNATURES_COUNT,
  ValidationFileResponseDTO.JSON_PROPERTY_VALID_SIGNATURES_COUNT,
  ValidationFileResponseDTO.JSON_PROPERTY_ERROR_CODE,
  ValidationFileResponseDTO.JSON_PROPERTY_ERROR_MESSAGE,
  ValidationFileResponseDTO.JSON_PROPERTY_TRAIL_LINK,
  ValidationFileResponseDTO.JSON_PROPERTY_VERIFIED_SIGNATURES
})
@JsonTypeName("ValidationFileResponseDTO")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-03-04T11:20:43.685+01:00[Europe/Paris]")
public class ValidationFileResponseDTO {
  public static final String JSON_PROPERTY_OPERATION_CODE = "operationCode";
  private String operationCode;

  public static final String JSON_PROPERTY_INTERNAL_OPERATION_CODE = "internalOperationCode";
  private String internalOperationCode;

  public static final String JSON_PROPERTY_FILENAME = "filename";
  private String filename;

  public static final String JSON_PROPERTY_SIGNATURE_VALID = "signatureValid";
  private Boolean signatureValid;

  public static final String JSON_PROPERTY_VALIDATION_TIME = "validationTime";
  private OffsetDateTime validationTime;

  public static final String JSON_PROPERTY_SIGNATURES_COUNT = "signaturesCount";
  private Integer signaturesCount;

  public static final String JSON_PROPERTY_VALID_SIGNATURES_COUNT = "validSignaturesCount";
  private Integer validSignaturesCount;

  public static final String JSON_PROPERTY_ERROR_CODE = "errorCode";
  private String errorCode;

  public static final String JSON_PROPERTY_ERROR_MESSAGE = "errorMessage";
  private String errorMessage;

  public static final String JSON_PROPERTY_TRAIL_LINK = "trailLink";
  private String trailLink;

  public static final String JSON_PROPERTY_VERIFIED_SIGNATURES = "verifiedSignatures";
  private List<VerifierSignatureDTO> verifiedSignatures = null;

  public ValidationFileResponseDTO() { 
  }

  public ValidationFileResponseDTO operationCode(String operationCode) {
    
    this.operationCode = operationCode;
    return this;
  }

   /**
   * Get operationCode
   * @return operationCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_OPERATION_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getOperationCode() {
    return operationCode;
  }


  @JsonProperty(JSON_PROPERTY_OPERATION_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOperationCode(String operationCode) {
    this.operationCode = operationCode;
  }


  public ValidationFileResponseDTO internalOperationCode(String internalOperationCode) {
    
    this.internalOperationCode = internalOperationCode;
    return this;
  }

   /**
   * Get internalOperationCode
   * @return internalOperationCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_INTERNAL_OPERATION_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getInternalOperationCode() {
    return internalOperationCode;
  }


  @JsonProperty(JSON_PROPERTY_INTERNAL_OPERATION_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setInternalOperationCode(String internalOperationCode) {
    this.internalOperationCode = internalOperationCode;
  }


  public ValidationFileResponseDTO filename(String filename) {
    
    this.filename = filename;
    return this;
  }

   /**
   * Get filename
   * @return filename
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_FILENAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFilename() {
    return filename;
  }


  @JsonProperty(JSON_PROPERTY_FILENAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFilename(String filename) {
    this.filename = filename;
  }


  public ValidationFileResponseDTO signatureValid(Boolean signatureValid) {
    
    this.signatureValid = signatureValid;
    return this;
  }

   /**
   * Get signatureValid
   * @return signatureValid
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SIGNATURE_VALID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getSignatureValid() {
    return signatureValid;
  }


  @JsonProperty(JSON_PROPERTY_SIGNATURE_VALID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSignatureValid(Boolean signatureValid) {
    this.signatureValid = signatureValid;
  }


  public ValidationFileResponseDTO validationTime(OffsetDateTime validationTime) {
    
    this.validationTime = validationTime;
    return this;
  }

   /**
   * Get validationTime
   * @return validationTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_VALIDATION_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getValidationTime() {
    return validationTime;
  }


  @JsonProperty(JSON_PROPERTY_VALIDATION_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setValidationTime(OffsetDateTime validationTime) {
    this.validationTime = validationTime;
  }


  public ValidationFileResponseDTO signaturesCount(Integer signaturesCount) {
    
    this.signaturesCount = signaturesCount;
    return this;
  }

   /**
   * Get signaturesCount
   * @return signaturesCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SIGNATURES_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getSignaturesCount() {
    return signaturesCount;
  }


  @JsonProperty(JSON_PROPERTY_SIGNATURES_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSignaturesCount(Integer signaturesCount) {
    this.signaturesCount = signaturesCount;
  }


  public ValidationFileResponseDTO validSignaturesCount(Integer validSignaturesCount) {
    
    this.validSignaturesCount = validSignaturesCount;
    return this;
  }

   /**
   * Get validSignaturesCount
   * @return validSignaturesCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_VALID_SIGNATURES_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getValidSignaturesCount() {
    return validSignaturesCount;
  }


  @JsonProperty(JSON_PROPERTY_VALID_SIGNATURES_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setValidSignaturesCount(Integer validSignaturesCount) {
    this.validSignaturesCount = validSignaturesCount;
  }


  public ValidationFileResponseDTO errorCode(String errorCode) {
    
    this.errorCode = errorCode;
    return this;
  }

   /**
   * Get errorCode
   * @return errorCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ERROR_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getErrorCode() {
    return errorCode;
  }


  @JsonProperty(JSON_PROPERTY_ERROR_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setErrorCode(String errorCode) {
    this.errorCode = errorCode;
  }


  public ValidationFileResponseDTO errorMessage(String errorMessage) {
    
    this.errorMessage = errorMessage;
    return this;
  }

   /**
   * Get errorMessage
   * @return errorMessage
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ERROR_MESSAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getErrorMessage() {
    return errorMessage;
  }


  @JsonProperty(JSON_PROPERTY_ERROR_MESSAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setErrorMessage(String errorMessage) {
    this.errorMessage = errorMessage;
  }


  public ValidationFileResponseDTO trailLink(String trailLink) {
    
    this.trailLink = trailLink;
    return this;
  }

   /**
   * Get trailLink
   * @return trailLink
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TRAIL_LINK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTrailLink() {
    return trailLink;
  }


  @JsonProperty(JSON_PROPERTY_TRAIL_LINK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTrailLink(String trailLink) {
    this.trailLink = trailLink;
  }


  public ValidationFileResponseDTO verifiedSignatures(List<VerifierSignatureDTO> verifiedSignatures) {
    
    this.verifiedSignatures = verifiedSignatures;
    return this;
  }

  public ValidationFileResponseDTO addVerifiedSignaturesItem(VerifierSignatureDTO verifiedSignaturesItem) {
    if (this.verifiedSignatures == null) {
      this.verifiedSignatures = new ArrayList<>();
    }
    this.verifiedSignatures.add(verifiedSignaturesItem);
    return this;
  }

   /**
   * Get verifiedSignatures
   * @return verifiedSignatures
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_VERIFIED_SIGNATURES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<VerifierSignatureDTO> getVerifiedSignatures() {
    return verifiedSignatures;
  }


  @JsonProperty(JSON_PROPERTY_VERIFIED_SIGNATURES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVerifiedSignatures(List<VerifierSignatureDTO> verifiedSignatures) {
    this.verifiedSignatures = verifiedSignatures;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ValidationFileResponseDTO validationFileResponseDTO = (ValidationFileResponseDTO) o;
    return Objects.equals(this.operationCode, validationFileResponseDTO.operationCode) &&
        Objects.equals(this.internalOperationCode, validationFileResponseDTO.internalOperationCode) &&
        Objects.equals(this.filename, validationFileResponseDTO.filename) &&
        Objects.equals(this.signatureValid, validationFileResponseDTO.signatureValid) &&
        Objects.equals(this.validationTime, validationFileResponseDTO.validationTime) &&
        Objects.equals(this.signaturesCount, validationFileResponseDTO.signaturesCount) &&
        Objects.equals(this.validSignaturesCount, validationFileResponseDTO.validSignaturesCount) &&
        Objects.equals(this.errorCode, validationFileResponseDTO.errorCode) &&
        Objects.equals(this.errorMessage, validationFileResponseDTO.errorMessage) &&
        Objects.equals(this.trailLink, validationFileResponseDTO.trailLink) &&
        Objects.equals(this.verifiedSignatures, validationFileResponseDTO.verifiedSignatures);
  }

  @Override
  public int hashCode() {
    return Objects.hash(operationCode, internalOperationCode, filename, signatureValid, validationTime, signaturesCount, validSignaturesCount, errorCode, errorMessage, trailLink, verifiedSignatures);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ValidationFileResponseDTO {\n");
    sb.append("    operationCode: ").append(toIndentedString(operationCode)).append("\n");
    sb.append("    internalOperationCode: ").append(toIndentedString(internalOperationCode)).append("\n");
    sb.append("    filename: ").append(toIndentedString(filename)).append("\n");
    sb.append("    signatureValid: ").append(toIndentedString(signatureValid)).append("\n");
    sb.append("    validationTime: ").append(toIndentedString(validationTime)).append("\n");
    sb.append("    signaturesCount: ").append(toIndentedString(signaturesCount)).append("\n");
    sb.append("    validSignaturesCount: ").append(toIndentedString(validSignaturesCount)).append("\n");
    sb.append("    errorCode: ").append(toIndentedString(errorCode)).append("\n");
    sb.append("    errorMessage: ").append(toIndentedString(errorMessage)).append("\n");
    sb.append("    trailLink: ").append(toIndentedString(trailLink)).append("\n");
    sb.append("    verifiedSignatures: ").append(toIndentedString(verifiedSignatures)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

