/*
 * Viafirma API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.3.29-r83-596fbc1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ValidateCertificateRequestDTO
 */
@JsonPropertyOrder({
  ValidateCertificateRequestDTO.JSON_PROPERTY_CERTIFICATE_BASE64,
  ValidateCertificateRequestDTO.JSON_PROPERTY_VALIDATION_TYPE
})
@JsonTypeName("ValidateCertificateRequestDTO")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-03-04T11:20:43.685+01:00[Europe/Paris]")
public class ValidateCertificateRequestDTO {
  public static final String JSON_PROPERTY_CERTIFICATE_BASE64 = "certificateBase64";
  private String certificateBase64;

  /**
   * Gets or Sets validationType
   */
  public enum ValidationTypeEnum {
    ONLINE("ONLINE"),
    
    ONLINE_WITH_CACHE("ONLINE_WITH_CACHE"),
    
    CRL("CRL"),
    
    CRL_CACHE("CRL_CACHE"),
    
    OCSP("OCSP"),
    
    NONE("NONE");

    private String value;

    ValidationTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ValidationTypeEnum fromValue(String value) {
      for (ValidationTypeEnum b : ValidationTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_VALIDATION_TYPE = "validationType";
  private ValidationTypeEnum validationType;

  public ValidateCertificateRequestDTO() { 
  }

  public ValidateCertificateRequestDTO certificateBase64(String certificateBase64) {
    
    this.certificateBase64 = certificateBase64;
    return this;
  }

   /**
   * Get certificateBase64
   * @return certificateBase64
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CERTIFICATE_BASE64)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCertificateBase64() {
    return certificateBase64;
  }


  @JsonProperty(JSON_PROPERTY_CERTIFICATE_BASE64)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCertificateBase64(String certificateBase64) {
    this.certificateBase64 = certificateBase64;
  }


  public ValidateCertificateRequestDTO validationType(ValidationTypeEnum validationType) {
    
    this.validationType = validationType;
    return this;
  }

   /**
   * Get validationType
   * @return validationType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_VALIDATION_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ValidationTypeEnum getValidationType() {
    return validationType;
  }


  @JsonProperty(JSON_PROPERTY_VALIDATION_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setValidationType(ValidationTypeEnum validationType) {
    this.validationType = validationType;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ValidateCertificateRequestDTO validateCertificateRequestDTO = (ValidateCertificateRequestDTO) o;
    return Objects.equals(this.certificateBase64, validateCertificateRequestDTO.certificateBase64) &&
        Objects.equals(this.validationType, validateCertificateRequestDTO.validationType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(certificateBase64, validationType);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ValidateCertificateRequestDTO {\n");
    sb.append("    certificateBase64: ").append(toIndentedString(certificateBase64)).append("\n");
    sb.append("    validationType: ").append(toIndentedString(validationType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

