/*
 * Viafirma API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.3.29-r83-596fbc1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Validate hash signature
 */
@ApiModel(description = "Validate hash signature")
@JsonPropertyOrder({
  ValidationHashRequestDTO.JSON_PROPERTY_SIGNED_FILE_BASE64,
  ValidationHashRequestDTO.JSON_PROPERTY_SIGNED_FILE,
  ValidationHashRequestDTO.JSON_PROPERTY_INTERNAL_OPERATION_CODE,
  ValidationHashRequestDTO.JSON_PROPERTY_FILENAME,
  ValidationHashRequestDTO.JSON_PROPERTY_SHOW_EXTENDED_INFO,
  ValidationHashRequestDTO.JSON_PROPERTY_TRAIL_ENABLED,
  ValidationHashRequestDTO.JSON_PROPERTY_ORIGINAL_CONTENT
})
@JsonTypeName("ValidationHashRequestDTO")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-03-04T11:20:43.685+01:00[Europe/Paris]")
public class ValidationHashRequestDTO {
  public static final String JSON_PROPERTY_SIGNED_FILE_BASE64 = "signedFileBase64";
  private String signedFileBase64;

  public static final String JSON_PROPERTY_SIGNED_FILE = "signedFile";
  private String signedFile;

  public static final String JSON_PROPERTY_INTERNAL_OPERATION_CODE = "internalOperationCode";
  private String internalOperationCode;

  public static final String JSON_PROPERTY_FILENAME = "filename";
  private String filename;

  public static final String JSON_PROPERTY_SHOW_EXTENDED_INFO = "showExtendedInfo";
  private Boolean showExtendedInfo = false;

  public static final String JSON_PROPERTY_TRAIL_ENABLED = "trailEnabled";
  private Boolean trailEnabled = false;

  public static final String JSON_PROPERTY_ORIGINAL_CONTENT = "originalContent";
  private String originalContent;

  public ValidationHashRequestDTO() { 
  }

  public ValidationHashRequestDTO signedFileBase64(String signedFileBase64) {
    
    this.signedFileBase64 = signedFileBase64;
    return this;
  }

   /**
   * Signed document in base64 format
   * @return signedFileBase64
   * @deprecated
  **/
  @Deprecated
  @javax.annotation.Nullable
  @ApiModelProperty(example = "SGVsbG8sIFdvcmxkIQ==", value = "Signed document in base64 format")
  @JsonProperty(JSON_PROPERTY_SIGNED_FILE_BASE64)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSignedFileBase64() {
    return signedFileBase64;
  }


  @JsonProperty(JSON_PROPERTY_SIGNED_FILE_BASE64)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSignedFileBase64(String signedFileBase64) {
    this.signedFileBase64 = signedFileBase64;
  }


  public ValidationHashRequestDTO signedFile(String signedFile) {
    
    this.signedFile = signedFile;
    return this;
  }

   /**
   * Reference to signed document
   * @return signedFile
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "https://www.example.com/signed_example.pdf", value = "Reference to signed document")
  @JsonProperty(JSON_PROPERTY_SIGNED_FILE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSignedFile() {
    return signedFile;
  }


  @JsonProperty(JSON_PROPERTY_SIGNED_FILE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSignedFile(String signedFile) {
    this.signedFile = signedFile;
  }


  public ValidationHashRequestDTO internalOperationCode(String internalOperationCode) {
    
    this.internalOperationCode = internalOperationCode;
    return this;
  }

   /**
   * Identifier of the operation in the system that consumes the service
   * @return internalOperationCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "CKRD1720109848365R001", value = "Identifier of the operation in the system that consumes the service")
  @JsonProperty(JSON_PROPERTY_INTERNAL_OPERATION_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getInternalOperationCode() {
    return internalOperationCode;
  }


  @JsonProperty(JSON_PROPERTY_INTERNAL_OPERATION_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setInternalOperationCode(String internalOperationCode) {
    this.internalOperationCode = internalOperationCode;
  }


  public ValidationHashRequestDTO filename(String filename) {
    
    this.filename = filename;
    return this;
  }

   /**
   * Name of signed document
   * @return filename
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "signed_example.pdf", value = "Name of signed document")
  @JsonProperty(JSON_PROPERTY_FILENAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFilename() {
    return filename;
  }


  @JsonProperty(JSON_PROPERTY_FILENAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFilename(String filename) {
    this.filename = filename;
  }


  public ValidationHashRequestDTO showExtendedInfo(Boolean showExtendedInfo) {
    
    this.showExtendedInfo = showExtendedInfo;
    return this;
  }

   /**
   * Name of signed document
   * @return showExtendedInfo
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "false", value = "Name of signed document")
  @JsonProperty(JSON_PROPERTY_SHOW_EXTENDED_INFO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getShowExtendedInfo() {
    return showExtendedInfo;
  }


  @JsonProperty(JSON_PROPERTY_SHOW_EXTENDED_INFO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setShowExtendedInfo(Boolean showExtendedInfo) {
    this.showExtendedInfo = showExtendedInfo;
  }


  public ValidationHashRequestDTO trailEnabled(Boolean trailEnabled) {
    
    this.trailEnabled = trailEnabled;
    return this;
  }

   /**
   * Enable create validation audit trail
   * @return trailEnabled
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "false", value = "Enable create validation audit trail")
  @JsonProperty(JSON_PROPERTY_TRAIL_ENABLED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getTrailEnabled() {
    return trailEnabled;
  }


  @JsonProperty(JSON_PROPERTY_TRAIL_ENABLED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTrailEnabled(Boolean trailEnabled) {
    this.trailEnabled = trailEnabled;
  }


  public ValidationHashRequestDTO originalContent(String originalContent) {
    
    this.originalContent = originalContent;
    return this;
  }

   /**
   * Reference to original signed content, as Base64 or URL
   * @return originalContent
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "https://www.example.com/original.pdf", required = true, value = "Reference to original signed content, as Base64 or URL")
  @JsonProperty(JSON_PROPERTY_ORIGINAL_CONTENT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getOriginalContent() {
    return originalContent;
  }


  @JsonProperty(JSON_PROPERTY_ORIGINAL_CONTENT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setOriginalContent(String originalContent) {
    this.originalContent = originalContent;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ValidationHashRequestDTO validationHashRequestDTO = (ValidationHashRequestDTO) o;
    return Objects.equals(this.signedFileBase64, validationHashRequestDTO.signedFileBase64) &&
        Objects.equals(this.signedFile, validationHashRequestDTO.signedFile) &&
        Objects.equals(this.internalOperationCode, validationHashRequestDTO.internalOperationCode) &&
        Objects.equals(this.filename, validationHashRequestDTO.filename) &&
        Objects.equals(this.showExtendedInfo, validationHashRequestDTO.showExtendedInfo) &&
        Objects.equals(this.trailEnabled, validationHashRequestDTO.trailEnabled) &&
        Objects.equals(this.originalContent, validationHashRequestDTO.originalContent);
  }

  @Override
  public int hashCode() {
    return Objects.hash(signedFileBase64, signedFile, internalOperationCode, filename, showExtendedInfo, trailEnabled, originalContent);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ValidationHashRequestDTO {\n");
    sb.append("    signedFileBase64: ").append(toIndentedString(signedFileBase64)).append("\n");
    sb.append("    signedFile: ").append(toIndentedString(signedFile)).append("\n");
    sb.append("    internalOperationCode: ").append(toIndentedString(internalOperationCode)).append("\n");
    sb.append("    filename: ").append(toIndentedString(filename)).append("\n");
    sb.append("    showExtendedInfo: ").append(toIndentedString(showExtendedInfo)).append("\n");
    sb.append("    trailEnabled: ").append(toIndentedString(trailEnabled)).append("\n");
    sb.append("    originalContent: ").append(toIndentedString(originalContent)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

