/*
 * Viafirma API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.3.29-r83-596fbc1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ValidateCertificateResponseDTO
 */
@JsonPropertyOrder({
  ValidateCertificateResponseDTO.JSON_PROPERTY_OPERATION_CODE,
  ValidateCertificateResponseDTO.JSON_PROPERTY_STATUS,
  ValidateCertificateResponseDTO.JSON_PROPERTY_NOT_VALID_CERTIFICATE_ERROR_CODE,
  ValidateCertificateResponseDTO.JSON_PROPERTY_NOT_VALID_CERTIFICATE_ERROR_DESCRIPTION
})
@JsonTypeName("ValidateCertificateResponseDTO")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-03-04T11:20:43.685+01:00[Europe/Paris]")
public class ValidateCertificateResponseDTO {
  public static final String JSON_PROPERTY_OPERATION_CODE = "operationCode";
  private String operationCode;

  public static final String JSON_PROPERTY_STATUS = "status";
  private String status;

  public static final String JSON_PROPERTY_NOT_VALID_CERTIFICATE_ERROR_CODE = "notValidCertificateErrorCode";
  private Integer notValidCertificateErrorCode;

  public static final String JSON_PROPERTY_NOT_VALID_CERTIFICATE_ERROR_DESCRIPTION = "notValidCertificateErrorDescription";
  private String notValidCertificateErrorDescription;

  public ValidateCertificateResponseDTO() { 
  }

  public ValidateCertificateResponseDTO operationCode(String operationCode) {
    
    this.operationCode = operationCode;
    return this;
  }

   /**
   * Get operationCode
   * @return operationCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_OPERATION_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getOperationCode() {
    return operationCode;
  }


  @JsonProperty(JSON_PROPERTY_OPERATION_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOperationCode(String operationCode) {
    this.operationCode = operationCode;
  }


  public ValidateCertificateResponseDTO status(String status) {
    
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getStatus() {
    return status;
  }


  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStatus(String status) {
    this.status = status;
  }


  public ValidateCertificateResponseDTO notValidCertificateErrorCode(Integer notValidCertificateErrorCode) {
    
    this.notValidCertificateErrorCode = notValidCertificateErrorCode;
    return this;
  }

   /**
   * Get notValidCertificateErrorCode
   * @return notValidCertificateErrorCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_NOT_VALID_CERTIFICATE_ERROR_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getNotValidCertificateErrorCode() {
    return notValidCertificateErrorCode;
  }


  @JsonProperty(JSON_PROPERTY_NOT_VALID_CERTIFICATE_ERROR_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNotValidCertificateErrorCode(Integer notValidCertificateErrorCode) {
    this.notValidCertificateErrorCode = notValidCertificateErrorCode;
  }


  public ValidateCertificateResponseDTO notValidCertificateErrorDescription(String notValidCertificateErrorDescription) {
    
    this.notValidCertificateErrorDescription = notValidCertificateErrorDescription;
    return this;
  }

   /**
   * Get notValidCertificateErrorDescription
   * @return notValidCertificateErrorDescription
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_NOT_VALID_CERTIFICATE_ERROR_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getNotValidCertificateErrorDescription() {
    return notValidCertificateErrorDescription;
  }


  @JsonProperty(JSON_PROPERTY_NOT_VALID_CERTIFICATE_ERROR_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNotValidCertificateErrorDescription(String notValidCertificateErrorDescription) {
    this.notValidCertificateErrorDescription = notValidCertificateErrorDescription;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ValidateCertificateResponseDTO validateCertificateResponseDTO = (ValidateCertificateResponseDTO) o;
    return Objects.equals(this.operationCode, validateCertificateResponseDTO.operationCode) &&
        Objects.equals(this.status, validateCertificateResponseDTO.status) &&
        Objects.equals(this.notValidCertificateErrorCode, validateCertificateResponseDTO.notValidCertificateErrorCode) &&
        Objects.equals(this.notValidCertificateErrorDescription, validateCertificateResponseDTO.notValidCertificateErrorDescription);
  }

  @Override
  public int hashCode() {
    return Objects.hash(operationCode, status, notValidCertificateErrorCode, notValidCertificateErrorDescription);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ValidateCertificateResponseDTO {\n");
    sb.append("    operationCode: ").append(toIndentedString(operationCode)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    notValidCertificateErrorCode: ").append(toIndentedString(notValidCertificateErrorCode)).append("\n");
    sb.append("    notValidCertificateErrorDescription: ").append(toIndentedString(notValidCertificateErrorDescription)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

