/*
 * Viafirma API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.3.29-r83-596fbc1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.VerifierCertificateDTO;
import org.openapitools.client.model.VerifierTimeStampDTO;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * VerifierSignatureDTO
 */
@JsonPropertyOrder({
  VerifierSignatureDTO.JSON_PROPERTY_ID,
  VerifierSignatureDTO.JSON_PROPERTY_FORMAT,
  VerifierSignatureDTO.JSON_PROPERTY_REQUESTED_FORMAT,
  VerifierSignatureDTO.JSON_PROPERTY_ENCRYPTION_ALGORITHM,
  VerifierSignatureDTO.JSON_PROPERTY_DIGEST_ALGORITHM,
  VerifierSignatureDTO.JSON_PROPERTY_LEVEL,
  VerifierSignatureDTO.JSON_PROPERTY_SIGNING_TIME,
  VerifierSignatureDTO.JSON_PROPERTY_VALIDATION_DISABLED,
  VerifierSignatureDTO.JSON_PROPERTY_VALIDATION_STATUS,
  VerifierSignatureDTO.JSON_PROPERTY_INDICATION,
  VerifierSignatureDTO.JSON_PROPERTY_SUB_INDICATION,
  VerifierSignatureDTO.JSON_PROPERTY_POLICY_ID,
  VerifierSignatureDTO.JSON_PROPERTY_ERROR_MESSAGE,
  VerifierSignatureDTO.JSON_PROPERTY_SIGNED_BY,
  VerifierSignatureDTO.JSON_PROPERTY_SIGNER_ID,
  VerifierSignatureDTO.JSON_PROPERTY_ISSUER_BY,
  VerifierSignatureDTO.JSON_PROPERTY_CODE,
  VerifierSignatureDTO.JSON_PROPERTY_CERTIFICATE,
  VerifierSignatureDTO.JSON_PROPERTY_TIME_STAMPS,
  VerifierSignatureDTO.JSON_PROPERTY_UNSIGNED_CHANGES,
  VerifierSignatureDTO.JSON_PROPERTY_REASON,
  VerifierSignatureDTO.JSON_PROPERTY_LOCATION,
  VerifierSignatureDTO.JSON_PROPERTY_QUALIFIED_SIGNATURE,
  VerifierSignatureDTO.JSON_PROPERTY_PKCS7
})
@JsonTypeName("VerifierSignatureDTO")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-03-04T11:20:43.685+01:00[Europe/Paris]")
public class VerifierSignatureDTO {
  public static final String JSON_PROPERTY_ID = "id";
  private String id;

  public static final String JSON_PROPERTY_FORMAT = "format";
  private String format;

  public static final String JSON_PROPERTY_REQUESTED_FORMAT = "requestedFormat";
  private String requestedFormat;

  public static final String JSON_PROPERTY_ENCRYPTION_ALGORITHM = "encryptionAlgorithm";
  private String encryptionAlgorithm;

  public static final String JSON_PROPERTY_DIGEST_ALGORITHM = "digestAlgorithm";
  private String digestAlgorithm;

  public static final String JSON_PROPERTY_LEVEL = "level";
  private String level;

  public static final String JSON_PROPERTY_SIGNING_TIME = "signingTime";
  private OffsetDateTime signingTime;

  public static final String JSON_PROPERTY_VALIDATION_DISABLED = "validationDisabled";
  private Boolean validationDisabled;

  /**
   * Gets or Sets validationStatus
   */
  public enum ValidationStatusEnum {
    VALID("VALID"),
    
    UNKNOWN("UNKNOWN"),
    
    INVALID("INVALID");

    private String value;

    ValidationStatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ValidationStatusEnum fromValue(String value) {
      for (ValidationStatusEnum b : ValidationStatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_VALIDATION_STATUS = "validationStatus";
  private ValidationStatusEnum validationStatus;

  public static final String JSON_PROPERTY_INDICATION = "indication";
  private String indication;

  public static final String JSON_PROPERTY_SUB_INDICATION = "subIndication";
  private String subIndication;

  public static final String JSON_PROPERTY_POLICY_ID = "policyId";
  private String policyId;

  public static final String JSON_PROPERTY_ERROR_MESSAGE = "errorMessage";
  private String errorMessage;

  public static final String JSON_PROPERTY_SIGNED_BY = "signedBy";
  private String signedBy;

  public static final String JSON_PROPERTY_SIGNER_ID = "signerId";
  private String signerId;

  public static final String JSON_PROPERTY_ISSUER_BY = "issuerBy";
  private String issuerBy;

  public static final String JSON_PROPERTY_CODE = "code";
  private String code;

  public static final String JSON_PROPERTY_CERTIFICATE = "certificate";
  private VerifierCertificateDTO certificate;

  public static final String JSON_PROPERTY_TIME_STAMPS = "timeStamps";
  private List<VerifierTimeStampDTO> timeStamps = null;

  public static final String JSON_PROPERTY_UNSIGNED_CHANGES = "unsignedChanges";
  private Boolean unsignedChanges;

  public static final String JSON_PROPERTY_REASON = "reason";
  private String reason;

  public static final String JSON_PROPERTY_LOCATION = "location";
  private String location;

  public static final String JSON_PROPERTY_QUALIFIED_SIGNATURE = "qualifiedSignature";
  private Boolean qualifiedSignature;

  public static final String JSON_PROPERTY_PKCS7 = "pkcs7";
  private Boolean pkcs7;

  public VerifierSignatureDTO() { 
  }

  public VerifierSignatureDTO id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(String id) {
    this.id = id;
  }


  public VerifierSignatureDTO format(String format) {
    
    this.format = format;
    return this;
  }

   /**
   * Get format
   * @return format
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_FORMAT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFormat() {
    return format;
  }


  @JsonProperty(JSON_PROPERTY_FORMAT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFormat(String format) {
    this.format = format;
  }


  public VerifierSignatureDTO requestedFormat(String requestedFormat) {
    
    this.requestedFormat = requestedFormat;
    return this;
  }

   /**
   * Get requestedFormat
   * @return requestedFormat
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_REQUESTED_FORMAT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getRequestedFormat() {
    return requestedFormat;
  }


  @JsonProperty(JSON_PROPERTY_REQUESTED_FORMAT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRequestedFormat(String requestedFormat) {
    this.requestedFormat = requestedFormat;
  }


  public VerifierSignatureDTO encryptionAlgorithm(String encryptionAlgorithm) {
    
    this.encryptionAlgorithm = encryptionAlgorithm;
    return this;
  }

   /**
   * Get encryptionAlgorithm
   * @return encryptionAlgorithm
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ENCRYPTION_ALGORITHM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getEncryptionAlgorithm() {
    return encryptionAlgorithm;
  }


  @JsonProperty(JSON_PROPERTY_ENCRYPTION_ALGORITHM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEncryptionAlgorithm(String encryptionAlgorithm) {
    this.encryptionAlgorithm = encryptionAlgorithm;
  }


  public VerifierSignatureDTO digestAlgorithm(String digestAlgorithm) {
    
    this.digestAlgorithm = digestAlgorithm;
    return this;
  }

   /**
   * Get digestAlgorithm
   * @return digestAlgorithm
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_DIGEST_ALGORITHM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDigestAlgorithm() {
    return digestAlgorithm;
  }


  @JsonProperty(JSON_PROPERTY_DIGEST_ALGORITHM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDigestAlgorithm(String digestAlgorithm) {
    this.digestAlgorithm = digestAlgorithm;
  }


  public VerifierSignatureDTO level(String level) {
    
    this.level = level;
    return this;
  }

   /**
   * Get level
   * @return level
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_LEVEL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLevel() {
    return level;
  }


  @JsonProperty(JSON_PROPERTY_LEVEL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLevel(String level) {
    this.level = level;
  }


  public VerifierSignatureDTO signingTime(OffsetDateTime signingTime) {
    
    this.signingTime = signingTime;
    return this;
  }

   /**
   * Get signingTime
   * @return signingTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SIGNING_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getSigningTime() {
    return signingTime;
  }


  @JsonProperty(JSON_PROPERTY_SIGNING_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSigningTime(OffsetDateTime signingTime) {
    this.signingTime = signingTime;
  }


  public VerifierSignatureDTO validationDisabled(Boolean validationDisabled) {
    
    this.validationDisabled = validationDisabled;
    return this;
  }

   /**
   * Get validationDisabled
   * @return validationDisabled
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_VALIDATION_DISABLED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getValidationDisabled() {
    return validationDisabled;
  }


  @JsonProperty(JSON_PROPERTY_VALIDATION_DISABLED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setValidationDisabled(Boolean validationDisabled) {
    this.validationDisabled = validationDisabled;
  }


  public VerifierSignatureDTO validationStatus(ValidationStatusEnum validationStatus) {
    
    this.validationStatus = validationStatus;
    return this;
  }

   /**
   * Get validationStatus
   * @return validationStatus
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_VALIDATION_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ValidationStatusEnum getValidationStatus() {
    return validationStatus;
  }


  @JsonProperty(JSON_PROPERTY_VALIDATION_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setValidationStatus(ValidationStatusEnum validationStatus) {
    this.validationStatus = validationStatus;
  }


  public VerifierSignatureDTO indication(String indication) {
    
    this.indication = indication;
    return this;
  }

   /**
   * Get indication
   * @return indication
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_INDICATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getIndication() {
    return indication;
  }


  @JsonProperty(JSON_PROPERTY_INDICATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIndication(String indication) {
    this.indication = indication;
  }


  public VerifierSignatureDTO subIndication(String subIndication) {
    
    this.subIndication = subIndication;
    return this;
  }

   /**
   * Get subIndication
   * @return subIndication
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SUB_INDICATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSubIndication() {
    return subIndication;
  }


  @JsonProperty(JSON_PROPERTY_SUB_INDICATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSubIndication(String subIndication) {
    this.subIndication = subIndication;
  }


  public VerifierSignatureDTO policyId(String policyId) {
    
    this.policyId = policyId;
    return this;
  }

   /**
   * Get policyId
   * @return policyId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_POLICY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPolicyId() {
    return policyId;
  }


  @JsonProperty(JSON_PROPERTY_POLICY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPolicyId(String policyId) {
    this.policyId = policyId;
  }


  public VerifierSignatureDTO errorMessage(String errorMessage) {
    
    this.errorMessage = errorMessage;
    return this;
  }

   /**
   * Get errorMessage
   * @return errorMessage
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ERROR_MESSAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getErrorMessage() {
    return errorMessage;
  }


  @JsonProperty(JSON_PROPERTY_ERROR_MESSAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setErrorMessage(String errorMessage) {
    this.errorMessage = errorMessage;
  }


  public VerifierSignatureDTO signedBy(String signedBy) {
    
    this.signedBy = signedBy;
    return this;
  }

   /**
   * Get signedBy
   * @return signedBy
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SIGNED_BY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSignedBy() {
    return signedBy;
  }


  @JsonProperty(JSON_PROPERTY_SIGNED_BY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSignedBy(String signedBy) {
    this.signedBy = signedBy;
  }


  public VerifierSignatureDTO signerId(String signerId) {
    
    this.signerId = signerId;
    return this;
  }

   /**
   * Get signerId
   * @return signerId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SIGNER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSignerId() {
    return signerId;
  }


  @JsonProperty(JSON_PROPERTY_SIGNER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSignerId(String signerId) {
    this.signerId = signerId;
  }


  public VerifierSignatureDTO issuerBy(String issuerBy) {
    
    this.issuerBy = issuerBy;
    return this;
  }

   /**
   * Get issuerBy
   * @return issuerBy
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ISSUER_BY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getIssuerBy() {
    return issuerBy;
  }


  @JsonProperty(JSON_PROPERTY_ISSUER_BY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIssuerBy(String issuerBy) {
    this.issuerBy = issuerBy;
  }


  public VerifierSignatureDTO code(String code) {
    
    this.code = code;
    return this;
  }

   /**
   * Get code
   * @return code
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCode() {
    return code;
  }


  @JsonProperty(JSON_PROPERTY_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCode(String code) {
    this.code = code;
  }


  public VerifierSignatureDTO certificate(VerifierCertificateDTO certificate) {
    
    this.certificate = certificate;
    return this;
  }

   /**
   * Get certificate
   * @return certificate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CERTIFICATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public VerifierCertificateDTO getCertificate() {
    return certificate;
  }


  @JsonProperty(JSON_PROPERTY_CERTIFICATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCertificate(VerifierCertificateDTO certificate) {
    this.certificate = certificate;
  }


  public VerifierSignatureDTO timeStamps(List<VerifierTimeStampDTO> timeStamps) {
    
    this.timeStamps = timeStamps;
    return this;
  }

  public VerifierSignatureDTO addTimeStampsItem(VerifierTimeStampDTO timeStampsItem) {
    if (this.timeStamps == null) {
      this.timeStamps = new ArrayList<>();
    }
    this.timeStamps.add(timeStampsItem);
    return this;
  }

   /**
   * Get timeStamps
   * @return timeStamps
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TIME_STAMPS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<VerifierTimeStampDTO> getTimeStamps() {
    return timeStamps;
  }


  @JsonProperty(JSON_PROPERTY_TIME_STAMPS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTimeStamps(List<VerifierTimeStampDTO> timeStamps) {
    this.timeStamps = timeStamps;
  }


  public VerifierSignatureDTO unsignedChanges(Boolean unsignedChanges) {
    
    this.unsignedChanges = unsignedChanges;
    return this;
  }

   /**
   * Get unsignedChanges
   * @return unsignedChanges
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_UNSIGNED_CHANGES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getUnsignedChanges() {
    return unsignedChanges;
  }


  @JsonProperty(JSON_PROPERTY_UNSIGNED_CHANGES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUnsignedChanges(Boolean unsignedChanges) {
    this.unsignedChanges = unsignedChanges;
  }


  public VerifierSignatureDTO reason(String reason) {
    
    this.reason = reason;
    return this;
  }

   /**
   * Get reason
   * @return reason
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_REASON)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getReason() {
    return reason;
  }


  @JsonProperty(JSON_PROPERTY_REASON)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setReason(String reason) {
    this.reason = reason;
  }


  public VerifierSignatureDTO location(String location) {
    
    this.location = location;
    return this;
  }

   /**
   * Get location
   * @return location
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_LOCATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLocation() {
    return location;
  }


  @JsonProperty(JSON_PROPERTY_LOCATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLocation(String location) {
    this.location = location;
  }


  public VerifierSignatureDTO qualifiedSignature(Boolean qualifiedSignature) {
    
    this.qualifiedSignature = qualifiedSignature;
    return this;
  }

   /**
   * Get qualifiedSignature
   * @return qualifiedSignature
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_QUALIFIED_SIGNATURE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getQualifiedSignature() {
    return qualifiedSignature;
  }


  @JsonProperty(JSON_PROPERTY_QUALIFIED_SIGNATURE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setQualifiedSignature(Boolean qualifiedSignature) {
    this.qualifiedSignature = qualifiedSignature;
  }


  public VerifierSignatureDTO pkcs7(Boolean pkcs7) {
    
    this.pkcs7 = pkcs7;
    return this;
  }

   /**
   * Get pkcs7
   * @return pkcs7
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_PKCS7)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getPkcs7() {
    return pkcs7;
  }


  @JsonProperty(JSON_PROPERTY_PKCS7)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPkcs7(Boolean pkcs7) {
    this.pkcs7 = pkcs7;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VerifierSignatureDTO verifierSignatureDTO = (VerifierSignatureDTO) o;
    return Objects.equals(this.id, verifierSignatureDTO.id) &&
        Objects.equals(this.format, verifierSignatureDTO.format) &&
        Objects.equals(this.requestedFormat, verifierSignatureDTO.requestedFormat) &&
        Objects.equals(this.encryptionAlgorithm, verifierSignatureDTO.encryptionAlgorithm) &&
        Objects.equals(this.digestAlgorithm, verifierSignatureDTO.digestAlgorithm) &&
        Objects.equals(this.level, verifierSignatureDTO.level) &&
        Objects.equals(this.signingTime, verifierSignatureDTO.signingTime) &&
        Objects.equals(this.validationDisabled, verifierSignatureDTO.validationDisabled) &&
        Objects.equals(this.validationStatus, verifierSignatureDTO.validationStatus) &&
        Objects.equals(this.indication, verifierSignatureDTO.indication) &&
        Objects.equals(this.subIndication, verifierSignatureDTO.subIndication) &&
        Objects.equals(this.policyId, verifierSignatureDTO.policyId) &&
        Objects.equals(this.errorMessage, verifierSignatureDTO.errorMessage) &&
        Objects.equals(this.signedBy, verifierSignatureDTO.signedBy) &&
        Objects.equals(this.signerId, verifierSignatureDTO.signerId) &&
        Objects.equals(this.issuerBy, verifierSignatureDTO.issuerBy) &&
        Objects.equals(this.code, verifierSignatureDTO.code) &&
        Objects.equals(this.certificate, verifierSignatureDTO.certificate) &&
        Objects.equals(this.timeStamps, verifierSignatureDTO.timeStamps) &&
        Objects.equals(this.unsignedChanges, verifierSignatureDTO.unsignedChanges) &&
        Objects.equals(this.reason, verifierSignatureDTO.reason) &&
        Objects.equals(this.location, verifierSignatureDTO.location) &&
        Objects.equals(this.qualifiedSignature, verifierSignatureDTO.qualifiedSignature) &&
        Objects.equals(this.pkcs7, verifierSignatureDTO.pkcs7);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, format, requestedFormat, encryptionAlgorithm, digestAlgorithm, level, signingTime, validationDisabled, validationStatus, indication, subIndication, policyId, errorMessage, signedBy, signerId, issuerBy, code, certificate, timeStamps, unsignedChanges, reason, location, qualifiedSignature, pkcs7);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VerifierSignatureDTO {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    format: ").append(toIndentedString(format)).append("\n");
    sb.append("    requestedFormat: ").append(toIndentedString(requestedFormat)).append("\n");
    sb.append("    encryptionAlgorithm: ").append(toIndentedString(encryptionAlgorithm)).append("\n");
    sb.append("    digestAlgorithm: ").append(toIndentedString(digestAlgorithm)).append("\n");
    sb.append("    level: ").append(toIndentedString(level)).append("\n");
    sb.append("    signingTime: ").append(toIndentedString(signingTime)).append("\n");
    sb.append("    validationDisabled: ").append(toIndentedString(validationDisabled)).append("\n");
    sb.append("    validationStatus: ").append(toIndentedString(validationStatus)).append("\n");
    sb.append("    indication: ").append(toIndentedString(indication)).append("\n");
    sb.append("    subIndication: ").append(toIndentedString(subIndication)).append("\n");
    sb.append("    policyId: ").append(toIndentedString(policyId)).append("\n");
    sb.append("    errorMessage: ").append(toIndentedString(errorMessage)).append("\n");
    sb.append("    signedBy: ").append(toIndentedString(signedBy)).append("\n");
    sb.append("    signerId: ").append(toIndentedString(signerId)).append("\n");
    sb.append("    issuerBy: ").append(toIndentedString(issuerBy)).append("\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    certificate: ").append(toIndentedString(certificate)).append("\n");
    sb.append("    timeStamps: ").append(toIndentedString(timeStamps)).append("\n");
    sb.append("    unsignedChanges: ").append(toIndentedString(unsignedChanges)).append("\n");
    sb.append("    reason: ").append(toIndentedString(reason)).append("\n");
    sb.append("    location: ").append(toIndentedString(location)).append("\n");
    sb.append("    qualifiedSignature: ").append(toIndentedString(qualifiedSignature)).append("\n");
    sb.append("    pkcs7: ").append(toIndentedString(pkcs7)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

