/*
 * Viafirma API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.3.29-r83-596fbc1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.OffsetDateTime;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * VerifierCrlDTO
 */
@JsonPropertyOrder({
  VerifierCrlDTO.JSON_PROPERTY_TYPE,
  VerifierCrlDTO.JSON_PROPERTY_VERSION,
  VerifierCrlDTO.JSON_PROPERTY_ISSUER,
  VerifierCrlDTO.JSON_PROPERTY_SIGNING_ALGORITHM,
  VerifierCrlDTO.JSON_PROPERTY_SIGNING_O_I_D,
  VerifierCrlDTO.JSON_PROPERTY_NEXT_UPDATE,
  VerifierCrlDTO.JSON_PROPERTY_THIS_UPDATE
})
@JsonTypeName("VerifierCrlDTO")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-03-04T11:20:43.685+01:00[Europe/Paris]")
public class VerifierCrlDTO {
  public static final String JSON_PROPERTY_TYPE = "type";
  private String type;

  public static final String JSON_PROPERTY_VERSION = "version";
  private String version;

  public static final String JSON_PROPERTY_ISSUER = "issuer";
  private String issuer;

  public static final String JSON_PROPERTY_SIGNING_ALGORITHM = "signingAlgorithm";
  private String signingAlgorithm;

  public static final String JSON_PROPERTY_SIGNING_O_I_D = "signingOID";
  private String signingOID;

  public static final String JSON_PROPERTY_NEXT_UPDATE = "nextUpdate";
  private OffsetDateTime nextUpdate;

  public static final String JSON_PROPERTY_THIS_UPDATE = "thisUpdate";
  private OffsetDateTime thisUpdate;

  public VerifierCrlDTO() { 
  }

  public VerifierCrlDTO type(String type) {
    
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getType() {
    return type;
  }


  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setType(String type) {
    this.type = type;
  }


  public VerifierCrlDTO version(String version) {
    
    this.version = version;
    return this;
  }

   /**
   * Get version
   * @return version
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_VERSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getVersion() {
    return version;
  }


  @JsonProperty(JSON_PROPERTY_VERSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVersion(String version) {
    this.version = version;
  }


  public VerifierCrlDTO issuer(String issuer) {
    
    this.issuer = issuer;
    return this;
  }

   /**
   * Get issuer
   * @return issuer
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ISSUER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getIssuer() {
    return issuer;
  }


  @JsonProperty(JSON_PROPERTY_ISSUER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIssuer(String issuer) {
    this.issuer = issuer;
  }


  public VerifierCrlDTO signingAlgorithm(String signingAlgorithm) {
    
    this.signingAlgorithm = signingAlgorithm;
    return this;
  }

   /**
   * Get signingAlgorithm
   * @return signingAlgorithm
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SIGNING_ALGORITHM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSigningAlgorithm() {
    return signingAlgorithm;
  }


  @JsonProperty(JSON_PROPERTY_SIGNING_ALGORITHM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSigningAlgorithm(String signingAlgorithm) {
    this.signingAlgorithm = signingAlgorithm;
  }


  public VerifierCrlDTO signingOID(String signingOID) {
    
    this.signingOID = signingOID;
    return this;
  }

   /**
   * Get signingOID
   * @return signingOID
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SIGNING_O_I_D)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSigningOID() {
    return signingOID;
  }


  @JsonProperty(JSON_PROPERTY_SIGNING_O_I_D)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSigningOID(String signingOID) {
    this.signingOID = signingOID;
  }


  public VerifierCrlDTO nextUpdate(OffsetDateTime nextUpdate) {
    
    this.nextUpdate = nextUpdate;
    return this;
  }

   /**
   * Get nextUpdate
   * @return nextUpdate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_NEXT_UPDATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getNextUpdate() {
    return nextUpdate;
  }


  @JsonProperty(JSON_PROPERTY_NEXT_UPDATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNextUpdate(OffsetDateTime nextUpdate) {
    this.nextUpdate = nextUpdate;
  }


  public VerifierCrlDTO thisUpdate(OffsetDateTime thisUpdate) {
    
    this.thisUpdate = thisUpdate;
    return this;
  }

   /**
   * Get thisUpdate
   * @return thisUpdate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_THIS_UPDATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getThisUpdate() {
    return thisUpdate;
  }


  @JsonProperty(JSON_PROPERTY_THIS_UPDATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setThisUpdate(OffsetDateTime thisUpdate) {
    this.thisUpdate = thisUpdate;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VerifierCrlDTO verifierCrlDTO = (VerifierCrlDTO) o;
    return Objects.equals(this.type, verifierCrlDTO.type) &&
        Objects.equals(this.version, verifierCrlDTO.version) &&
        Objects.equals(this.issuer, verifierCrlDTO.issuer) &&
        Objects.equals(this.signingAlgorithm, verifierCrlDTO.signingAlgorithm) &&
        Objects.equals(this.signingOID, verifierCrlDTO.signingOID) &&
        Objects.equals(this.nextUpdate, verifierCrlDTO.nextUpdate) &&
        Objects.equals(this.thisUpdate, verifierCrlDTO.thisUpdate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, version, issuer, signingAlgorithm, signingOID, nextUpdate, thisUpdate);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VerifierCrlDTO {\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    issuer: ").append(toIndentedString(issuer)).append("\n");
    sb.append("    signingAlgorithm: ").append(toIndentedString(signingAlgorithm)).append("\n");
    sb.append("    signingOID: ").append(toIndentedString(signingOID)).append("\n");
    sb.append("    nextUpdate: ").append(toIndentedString(nextUpdate)).append("\n");
    sb.append("    thisUpdate: ").append(toIndentedString(thisUpdate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

