/*
 * Viafirma API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.3.29-r83-596fbc1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.VerifierCrlDTO;
import org.openapitools.client.model.VerifierOcspDTO;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * VerifierDTO
 */
@JsonPropertyOrder({
  VerifierDTO.JSON_PROPERTY_VALID_REVOCATION_SOURCE,
  VerifierDTO.JSON_PROPERTY_METHOD,
  VerifierDTO.JSON_PROPERTY_OCSP_RESPONSE,
  VerifierDTO.JSON_PROPERTY_CRL_RESPONSE,
  VerifierDTO.JSON_PROPERTY_REVOCATION_DATE,
  VerifierDTO.JSON_PROPERTY_REVOCATION_REASON,
  VerifierDTO.JSON_PROPERTY_URL,
  VerifierDTO.JSON_PROPERTY_INFO,
  VerifierDTO.JSON_PROPERTY_REVOKED,
  VerifierDTO.JSON_PROPERTY_DISABLED
})
@JsonTypeName("VerifierDTO")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-03-04T11:20:43.685+01:00[Europe/Paris]")
public class VerifierDTO {
  public static final String JSON_PROPERTY_VALID_REVOCATION_SOURCE = "validRevocationSource";
  private Boolean validRevocationSource;

  public static final String JSON_PROPERTY_METHOD = "method";
  private String method;

  public static final String JSON_PROPERTY_OCSP_RESPONSE = "ocspResponse";
  private VerifierOcspDTO ocspResponse;

  public static final String JSON_PROPERTY_CRL_RESPONSE = "crlResponse";
  private VerifierCrlDTO crlResponse;

  public static final String JSON_PROPERTY_REVOCATION_DATE = "revocationDate";
  private OffsetDateTime revocationDate;

  public static final String JSON_PROPERTY_REVOCATION_REASON = "revocationReason";
  private String revocationReason;

  public static final String JSON_PROPERTY_URL = "url";
  private String url;

  public static final String JSON_PROPERTY_INFO = "info";
  private List<String> info = null;

  public static final String JSON_PROPERTY_REVOKED = "revoked";
  private Boolean revoked;

  public static final String JSON_PROPERTY_DISABLED = "disabled";
  private Boolean disabled;

  public VerifierDTO() { 
  }

  public VerifierDTO validRevocationSource(Boolean validRevocationSource) {
    
    this.validRevocationSource = validRevocationSource;
    return this;
  }

   /**
   * Get validRevocationSource
   * @return validRevocationSource
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_VALID_REVOCATION_SOURCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getValidRevocationSource() {
    return validRevocationSource;
  }


  @JsonProperty(JSON_PROPERTY_VALID_REVOCATION_SOURCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setValidRevocationSource(Boolean validRevocationSource) {
    this.validRevocationSource = validRevocationSource;
  }


  public VerifierDTO method(String method) {
    
    this.method = method;
    return this;
  }

   /**
   * Get method
   * @return method
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_METHOD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getMethod() {
    return method;
  }


  @JsonProperty(JSON_PROPERTY_METHOD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMethod(String method) {
    this.method = method;
  }


  public VerifierDTO ocspResponse(VerifierOcspDTO ocspResponse) {
    
    this.ocspResponse = ocspResponse;
    return this;
  }

   /**
   * Get ocspResponse
   * @return ocspResponse
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_OCSP_RESPONSE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public VerifierOcspDTO getOcspResponse() {
    return ocspResponse;
  }


  @JsonProperty(JSON_PROPERTY_OCSP_RESPONSE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOcspResponse(VerifierOcspDTO ocspResponse) {
    this.ocspResponse = ocspResponse;
  }


  public VerifierDTO crlResponse(VerifierCrlDTO crlResponse) {
    
    this.crlResponse = crlResponse;
    return this;
  }

   /**
   * Get crlResponse
   * @return crlResponse
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CRL_RESPONSE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public VerifierCrlDTO getCrlResponse() {
    return crlResponse;
  }


  @JsonProperty(JSON_PROPERTY_CRL_RESPONSE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCrlResponse(VerifierCrlDTO crlResponse) {
    this.crlResponse = crlResponse;
  }


  public VerifierDTO revocationDate(OffsetDateTime revocationDate) {
    
    this.revocationDate = revocationDate;
    return this;
  }

   /**
   * Get revocationDate
   * @return revocationDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_REVOCATION_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getRevocationDate() {
    return revocationDate;
  }


  @JsonProperty(JSON_PROPERTY_REVOCATION_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRevocationDate(OffsetDateTime revocationDate) {
    this.revocationDate = revocationDate;
  }


  public VerifierDTO revocationReason(String revocationReason) {
    
    this.revocationReason = revocationReason;
    return this;
  }

   /**
   * Get revocationReason
   * @return revocationReason
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_REVOCATION_REASON)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getRevocationReason() {
    return revocationReason;
  }


  @JsonProperty(JSON_PROPERTY_REVOCATION_REASON)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRevocationReason(String revocationReason) {
    this.revocationReason = revocationReason;
  }


  public VerifierDTO url(String url) {
    
    this.url = url;
    return this;
  }

   /**
   * Get url
   * @return url
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUrl() {
    return url;
  }


  @JsonProperty(JSON_PROPERTY_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUrl(String url) {
    this.url = url;
  }


  public VerifierDTO info(List<String> info) {
    
    this.info = info;
    return this;
  }

  public VerifierDTO addInfoItem(String infoItem) {
    if (this.info == null) {
      this.info = new ArrayList<>();
    }
    this.info.add(infoItem);
    return this;
  }

   /**
   * Get info
   * @return info
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_INFO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getInfo() {
    return info;
  }


  @JsonProperty(JSON_PROPERTY_INFO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setInfo(List<String> info) {
    this.info = info;
  }


  public VerifierDTO revoked(Boolean revoked) {
    
    this.revoked = revoked;
    return this;
  }

   /**
   * Get revoked
   * @return revoked
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_REVOKED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getRevoked() {
    return revoked;
  }


  @JsonProperty(JSON_PROPERTY_REVOKED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRevoked(Boolean revoked) {
    this.revoked = revoked;
  }


  public VerifierDTO disabled(Boolean disabled) {
    
    this.disabled = disabled;
    return this;
  }

   /**
   * Get disabled
   * @return disabled
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_DISABLED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getDisabled() {
    return disabled;
  }


  @JsonProperty(JSON_PROPERTY_DISABLED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDisabled(Boolean disabled) {
    this.disabled = disabled;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VerifierDTO verifierDTO = (VerifierDTO) o;
    return Objects.equals(this.validRevocationSource, verifierDTO.validRevocationSource) &&
        Objects.equals(this.method, verifierDTO.method) &&
        Objects.equals(this.ocspResponse, verifierDTO.ocspResponse) &&
        Objects.equals(this.crlResponse, verifierDTO.crlResponse) &&
        Objects.equals(this.revocationDate, verifierDTO.revocationDate) &&
        Objects.equals(this.revocationReason, verifierDTO.revocationReason) &&
        Objects.equals(this.url, verifierDTO.url) &&
        Objects.equals(this.info, verifierDTO.info) &&
        Objects.equals(this.revoked, verifierDTO.revoked) &&
        Objects.equals(this.disabled, verifierDTO.disabled);
  }

  @Override
  public int hashCode() {
    return Objects.hash(validRevocationSource, method, ocspResponse, crlResponse, revocationDate, revocationReason, url, info, revoked, disabled);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VerifierDTO {\n");
    sb.append("    validRevocationSource: ").append(toIndentedString(validRevocationSource)).append("\n");
    sb.append("    method: ").append(toIndentedString(method)).append("\n");
    sb.append("    ocspResponse: ").append(toIndentedString(ocspResponse)).append("\n");
    sb.append("    crlResponse: ").append(toIndentedString(crlResponse)).append("\n");
    sb.append("    revocationDate: ").append(toIndentedString(revocationDate)).append("\n");
    sb.append("    revocationReason: ").append(toIndentedString(revocationReason)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    info: ").append(toIndentedString(info)).append("\n");
    sb.append("    revoked: ").append(toIndentedString(revoked)).append("\n");
    sb.append("    disabled: ").append(toIndentedString(disabled)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

