/*
 * Viafirma API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.3.29-r83-596fbc1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.OffsetDateTime;
import org.openapitools.client.model.VerifierCertificateDTO;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * VerifierTimeStampDTO
 */
@JsonPropertyOrder({
  VerifierTimeStampDTO.JSON_PROPERTY_TYPE,
  VerifierTimeStampDTO.JSON_PROPERTY_INDICATION,
  VerifierTimeStampDTO.JSON_PROPERTY_SUB_INDICATION,
  VerifierTimeStampDTO.JSON_PROPERTY_DIGEST_ALGO,
  VerifierTimeStampDTO.JSON_PROPERTY_PRODUCTION_TIME,
  VerifierTimeStampDTO.JSON_PROPERTY_SIGNED_BY,
  VerifierTimeStampDTO.JSON_PROPERTY_CERTIFICATE,
  VerifierTimeStampDTO.JSON_PROPERTY_VALIDATION_STATUS,
  VerifierTimeStampDTO.JSON_PROPERTY_ISSUER_BY
})
@JsonTypeName("VerifierTimeStampDTO")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-03-04T11:20:43.685+01:00[Europe/Paris]")
public class VerifierTimeStampDTO {
  public static final String JSON_PROPERTY_TYPE = "type";
  private String type;

  public static final String JSON_PROPERTY_INDICATION = "indication";
  private String indication;

  public static final String JSON_PROPERTY_SUB_INDICATION = "subIndication";
  private String subIndication;

  public static final String JSON_PROPERTY_DIGEST_ALGO = "digestAlgo";
  private String digestAlgo;

  public static final String JSON_PROPERTY_PRODUCTION_TIME = "productionTime";
  private OffsetDateTime productionTime;

  public static final String JSON_PROPERTY_SIGNED_BY = "signedBy";
  private String signedBy;

  public static final String JSON_PROPERTY_CERTIFICATE = "certificate";
  private VerifierCertificateDTO certificate;

  /**
   * Gets or Sets validationStatus
   */
  public enum ValidationStatusEnum {
    VALID("VALID"),
    
    UNKNOWN("UNKNOWN"),
    
    INVALID("INVALID");

    private String value;

    ValidationStatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ValidationStatusEnum fromValue(String value) {
      for (ValidationStatusEnum b : ValidationStatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_VALIDATION_STATUS = "validationStatus";
  private ValidationStatusEnum validationStatus;

  public static final String JSON_PROPERTY_ISSUER_BY = "issuerBy";
  private String issuerBy;

  public VerifierTimeStampDTO() { 
  }

  public VerifierTimeStampDTO type(String type) {
    
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getType() {
    return type;
  }


  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setType(String type) {
    this.type = type;
  }


  public VerifierTimeStampDTO indication(String indication) {
    
    this.indication = indication;
    return this;
  }

   /**
   * Get indication
   * @return indication
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_INDICATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getIndication() {
    return indication;
  }


  @JsonProperty(JSON_PROPERTY_INDICATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIndication(String indication) {
    this.indication = indication;
  }


  public VerifierTimeStampDTO subIndication(String subIndication) {
    
    this.subIndication = subIndication;
    return this;
  }

   /**
   * Get subIndication
   * @return subIndication
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SUB_INDICATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSubIndication() {
    return subIndication;
  }


  @JsonProperty(JSON_PROPERTY_SUB_INDICATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSubIndication(String subIndication) {
    this.subIndication = subIndication;
  }


  public VerifierTimeStampDTO digestAlgo(String digestAlgo) {
    
    this.digestAlgo = digestAlgo;
    return this;
  }

   /**
   * Get digestAlgo
   * @return digestAlgo
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_DIGEST_ALGO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDigestAlgo() {
    return digestAlgo;
  }


  @JsonProperty(JSON_PROPERTY_DIGEST_ALGO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDigestAlgo(String digestAlgo) {
    this.digestAlgo = digestAlgo;
  }


  public VerifierTimeStampDTO productionTime(OffsetDateTime productionTime) {
    
    this.productionTime = productionTime;
    return this;
  }

   /**
   * Get productionTime
   * @return productionTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_PRODUCTION_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getProductionTime() {
    return productionTime;
  }


  @JsonProperty(JSON_PROPERTY_PRODUCTION_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProductionTime(OffsetDateTime productionTime) {
    this.productionTime = productionTime;
  }


  public VerifierTimeStampDTO signedBy(String signedBy) {
    
    this.signedBy = signedBy;
    return this;
  }

   /**
   * Get signedBy
   * @return signedBy
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SIGNED_BY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSignedBy() {
    return signedBy;
  }


  @JsonProperty(JSON_PROPERTY_SIGNED_BY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSignedBy(String signedBy) {
    this.signedBy = signedBy;
  }


  public VerifierTimeStampDTO certificate(VerifierCertificateDTO certificate) {
    
    this.certificate = certificate;
    return this;
  }

   /**
   * Get certificate
   * @return certificate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CERTIFICATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public VerifierCertificateDTO getCertificate() {
    return certificate;
  }


  @JsonProperty(JSON_PROPERTY_CERTIFICATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCertificate(VerifierCertificateDTO certificate) {
    this.certificate = certificate;
  }


  public VerifierTimeStampDTO validationStatus(ValidationStatusEnum validationStatus) {
    
    this.validationStatus = validationStatus;
    return this;
  }

   /**
   * Get validationStatus
   * @return validationStatus
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_VALIDATION_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ValidationStatusEnum getValidationStatus() {
    return validationStatus;
  }


  @JsonProperty(JSON_PROPERTY_VALIDATION_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setValidationStatus(ValidationStatusEnum validationStatus) {
    this.validationStatus = validationStatus;
  }


  public VerifierTimeStampDTO issuerBy(String issuerBy) {
    
    this.issuerBy = issuerBy;
    return this;
  }

   /**
   * Get issuerBy
   * @return issuerBy
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ISSUER_BY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getIssuerBy() {
    return issuerBy;
  }


  @JsonProperty(JSON_PROPERTY_ISSUER_BY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIssuerBy(String issuerBy) {
    this.issuerBy = issuerBy;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VerifierTimeStampDTO verifierTimeStampDTO = (VerifierTimeStampDTO) o;
    return Objects.equals(this.type, verifierTimeStampDTO.type) &&
        Objects.equals(this.indication, verifierTimeStampDTO.indication) &&
        Objects.equals(this.subIndication, verifierTimeStampDTO.subIndication) &&
        Objects.equals(this.digestAlgo, verifierTimeStampDTO.digestAlgo) &&
        Objects.equals(this.productionTime, verifierTimeStampDTO.productionTime) &&
        Objects.equals(this.signedBy, verifierTimeStampDTO.signedBy) &&
        Objects.equals(this.certificate, verifierTimeStampDTO.certificate) &&
        Objects.equals(this.validationStatus, verifierTimeStampDTO.validationStatus) &&
        Objects.equals(this.issuerBy, verifierTimeStampDTO.issuerBy);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, indication, subIndication, digestAlgo, productionTime, signedBy, certificate, validationStatus, issuerBy);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VerifierTimeStampDTO {\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    indication: ").append(toIndentedString(indication)).append("\n");
    sb.append("    subIndication: ").append(toIndentedString(subIndication)).append("\n");
    sb.append("    digestAlgo: ").append(toIndentedString(digestAlgo)).append("\n");
    sb.append("    productionTime: ").append(toIndentedString(productionTime)).append("\n");
    sb.append("    signedBy: ").append(toIndentedString(signedBy)).append("\n");
    sb.append("    certificate: ").append(toIndentedString(certificate)).append("\n");
    sb.append("    validationStatus: ").append(toIndentedString(validationStatus)).append("\n");
    sb.append("    issuerBy: ").append(toIndentedString(issuerBy)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

